class AmusementParkRunner{
	public static void main(String park[]){
		System.out.println("main started");
	
		AmusementPark parkOne=new AmusementPark();
		parkOne.parkId = 1;
		parkOne.name = "Green Valley Park";
		parkOne.location = "Mysore";
		parkOne.openingTime = "7:00";
		parkOne.closingTime = "6:00";
		parkOne.entryFee = 150.00;
			System.out.println();
			System.out.println("Park one details: ");
			System.out.println("id of park is:"+parkOne.parkId);
			System.out.println("name of the park is:"+parkOne.name);
			System.out.println("Park is located at :"+parkOne.location);
			System.out.println("opening time of the park is :"+parkOne.openingTime);
			System.out.println("closing Time of the park is:"+parkOne.closingTime);
			System.out.println("entry fee of the park is:"+parkOne.entryFee);
	
		AmusementPark parkTwo=new AmusementPark();
		parkTwo.parkId=2;
		parkTwo.name="Wonderla";
		parkTwo.location="Banglore";
		parkTwo.openingTime="8:00";
		parkTwo.closingTime="7:30";
		parkTwo.entryFee=1000.00;
			System.out.println();
			System.out.println("Park two details: ");
			System.out.println("id of park is:"+parkTwo.parkId);
			System.out.println("name of the park is:"+parkTwo.name);
			System.out.println("Park is located at :"+parkTwo.location);
			System.out.println("opening time of the park is :"+parkTwo.openingTime);
			System.out.println("closing Time of the park is:"+parkTwo.closingTime);
			System.out.println("entry fee of the park is:"+parkTwo.entryFee);
		
		AmusementPark parkThree=new AmusementPark();
		parkThree.parkId = 3;
		parkThree.name = "Nature Nest";
		parkThree.location = "Chennai";
		parkThree.openingTime = "6:30";
		parkThree.closingTime = "7:00";
		parkThree.entryFee = 100.00;
			System.out.println();
			System.out.println("Park three details: ");
			System.out.println("id of park is:"+parkThree.parkId);
			System.out.println("name of the park is:"+parkThree.name);
			System.out.println("Park is located at :"+parkThree.location);
			System.out.println("opening time of the park is :"+parkThree.openingTime);
			System.out.println("closing Time of the park is:"+parkThree.closingTime);
			System.out.println("entry fee of the park is:"+parkThree.entryFee);
		
		AmusementPark parkFour=new AmusementPark();
		parkFour.parkId = 4;
		parkFour.name = "Lakeside Garden";
		parkFour.location = "Hyderabad";
		parkFour.openingTime = "8:00";
		parkFour.closingTime = "7:30";
		parkFour.entryFee = 120.00;
			System.out.println();
			System.out.println("Park four details: ");
			System.out.println("id of park is:"+parkFour.parkId);
			System.out.println("name of the park is:"+parkFour.name);
			System.out.println("Park is located at :"+parkFour.location);
			System.out.println("opening time of the park is :"+parkFour.openingTime);
			System.out.println("closing Time of the park is:"+parkFour.closingTime);
			System.out.println("entry fee of the park is:"+parkFour.entryFee);
		
		AmusementPark parkFive=new AmusementPark();
		parkFive.parkId = 5;
		parkFive.name = "Rose Garden";
		parkFive.location = "Ooty";
		parkFive.openingTime = "9:00";
		parkFive.closingTime = "6:00";
		parkFive.entryFee = 200.00;
			System.out.println();
			System.out.println("Park five details: ");
			System.out.println("id of park is:"+parkFive.parkId);
			System.out.println("name of the park is:"+parkFive.name);
			System.out.println("Park is located at :"+parkFive.location);
			System.out.println("opening time of the park is :"+parkFive.openingTime);
			System.out.println("closing Time of the park is:"+parkFive.closingTime);
			System.out.println("entry fee of the park is:"+parkFive.entryFee);
			
		AmusementPark parkSix=new AmusementPark();
		parkSix.parkId = 6;
		parkSix.name = "Sunset Park";
		parkSix.location = "Mangalore";
		parkSix.openingTime = "6:00";
		parkSix.closingTime = "6:30";
		parkSix.entryFee = 180.00;
			System.out.println();
			System.out.println("Park six details: ");
			System.out.println("id of park is:"+parkSix.parkId);
			System.out.println("name of the park is:"+parkSix.name);
			System.out.println("Park is located at :"+parkSix.location);
			System.out.println("opening time of the park is :"+parkSix.openingTime);
			System.out.println("closing Time of the park is:"+parkSix.closingTime);
			System.out.println("entry fee of the park is:"+parkSix.entryFee);
		
		AmusementPark parkSeven=new AmusementPark();
		parkSeven.parkId = 7;
		parkSeven.name = "Wild Woods";
		parkSeven.location = "Madikeri";
		parkSeven.openingTime = "7:30";
		parkSeven.closingTime = "6:30";
		parkSeven.entryFee = 220.00;
			System.out.println();
			System.out.println("Park seven details: ");
			System.out.println("id of park is:"+parkSeven.parkId);
			System.out.println("name of the park is:"+parkSeven.name);
			System.out.println("Park is located at :"+parkSeven.location);
			System.out.println("opening time of the park is :"+parkSeven.openingTime);
			System.out.println("closing Time of the park is:"+parkSeven.closingTime);
			System.out.println("entry fee of the park is:"+parkSeven.entryFee);
		
		AmusementPark parkEight=new AmusementPark();
		parkEight.parkId = 8;
		parkEight.name = "City Eco Park";
		parkEight.location = "Bangalore";
		parkEight.openingTime = "8:00";
		parkEight.closingTime = "8:00";
		parkEight.entryFee = 250.00;
			System.out.println();
			System.out.println("Park eight details: ");
			System.out.println("id of park is:"+parkEight.parkId);
			System.out.println("name of the park is:"+parkEight.name);
			System.out.println("Park is located at :"+parkEight.location);
			System.out.println("opening time of the park is :"+parkEight.openingTime);
			System.out.println("closing Time of the park is:"+parkEight.closingTime);
			System.out.println("entry fee of the park is:"+parkEight.entryFee);
		
		AmusementPark parkNine=new AmusementPark();
		parkNine.parkId = 9;
		parkNine.name = "Hilltop Park";
		parkNine.location = "Shimla";
		parkNine.openingTime = "5:30";
		parkNine.closingTime = "6:00";
		parkNine.entryFee = 300.00;
			System.out.println();
			System.out.println("Park nine details: ");
			System.out.println("id of park is:"+parkNine.parkId);
			System.out.println("name of the park is:"+parkNine.name);
			System.out.println("Park is located at :"+parkNine.location);
			System.out.println("opening time of the park is :"+parkNine.openingTime);
			System.out.println("closing Time of the park is:"+parkNine.closingTime);
			System.out.println("entry fee of the park is:"+parkNine.entryFee);
		
		AmusementPark parkTen=new AmusementPark();
		parkTen.parkId = 10;
		parkTen.name = "Pebble Garden";
		parkTen.location = "Pune";
		parkTen.openingTime = "7:00";
		parkTen.closingTime = "7:00";
		parkTen.entryFee = 160.00;
			System.out.println();
			System.out.println("Park ten details: ");
			System.out.println("id of park is:"+parkTen.parkId);
			System.out.println("name of the park is:"+parkTen.name);
			System.out.println("Park is located at :"+parkTen.location);
			System.out.println("opening time of the park is :"+parkTen.openingTime);
			System.out.println("closing Time of the park is:"+parkTen.closingTime);
			System.out.println("entry fee of the park is:"+parkTen.entryFee);
		
		AmusementPark parkEleven=new AmusementPark();
		parkEleven.parkId = 11;
		parkEleven.name = "Nature's Hug";
		parkEleven.location = "Delhi";
		parkEleven.openingTime = "6:00";
		parkEleven.closingTime = "6:30";
		parkEleven.entryFee = 120.00;
			System.out.println();
			System.out.println("Park eleven details: ");
			System.out.println("id of park is:"+parkEleven.parkId);
			System.out.println("name of the park is:"+parkEleven.name);
			System.out.println("Park is located at :"+parkEleven.location);
			System.out.println("opening time of the park is :"+parkEleven.openingTime);
			System.out.println("closing Time of the park is:"+parkEleven.closingTime);
			System.out.println("entry fee of the park is:"+parkEleven.entryFee);
			
		AmusementPark parkTwelve=new AmusementPark();
		parkTwelve.parkId = 12;
		parkTwelve.name = "Riverfront Park";
		parkTwelve.location = "Ahmedabad";
		parkTwelve.openingTime = "6:00";
		parkTwelve.closingTime = "9:00";
		parkTwelve.entryFee = 90.00;
			System.out.println();
			System.out.println("Park twelve details: ");
			System.out.println("id of park is:"+parkTwelve.parkId);
			System.out.println("name of the park is:"+parkTwelve.name);
			System.out.println("Park is located at :"+parkTwelve.location);
			System.out.println("opening time of the park is :"+parkTwelve.openingTime);
			System.out.println("closing Time of the park is:"+parkTwelve.closingTime);
			System.out.println("entry fee of the park is:"+parkTwelve.entryFee);
		
		AmusementPark parkThirteen=new AmusementPark();
		parkThirteen.parkId = 13;
		parkThirteen.name = "Adventure Zone";
		parkThirteen.location = "Manali";
		parkThirteen.openingTime = "8:30";
		parkThirteen.closingTime = "5:30";
		parkThirteen.entryFee = 500.00;
			System.out.println();
			System.out.println("Park thirteen details: ");
			System.out.println("id of park is:"+parkThirteen.parkId);
			System.out.println("name of the park is:"+parkThirteen.name);
			System.out.println("Park is located at :"+parkThirteen.location);
			System.out.println("opening time of the park is :"+parkThirteen.openingTime);
			System.out.println("closing Time of the park is:"+parkThirteen.closingTime);
			System.out.println("entry fee of the park is:"+parkThirteen.entryFee);
		
		AmusementPark parkFourteen=new AmusementPark();
		parkFourteen.parkId = 14;
		parkFourteen.name = "Whispering Pines";
		parkFourteen.location = "Coorg";
		parkFourteen.openingTime = "7:00";
		parkFourteen.closingTime = "7:00";
		parkFourteen.entryFee = 350.00;
			System.out.println();
			System.out.println("Park fourteen details: ");
			System.out.println("id of park is:"+parkFourteen.parkId);
			System.out.println("name of the park is:"+parkFourteen.name);
			System.out.println("Park is located at :"+parkFourteen.location);
			System.out.println("opening time of the park is :"+parkFourteen.openingTime);
			System.out.println("closing Time of the park is:"+parkFourteen.closingTime);
			System.out.println("entry fee of the park is:"+parkFourteen.entryFee);
		
		AmusementPark parkFifteen=new AmusementPark();
		parkFifteen.parkId = 15;
		parkFifteen.name = "Floral World";
		parkFifteen.location = "Chandigarh";
		parkFifteen.openingTime = "9:00";
		parkFifteen.closingTime = "5:00";
		parkFifteen.entryFee = 80.00;
			System.out.println();
			System.out.println("Park fifteen details: ");
			System.out.println("id of park is:"+parkFifteen.parkId);
			System.out.println("name of the park is:"+parkFifteen.name);
			System.out.println("Park is located at :"+parkFifteen.location);
			System.out.println("opening time of the park is :"+parkFifteen.openingTime);
			System.out.println("closing Time of the park is:"+parkFifteen.closingTime);
			System.out.println("entry fee of the park is:"+parkFifteen.entryFee);	
		
		AmusementPark parkSixteen=new AmusementPark();
		parkSixteen.parkId = 16;
		parkSixteen.name = "Botanical Paradise";
		parkSixteen.location = "Thiruvananthapuram";
		parkSixteen.openingTime = "7:00";
		parkSixteen.closingTime = "6:00";
		parkSixteen.entryFee = 60.00;
			System.out.println();
			System.out.println("Park sixteen details: ");
			System.out.println("id of park is:"+parkSixteen.parkId);
			System.out.println("name of the park is:"+parkSixteen.name);
			System.out.println("Park is located at :"+parkSixteen.location);
			System.out.println("opening time of the park is :"+parkSixteen.openingTime);
			System.out.println("closing Time of the park is:"+parkSixteen.closingTime);
			System.out.println("entry fee of the park is:"+parkSixteen.entryFee);
		
		AmusementPark parkSeventeen=new AmusementPark();
		parkSeventeen.parkId = 17;
		parkSeventeen.name = "Urban Forest";
		parkSeventeen.location = "Nagpur";
		parkSeventeen.openingTime = "6:30";
		parkSeventeen.closingTime = "7:30";
		parkSeventeen.entryFee = 110.00;
			System.out.println();
			System.out.println("Park seventeen details: ");
			System.out.println("id of park is:"+parkSeventeen.parkId);
			System.out.println("name of the park is:"+parkSeventeen.name);
			System.out.println("Park is located at :"+parkSeventeen.location);
			System.out.println("opening time of the park is :"+parkSeventeen.openingTime);
			System.out.println("closing Time of the park is:"+parkSeventeen.closingTime);
			System.out.println("entry fee of the park is:"+parkSeventeen.entryFee);
		
		AmusementPark parkEighteen=new AmusementPark();
		parkEighteen.parkId = 18;
		parkEighteen.name = "Waterfall Retreat";
		parkEighteen.location = "Shillong";
		parkEighteen.openingTime = "8:00";
		parkEighteen.closingTime = "6:00";
		parkEighteen.entryFee = 270.00;
			System.out.println();
			System.out.println("Park eighteen details: ");
			System.out.println("id of park is:"+parkEighteen.parkId);
			System.out.println("name of the park is:"+parkEighteen.name);
			System.out.println("Park is located at :"+parkEighteen.location);
			System.out.println("opening time of the park is :"+parkEighteen.openingTime);
			System.out.println("closing Time of the park is:"+parkEighteen.closingTime);
			System.out.println("entry fee of the park is:"+parkEighteen.entryFee);
		
		AmusementPark parkNineteen=new AmusementPark();
		parkNineteen.parkId = 19;
		parkNineteen.name = "Deer Park";
		parkNineteen.location = "Visakhapatnam";
		parkNineteen.openingTime = "9:00";
		parkNineteen.closingTime = "6:30";
		parkNineteen.entryFee = 95.00;
			System.out.println();
			System.out.println("Park nineteen details: ");
			System.out.println("id of park is:"+parkNineteen.parkId);
			System.out.println("name of the park is:"+parkNineteen.name);
			System.out.println("Park is located at :"+parkNineteen.location);
			System.out.println("opening time of the park is :"+parkNineteen.openingTime);
			System.out.println("closing Time of the park is:"+parkNineteen.closingTime);
			System.out.println("entry fee of the park is:"+parkNineteen.entryFee);
		
		AmusementPark parkTwenty=new AmusementPark();
		parkTwenty.parkId = 20;
		parkTwenty.name = "Eco Harmony Park";
		parkTwenty.location = "Bangalore";
		parkTwenty.openingTime = "6:30";
		parkTwenty.closingTime = "7:30";
		parkTwenty.entryFee = 190.00;
			System.out.println();
			System.out.println("Park twenty details: ");
			System.out.println("id of park is:"+parkTwenty.parkId);
			System.out.println("name of the park is:"+parkTwenty.name);
			System.out.println("Park is located at :"+parkTwenty.location);
			System.out.println("opening time of the park is :"+parkTwenty.openingTime);
			System.out.println("closing Time of the park is:"+parkTwenty.closingTime);
			System.out.println("entry fee of the park is:"+parkTwenty.entryFee);
			System.out.println();
	System.out.println("main ended");
	}
}