class Apartment{
	static String apartmentName;
	static String location;
	static int noOfFloors;
	static int noOfFlats;
	static String flatTypes;
	static boolean isElevatorAvailable;
	static int noOfWorkers;
	static double priceOfTwoBhk;
	static double priceOfThreeBhk;
	static double rentPrice;
	static boolean isSwimmingPool;
	static boolean isKidsPlayground;
	static boolean isSmartHome;
	static boolean isFullyFurnished;
	static boolean isGasPipelineAvailable;
	static String buildingType;
	static String ownerName;
	static boolean isWebsiteAvailable;
	static int size;
	static int parkingCapacity;
	public static void main(String apartment[]){
			System.out.println("The apartment name is "+apartmentName);
			System.out.println("The location of the apartment is "+location);
			System.out.println("The number of floors in the apartment are "+noOfFloors);
			System.out.println("The number of flats are "+noOfFlats);
			System.out.println("The flat types of the apartment is "+flatTypes);
			System.out.println("is elevator available? "+isElevatorAvailable);
			System.out.println("The number of workers are "+noOfWorkers);
			System.out.println("The price of 2BHK flat is "+priceOfTwoBhk);
			System.out.println("The price of 3BHK flat is "+priceOfThreeBhk);
			System.out.println("The rent price of th flat is "+rentPrice);
			System.out.println("Is swimming pool available? "+isSwimmingPool);
			System.out.println("Is kids playgroumd available? "+isKidsPlayground);
			System.out.println("Is full furnished flats? "+isFullyFurnished);
			System.out.println("Is gas pipeline available? "+isGasPipelineAvailable);
			System.out.println("The building type is "+buildingType);
			System.out.println("The owner of th apartment is "+ownerName);
			System.out.println("Is website available is? "+isElevatorAvailable);
			System.out.println("The size of the flat is "+size+" Sq. ft");
			System.out.println("The parking capacity is "+parkingCapacity+" Vehicles");
			System.out.println();
	 String apartmentName="DHATRI RESIDENCY";
	 String location="Whitefield, Bengaluru";
	 int noOfFloors=12;
	 int noOfFlats=120;
	 String flatTypes="2BHK , 3BHK";
	 boolean isElevatorAvailable=true;
	 int noOfWorkers=100;
	 double priceOfTwoBhk=125000.00d;
	 double priceOfThreeBhk= 300000.00d;
	 double rentPrice=25000.00d;
	 boolean isSwimmingPool=true;
	 boolean isKidsPlayground=true;
	 boolean isSmartHome=true;
	 boolean isFullyFurnished=false;
	 boolean isGasPipelineAvailable=true;
	 String buildingType="Residential";
	 String ownerName="GS BuilTech";
	 boolean isWebsiteAvailable=true;
	 int size= 1440;
	 int parkingCapacity=200;
	 		System.out.println("After re-initialization");
			System.out.println("The apartment name is "+apartmentName);
			System.out.println("The location of the apartment is "+location);
			System.out.println("The number of floors in the apartment are "+noOfFloors);
			System.out.println("The number of flats are "+noOfFlats);
			System.out.println("The flat types of the apartment is "+flatTypes);
			System.out.println("is elevator available? "+isElevatorAvailable);
			System.out.println("The number of workers are "+noOfWorkers);
			System.out.println("The price of 2BHK flat is "+priceOfTwoBhk);
			System.out.println("The price of 3BHK flat is "+priceOfThreeBhk);
			System.out.println("The rent price of th flat is "+rentPrice);
			System.out.println("Is swimming pool available? "+isSwimmingPool);
			System.out.println("Is kids playgroumd available? "+isKidsPlayground);
			System.out.println("Is full furnished flats? "+isFullyFurnished);
			System.out.println("Is gas pipeline available? "+isGasPipelineAvailable);
			System.out.println("The building type is "+buildingType);
			System.out.println("The owner of th apartment is "+ownerName);
			System.out.println("Is website available is? "+isElevatorAvailable);
			System.out.println("The size of the flat is "+size+" Sq. ft");
			System.out.println("The parking capacity is "+parkingCapacity+" Vehicles");
	
	}
}