class Bank{
	static String bankName;
	static String branchName;
	static int workingHours;
	static String ifscCode;
	static int establishedYear;
	static String corporateIdentificationNumber;
	static long phoneNumber;
	static String headOffice;
	static String emailId;
	static String chairmanName;
	static int noOfCustomers;
	static double totalAmount;
	static boolean isAtmAvailable;
	static int noOfAtm;
	static int noOfEmployees;
	static int noOfBranches;
	static String savingsInterestRate;
	static String accountTypes;
	static boolean isNetBankingAvailable;
	static String loanInterestrate;	
	public static void main(String bank[]){
		System.out.println("The Bank name is "+bankName);
		System.out.println("The branch name of the bank is "+branchName);
		System.out.println("The IFSC code of the bank is "+ifscCode);
		System.out.println("The bank was established in the year "+establishedYear);
		System.out.println("The Corporate Identification Number of the bank is "+corporateIdentificationNumber);
		System.out.println("The Phone number of the bank is "+phoneNumber);
		System.out.println("The Head Office of the bank is "+headOffice);
		System.out.println("The email id of the bank is "+emailId);
		System.out.println("The Chairman of the bank is "+chairmanName);
		System.out.println("The total number of customers of this bank are "+noOfCustomers);
		System.out.println("The total amount in the bank is "+totalAmount);
		System.out.println("Is ATM available for this bank? "+isAtmAvailable);
		System.out.println("The total number of ATM's available are "+noOfAtm);
		System.out.println("The total number of employees of this bank are "+noOfEmployees);
		System.out.println("The working hours of this bank is "+workingHours+"hrs");
		System.out.println("The total number of branches of this bank are "+noOfBranches);
		System.out.println("The Savings account interest rates are "+savingsInterestRate);
		System.out.println("The account types of this bank are : "+accountTypes);
		System.out.println("Is Net banking available for this bank? "+isNetBankingAvailable);
		System.out.println("The loan interst rates of this bank is "+loanInterestrate);
		System.out.println();
	 String bankName = "State Bank Of India";
	 String branchName = "Rajajinagar Branch";
	 int workingHours = 9;
	 String ifscCode = "SBIN0040197";
	 int establishedYear = 1955;
	 String corporateIdentificationNumber = "U65190MH1993PLC074381";
	 long phoneNumber = 7485962423l;
     String headOffice = "Mumbai";
	 String emailId = "sbi.16873@sbi.co.in";
	 String chairmanName = "Shri Challa Sreenivasulu Setty";
	 int noOfCustomers = 300000;
	 double totalAmount = 15000085950.00d;
	 boolean isAtmAvailable = true;
	 int noOfAtm = 10000;
	 int noOfEmployees = 55000;
	 int noOfBranches = 25;
	 String savingsInterestRate = "2.70% p.a.";
	 String accountTypes = "Savings Account, Current Account , Loan Account , Fixed and Recurring Deposit Account";
	 boolean isNetBankingAvailable = true;
	 String loanInterestrate = "2.70% p.a.";
		System.out.println("After re-initializatiion");
		System.out.println("The Bank name is "+bankName);
		System.out.println("The branch name of the bank is "+branchName);
		System.out.println("The IFSC code of the bank is "+ifscCode);
		System.out.println("The bank was established in the year "+establishedYear);
		System.out.println("The Corporate Identification Number of the bank is "+corporateIdentificationNumber);
		System.out.println("The Phone number of the bank is "+phoneNumber);
		System.out.println("The Head Office of the bank is "+headOffice);
		System.out.println("The email id of the bank is "+emailId);
		System.out.println("The Chairman of the bank is "+chairmanName);
		System.out.println("The total number of customers of this bank are "+noOfCustomers);
		System.out.println("The total amount in the bank is "+totalAmount);
		System.out.println("Is ATM available for this bank? "+isAtmAvailable);
		System.out.println("The total number of ATM's available are "+noOfAtm);
		System.out.println("The total number of employees of this bank are "+noOfEmployees);
		System.out.println("The working hours of this bank is "+workingHours+"hrs");
		System.out.println("The total number of branches of this bank are "+noOfBranches);
		System.out.println("The Savings account interest rates are "+savingsInterestRate);
		System.out.println("The account types of this bank are : "+accountTypes);
		System.out.println("Is Net banking available for this bank? "+isNetBankingAvailable);
		System.out.println("The loan interst rates of this bank is "+loanInterestrate);
	}
}