class BillRunner{

	public static void main(String[] args){
	
		System.out.println("main started");
			Bill firstBill= new Bill();
			firstBill.billId=1;
			firstBill.planType="Monthly Plan";
			firstBill.billAmountWithTax=199.50;
			firstBill.isTaxIncluded=true;
			firstBill.billIssueDate="07/07/2025";
			firstBill.billDueDate="15/07/2025";
			firstBill.isBillPaid=true;
			firstBill.isOverdue=false;
			firstBill.paymentMethod="UPI Transaction";
			System.out.println();
			System.out.println("First Bill Details :");
				System.out.println("The first bill id is : "+firstBill.billId);
				System.out.println("The plan type of first bill is : "+firstBill.planType);
				System.out.println("The first bill amount with tax is : "+firstBill.billAmountWithTax);
				System.out.println("Is Tax Included? "+firstBill.isTaxIncluded);
				System.out.println("First Bill Issue Date is : "+firstBill.billIssueDate);
				System.out.println("First Bill Due Date is : "+firstBill.billDueDate);
				System.out.println("Is Bill Paid? "+firstBill.isBillPaid);
				System.out.println("Is Bill OverDue? "+firstBill.isOverdue);
				System.out.println("Payment method of first bill is : "+firstBill.paymentMethod);
				
			Bill secondBill= new Bill();
			secondBill.billId=2;
			secondBill.planType="Quarterly Plan";
			secondBill.billAmountWithTax=249.90;
			secondBill.isTaxIncluded=true;
			secondBill.billIssueDate="15/06/2025";
			secondBill.billDueDate="30/06/2025";
			secondBill.isBillPaid=true;
			secondBill.isOverdue=false;
			secondBill.paymentMethod="UPI Transaction";
			System.out.println();
			System.out.println("Second Bill Details :");
				System.out.println("The second bill id is : "+secondBill.billId);
				System.out.println("The plan type of second bill is : "+secondBill.planType);
				System.out.println("The second bill amount with tax is : "+secondBill.billAmountWithTax);
				System.out.println("Is Tax Included? "+secondBill.isTaxIncluded);
				System.out.println("Second Bill Issue Date is : "+secondBill.billIssueDate);
				System.out.println("Second Bill Due Date is : "+secondBill.billDueDate);
				System.out.println("Is Bill Paid? "+secondBill.isBillPaid);
				System.out.println("Is Bill OverDue? "+secondBill.isOverdue);
				System.out.println("Payment method of second bill is : "+secondBill.paymentMethod);
				
			Bill thirdBill= new Bill();
			thirdBill.billId=3;
			thirdBill.planType="Half Yearly Plan";
			thirdBill.billAmountWithTax=499.99;
			thirdBill.isTaxIncluded=true;
			thirdBill.billIssueDate="04/03/2025";
			thirdBill.billDueDate="12/03/2025";
			thirdBill.isBillPaid=true;
			thirdBill.isOverdue=false;
			thirdBill.paymentMethod="Credit Card";
			System.out.println();
			System.out.println("Third Bill Details :");
				System.out.println("The third bill id is : "+thirdBill.billId);
				System.out.println("The plan type of third bill is : "+thirdBill.planType);
				System.out.println("The third bill amount with tax is : "+thirdBill.billAmountWithTax);
				System.out.println("Is Tax Included? "+thirdBill.isTaxIncluded);
				System.out.println("Third Bill Issue Date is : "+thirdBill.billIssueDate);
				System.out.println("Third Bill Due Date is : "+thirdBill.billDueDate);
				System.out.println("Is Bill Paid? "+thirdBill.isBillPaid);
				System.out.println("Is Bill OverDue? "+thirdBill.isOverdue);
				System.out.println("Payment method of third bill is : "+thirdBill.paymentMethod);
				
			Bill fourthBill= new Bill();
			fourthBill.billId=4;
			fourthBill.planType="Monthly Plan";
			fourthBill.billAmountWithTax=219.00;
			fourthBill.isTaxIncluded=true;
			fourthBill.billIssueDate="10/05/2025";
			fourthBill.billDueDate="15/05/2025";
			fourthBill.isBillPaid=false;
			fourthBill.isOverdue=true;
			fourthBill.paymentMethod=null;
			System.out.println();
			System.out.println("Fourth Bill Details :");
				System.out.println("The fourth bill id is : "+fourthBill.billId);
				System.out.println("The plan type of fourth bill is : "+fourthBill.planType);
				System.out.println("The fourth bill amount with tax is : "+fourthBill.billAmountWithTax);
				System.out.println("Is Tax Included? "+fourthBill.isTaxIncluded);
				System.out.println("Fourth Bill Issue Date is : "+fourthBill.billIssueDate);
				System.out.println("Fourth Bill Due Date is : "+fourthBill.billDueDate);
				System.out.println("Is Bill Paid? "+fourthBill.isBillPaid);
				System.out.println("Is Bill OverDue? "+fourthBill.isOverdue);
				System.out.println("Payment method of fourth bill is : "+fourthBill.paymentMethod);
				
			Bill fifthBill= new Bill();
			fifthBill.billId=5;
			fifthBill.planType="Yearly Plan";
			fifthBill.billAmountWithTax=1099.59;
			fifthBill.isTaxIncluded=true;
			fifthBill.billIssueDate="28/06/2024";
			fifthBill.billDueDate="05/07/2024";
			fifthBill.isBillPaid=true;
			fifthBill.isOverdue=false;
			fifthBill.paymentMethod="Credit Card";
			System.out.println();
			System.out.println("Fifth Bill Details :");
				System.out.println("The fifth bill id is : "+fifthBill.billId);
				System.out.println("The plan type of fifth bill is : "+fifthBill.planType);
				System.out.println("The fifth bill amount with tax is : "+fifthBill.billAmountWithTax);
				System.out.println("Is Tax Included? "+fifthBill.isTaxIncluded);
				System.out.println("Fifth Bill Issue Date is : "+fifthBill.billIssueDate);
				System.out.println("Fifth Bill Due Date is : "+fifthBill.billDueDate);
				System.out.println("Is Bill Paid? "+fifthBill.isBillPaid);
				System.out.println("Is Bill OverDue? "+fifthBill.isOverdue);
				System.out.println("Payment method of fifth bill is : "+fifthBill.paymentMethod);
				
			Bill sixthBill= new Bill();
			sixthBill.billId=6;
			sixthBill.planType="quarterly Plan";
			sixthBill.billAmountWithTax=459.59;
			sixthBill.isTaxIncluded=true;
			sixthBill.billIssueDate="02/06/2025";
			sixthBill.billDueDate="07/06/2025";
			sixthBill.isBillPaid=false;
			sixthBill.isOverdue=true;
			sixthBill.paymentMethod=null;
			System.out.println();
			System.out.println("Sixth Bill Details :");
				System.out.println("The sixth bill id is : "+sixthBill.billId);
				System.out.println("The plan type of sixth bill is : "+sixthBill.planType);
				System.out.println("The sixth bill amount with tax is : "+sixthBill.billAmountWithTax);
				System.out.println("Is Tax Included? "+sixthBill.isTaxIncluded);
				System.out.println("Sixth Bill Issue Date is : "+sixthBill.billIssueDate);
				System.out.println("Sixth Bill Due Date is : "+sixthBill.billDueDate);
				System.out.println("Is Bill Paid? "+sixthBill.isBillPaid);
				System.out.println("Is Bill OverDue? "+sixthBill.isOverdue);
				System.out.println("Payment method of sixth bill is : "+sixthBill.paymentMethod);
				
			Bill seventhBill= new Bill();
			seventhBill.billId=7;
			seventhBill.planType="Half Yearly Plan";
			seventhBill.billAmountWithTax=699.99;
			seventhBill.isTaxIncluded=true;
			seventhBill.billIssueDate="05/01/2025";
			seventhBill.billDueDate="10/01/2025";
			seventhBill.isBillPaid=true;
			seventhBill.isOverdue=false;
			seventhBill.paymentMethod="Credit Card";
			System.out.println();
			System.out.println("Seventh Bill Details :");
				System.out.println("The seventh bill id is : "+seventhBill.billId);
				System.out.println("The plan type of seventh bill is : "+seventhBill.planType);
				System.out.println("The seventh bill amount with tax is : "+seventhBill.billAmountWithTax);
				System.out.println("Is Tax Included? "+seventhBill.isTaxIncluded);
				System.out.println("Seventh Bill Issue Date is : "+seventhBill.billIssueDate);
				System.out.println("Seventh Bill Due Date is : "+seventhBill.billDueDate);
				System.out.println("Is Bill Paid? "+seventhBill.isBillPaid);
				System.out.println("Is Bill OverDue? "+seventhBill.isOverdue);
				System.out.println("Payment method of seventh bill is : "+seventhBill.paymentMethod);
				
			Bill eighthBill= new Bill();
			eighthBill.billId=8;
			eighthBill.planType="Yearly Plan";
			eighthBill.billAmountWithTax=1499.99;
			eighthBill.isTaxIncluded=true;
			eighthBill.billIssueDate="05/07/2025";
			eighthBill.billDueDate="12/07/2025";
			eighthBill.isBillPaid=true;
			eighthBill.isOverdue=false;
			eighthBill.paymentMethod="Debit Card";
			System.out.println();
			System.out.println("Eighth Bill Details :");
				System.out.println("The eighth bill id is : "+eighthBill.billId);
				System.out.println("The plan type of eighth bill is : "+eighthBill.planType);
				System.out.println("The eighth bill amount with tax is : "+eighthBill.billAmountWithTax);
				System.out.println("Is Tax Included? "+eighthBill.isTaxIncluded);
				System.out.println("Eighth Bill Issue Date is : "+eighthBill.billIssueDate);
				System.out.println("Eighth Bill Due Date is : "+eighthBill.billDueDate);
				System.out.println("Is Bill Paid? "+eighthBill.isBillPaid);
				System.out.println("Is Bill OverDue? "+eighthBill.isOverdue);
				System.out.println("Payment method of eighth bill is : "+eighthBill.paymentMethod);
				
			Bill ninthBill= new Bill();
			ninthBill.billId=9;
			ninthBill.planType="Monthly Plan";
			ninthBill.billAmountWithTax=249.00;
			ninthBill.isTaxIncluded=true;
			ninthBill.billIssueDate="28/07/2025";
			ninthBill.billDueDate="03/08/2025";
			ninthBill.isBillPaid=false;
			ninthBill.isOverdue=true;
			ninthBill.paymentMethod=null;
			System.out.println();
			System.out.println("Ninth Bill Details :");
				System.out.println("The ninth bill id is : "+ninthBill.billId);
				System.out.println("The plan type of ninth bill is : "+ninthBill.planType);
				System.out.println("The ninth bill amount with tax is : "+ninthBill.billAmountWithTax);
				System.out.println("Is Tax Included? "+ninthBill.isTaxIncluded);
				System.out.println("Ninth Bill Issue Date is : "+ninthBill.billIssueDate);
				System.out.println("Ninth Bill Due Date is : "+ninthBill.billDueDate);
				System.out.println("Is Bill Paid? "+ninthBill.isBillPaid);
				System.out.println("Is Bill OverDue? "+ninthBill.isOverdue);
				System.out.println("Payment method of ninth bill is : "+ninthBill.paymentMethod);
			
			Bill tenthBill= new Bill();
			tenthBill.billId=10;
			tenthBill.planType="Half Yearly Plan";
			tenthBill.billAmountWithTax=649.00;
			tenthBill.isTaxIncluded=true;
			tenthBill.billIssueDate="18/08/2024";
			tenthBill.billDueDate="23/08/2024";
			tenthBill.isBillPaid=true;
			tenthBill.isOverdue=false;
			tenthBill.paymentMethod="Debit Card";
			System.out.println();
			System.out.println("Tenth Bill Details :");
				System.out.println("The tenth bill id is : "+tenthBill.billId);
				System.out.println("The plan type of tenth bill is : "+tenthBill.planType);
				System.out.println("The tenth bill amount with tax is : "+tenthBill.billAmountWithTax);
				System.out.println("Is Tax Included? "+tenthBill.isTaxIncluded);
				System.out.println("Tenth Bill Issue Date is : "+tenthBill.billIssueDate);
				System.out.println("Tenth Bill Due Date is : "+tenthBill.billDueDate);
				System.out.println("Is Bill Paid? "+tenthBill.isBillPaid);
				System.out.println("Is Bill OverDue? "+tenthBill.isOverdue);
				System.out.println("Payment method of tenth bill is : "+tenthBill.paymentMethod);
				
			Bill eleventhBill= new Bill();
			eleventhBill.billId=11;
			eleventhBill.planType="Quarterly Plan";
			eleventhBill.billAmountWithTax=349.00;
			eleventhBill.isTaxIncluded=true;
			eleventhBill.billIssueDate="11/11/2024";
			eleventhBill.billDueDate="17/11/2024";
			eleventhBill.isBillPaid=true;
			eleventhBill.isOverdue=false;
			eleventhBill.paymentMethod="Credit Card";
			System.out.println();
			System.out.println("Eleventh Bill Details :");
				System.out.println("The eleventh bill id is : "+eleventhBill.billId);
				System.out.println("The plan type of eleventh bill is : "+eleventhBill.planType);
				System.out.println("The eleventh bill amount with tax is : "+eleventhBill.billAmountWithTax);
				System.out.println("Is Tax Included? "+eleventhBill.isTaxIncluded);
				System.out.println("Eleventh Bill Issue Date is : "+eleventhBill.billIssueDate);
				System.out.println("Eleventh Bill Due Date is : "+eleventhBill.billDueDate);
				System.out.println("Is Bill Paid? "+eleventhBill.isBillPaid);
				System.out.println("Is Bill OverDue? "+eleventhBill.isOverdue);
				System.out.println("Payment method of eleventh bill is : "+eleventhBill.paymentMethod);
				
			Bill twelfthBill= new Bill();
			twelfthBill.billId=12;
			twelfthBill.planType="Yearly Plan";
			twelfthBill.billAmountWithTax=1599.90;
			twelfthBill.isTaxIncluded=true;
			twelfthBill.billIssueDate="01/05/2024";
			twelfthBill.billDueDate="07/05/2024";
			twelfthBill.isBillPaid=true;
			twelfthBill.isOverdue=false;
			twelfthBill.paymentMethod="UPI transaction";
			System.out.println();
			System.out.println("Twelfth Bill Details :");
				System.out.println("The twelfth bill id is : "+twelfthBill.billId);
				System.out.println("The plan type of twelfth bill is : "+twelfthBill.planType);
				System.out.println("The twelfth bill amount with tax is : "+twelfthBill.billAmountWithTax);
				System.out.println("Is Tax Included? "+twelfthBill.isTaxIncluded);
				System.out.println("Twelfth Bill Issue Date is : "+twelfthBill.billIssueDate);
				System.out.println("Twelfth Bill Due Date is : "+twelfthBill.billDueDate);
				System.out.println("Is Bill Paid? "+twelfthBill.isBillPaid);
				System.out.println("Is Bill OverDue? "+twelfthBill.isOverdue);
				System.out.println("Payment method of twelfth bill is : "+twelfthBill.paymentMethod);
				
			Bill thirteenthBill= new Bill();
			thirteenthBill.billId=13;
			thirteenthBill.planType="Monthly Plan";
			thirteenthBill.billAmountWithTax=399.90;
			thirteenthBill.isTaxIncluded=true;
			thirteenthBill.billIssueDate="09/06/2024";
			thirteenthBill.billDueDate="14/06/2024";
			thirteenthBill.isBillPaid=false;
			thirteenthBill.isOverdue=true;
			thirteenthBill.paymentMethod=null;
			System.out.println();
			System.out.println("Thirteenth Bill Details :");
				System.out.println("The thirteenth bill id is : "+thirteenthBill.billId);
				System.out.println("The plan type of thirteenth bill is : "+thirteenthBill.planType);
				System.out.println("The thirteenth bill amount with tax is : "+thirteenthBill.billAmountWithTax);
				System.out.println("Is Tax Included? "+thirteenthBill.isTaxIncluded);
				System.out.println("Thirteenth Bill Issue Date is : "+thirteenthBill.billIssueDate);
				System.out.println("Thirteenth Bill Due Date is : "+thirteenthBill.billDueDate);
				System.out.println("Is Bill Paid? "+thirteenthBill.isBillPaid);
				System.out.println("Is Bill OverDue? "+thirteenthBill.isOverdue);
				System.out.println("Payment method of thirteenth bill is : "+thirteenthBill.paymentMethod);
				
			Bill fourteenthBill= new Bill();
			fourteenthBill.billId=14;
			fourteenthBill.planType="Quarterly Plan";
			fourteenthBill.billAmountWithTax=799.90;
			fourteenthBill.isTaxIncluded=true;
			fourteenthBill.billIssueDate="12/12/2024";
			fourteenthBill.billDueDate="18/12/2024";
			fourteenthBill.isBillPaid=true;
			fourteenthBill.isOverdue=false;
			fourteenthBill.paymentMethod="UPI Id";
			System.out.println();
			System.out.println("Fourteenth Bill Details :");
				System.out.println("The fourteenth bill id is : "+fourteenthBill.billId);
				System.out.println("The plan type of fourteenth bill is : "+fourteenthBill.planType);
				System.out.println("The fourteenth bill amount with tax is : "+fourteenthBill.billAmountWithTax);
				System.out.println("Is Tax Included? "+fourteenthBill.isTaxIncluded);
				System.out.println("Fourteenth Bill Issue Date is : "+fourteenthBill.billIssueDate);
				System.out.println("Fourteenth Bill Due Date is : "+fourteenthBill.billDueDate);
				System.out.println("Is Bill Paid? "+fourteenthBill.isBillPaid);
				System.out.println("Is Bill OverDue? "+fourteenthBill.isOverdue);
				System.out.println("Payment method of fourteenth bill is : "+fourteenthBill.paymentMethod);
				
			Bill fifteenthBill= new Bill();
			fifteenthBill.billId=15;
			fifteenthBill.planType="Half Yearly Plan";
			fifteenthBill.billAmountWithTax=999.88;
			fifteenthBill.isTaxIncluded=true;
			fifteenthBill.billIssueDate="08/05/2025";
			fifteenthBill.billDueDate="13/05/2025";
			fifteenthBill.isBillPaid=false;
			fifteenthBill.isOverdue=true;
			fifteenthBill.paymentMethod=null;
			System.out.println();
			System.out.println("Fifteenth Bill Details :");
				System.out.println("The fifteenth bill id is : "+fifteenthBill.billId);
				System.out.println("The plan type of fifteenth bill is : "+fifteenthBill.planType);
				System.out.println("The fifteenth bill amount with tax is : "+fifteenthBill.billAmountWithTax);
				System.out.println("Is Tax Included? "+fifteenthBill.isTaxIncluded);
				System.out.println("Fifteenth Bill Issue Date is : "+fifteenthBill.billIssueDate);
				System.out.println("Fifteenth Bill Due Date is : "+fifteenthBill.billDueDate);
				System.out.println("Is Bill Paid? "+fifteenthBill.isBillPaid);
				System.out.println("Is Bill OverDue? "+fifteenthBill.isOverdue);
				System.out.println("Payment method of fifteenth bill is : "+fifteenthBill.paymentMethod);
			
			Bill sixteenthBill= new Bill();
			sixteenthBill.billId=16;
			sixteenthBill.planType="Monthly Plan";
			sixteenthBill.billAmountWithTax=109.88;
			sixteenthBill.isTaxIncluded=true;
			sixteenthBill.billIssueDate="01/06/2025";
			sixteenthBill.billDueDate="10/06/2025";
			sixteenthBill.isBillPaid=true;
			sixteenthBill.isOverdue=false;
			sixteenthBill.paymentMethod="UPI transaction";
			System.out.println();
			System.out.println("Sixteenth Bill Details :");
				System.out.println("The sixteenth bill id is : "+sixteenthBill.billId);
				System.out.println("The plan type of sixteenth bill is : "+sixteenthBill.planType);
				System.out.println("The sixteenth bill amount with tax is : "+sixteenthBill.billAmountWithTax);
				System.out.println("Is Tax Included? "+sixteenthBill.isTaxIncluded);
				System.out.println("Sixteenth Bill Issue Date is : "+sixteenthBill.billIssueDate);
				System.out.println("Sixteenth Bill Due Date is : "+sixteenthBill.billDueDate);
				System.out.println("Is Bill Paid? "+sixteenthBill.isBillPaid);
				System.out.println("Is Bill OverDue? "+sixteenthBill.isOverdue);
				System.out.println("Payment method of sixteenth bill is : "+sixteenthBill.paymentMethod);
			
			Bill seventeenthBill= new Bill();
			seventeenthBill.billId=17;
			seventeenthBill.planType="Quarterly Plan";
			seventeenthBill.billAmountWithTax=439.78;
			seventeenthBill.isTaxIncluded=true;
			seventeenthBill.billIssueDate="15/10/2025";
			seventeenthBill.billDueDate="20/10/2025";
			seventeenthBill.isBillPaid=true;
			seventeenthBill.isOverdue=false;
			seventeenthBill.paymentMethod="Credit Card";
			System.out.println();
			System.out.println("Seventeenth Bill Details :");
				System.out.println("The seventeenth bill id is : "+seventeenthBill.billId);
				System.out.println("The plan type of seventeenth bill is : "+seventeenthBill.planType);
				System.out.println("The seventeenth bill amount with tax is : "+seventeenthBill.billAmountWithTax);
				System.out.println("Is Tax Included? "+seventeenthBill.isTaxIncluded);
				System.out.println("Seventeenth Bill Issue Date is : "+seventeenthBill.billIssueDate);
				System.out.println("Seventeenth Bill Due Date is : "+seventeenthBill.billDueDate);
				System.out.println("Is Bill Paid? "+seventeenthBill.isBillPaid);
				System.out.println("Is Bill OverDue? "+seventeenthBill.isOverdue);
				System.out.println("Payment method of seventeenth bill is : "+seventeenthBill.paymentMethod);
				
			Bill eighteenthBill= new Bill();
			eighteenthBill.billId=18;
			eighteenthBill.planType="Monthly Plan";
			eighteenthBill.billAmountWithTax=239.50;
			eighteenthBill.isTaxIncluded=true;
			eighteenthBill.billIssueDate="05/08/2024";
			eighteenthBill.billDueDate="10/08/2024";
			eighteenthBill.isBillPaid=true;
			eighteenthBill.isOverdue=false;
			eighteenthBill.paymentMethod="Debit Card";
			System.out.println();
			System.out.println("Eighteenth Bill Details :");
				System.out.println("The eighteenth bill id is : "+eighteenthBill.billId);
				System.out.println("The plan type of eighteenth bill is : "+eighteenthBill.planType);
				System.out.println("The eighteenth bill amount with tax is : "+eighteenthBill.billAmountWithTax);
				System.out.println("Is Tax Included? "+eighteenthBill.isTaxIncluded);
				System.out.println("Eighteenth Bill Issue Date is : "+eighteenthBill.billIssueDate);
				System.out.println("Eighteenth Bill Due Date is : "+eighteenthBill.billDueDate);
				System.out.println("Is Bill Paid? "+eighteenthBill.isBillPaid);
				System.out.println("Is Bill OverDue? "+eighteenthBill.isOverdue);
				System.out.println("Payment method of eighteenth bill is : "+eighteenthBill.paymentMethod);
				
			Bill ninteenthBill= new Bill();
			ninteenthBill.billId=19;
			ninteenthBill.planType="Quarterly Plan";
			ninteenthBill.billAmountWithTax=679.70;
			ninteenthBill.isTaxIncluded=true;
			ninteenthBill.billIssueDate="01/09/2024";
			ninteenthBill.billDueDate="07/09/2024";
			ninteenthBill.isBillPaid=true;
			ninteenthBill.isOverdue=false;
			ninteenthBill.paymentMethod="UPI transaction";
			System.out.println();
			System.out.println("Ninteenth Bill Details :");
				System.out.println("The ninteenth bill id is : "+ninteenthBill.billId);
				System.out.println("The plan type of ninteenth bill is : "+ninteenthBill.planType);
				System.out.println("The ninteenth bill amount with tax is : "+ninteenthBill.billAmountWithTax);
				System.out.println("Is Tax Included? "+ninteenthBill.isTaxIncluded);
				System.out.println("Ninteenth Bill Issue Date is : "+ninteenthBill.billIssueDate);
				System.out.println("Ninteenth Bill Due Date is : "+ninteenthBill.billDueDate);
				System.out.println("Is Bill Paid? "+ninteenthBill.isBillPaid);
				System.out.println("Is Bill OverDue? "+ninteenthBill.isOverdue);
				System.out.println("Payment method of ninteenth bill is : "+ninteenthBill.paymentMethod);
				
			Bill twentythBill= new Bill();
			twentythBill.billId=20;
			twentythBill.planType="Yearly Plan";
			twentythBill.billAmountWithTax=1879.70;
			twentythBill.isTaxIncluded=true;
			twentythBill.billIssueDate="04/04/2025";
			twentythBill.billDueDate="10/04/2025";
			twentythBill.isBillPaid=true;
			twentythBill.isOverdue=false;
			twentythBill.paymentMethod="Debit Card";
			System.out.println();
			System.out.println("Twentyth Bill Details :");
				System.out.println("The twentyth bill id is : "+twentythBill.billId);
				System.out.println("The plan type of twentyth bill is : "+twentythBill.planType);
				System.out.println("The twentyth bill amount with tax is : "+twentythBill.billAmountWithTax);
				System.out.println("Is Tax Included? "+twentythBill.isTaxIncluded);
				System.out.println("Twentyth Bill Issue Date is : "+twentythBill.billIssueDate);
				System.out.println("Twentyth Bill Due Date is : "+twentythBill.billDueDate);
				System.out.println("Is Bill Paid? "+twentythBill.isBillPaid);
				System.out.println("Is Bill OverDue? "+twentythBill.isOverdue);
				System.out.println("Payment method of twentyth bill is : "+twentythBill.paymentMethod);
		System.out.println("main ended");
	}
}