class BladeRunner{
	
	public static void main(String blade[]){
		
		System.out.println("main started");
			Blade bladeOne = new Blade();
			bladeOne.bladeId=1;
			bladeOne.bladeWeight=150.00;
			bladeOne.bladeThickness=2.5;
			bladeOne.bladeMaterial="Stainless Steel";
			bladeOne.bladeLength=8.5;
			bladeOne.bladeType="Chef's Knife";
			bladeOne.sharpnessLevel="Ultra Sharp";
				System.out.println();
				System.out.println("Blade One details : ");
				System.out.println("id of blade is : "+bladeOne.bladeId);
				System.out.println("weight of the blade is : "+bladeOne.bladeWeight+" g");
				System.out.println("thickness of the blade is : "+bladeOne.bladeThickness+" mm");
				System.out.println("material of the blade is : "+bladeOne.bladeMaterial);
				System.out.println("length of the blade is : "+bladeOne.bladeLength+" inches");
				System.out.println("type of the blade is : "+bladeOne.bladeType);
				System.out.println("sharpness level of blade is : "+bladeOne.sharpnessLevel);
			
			Blade bladeTwo = new Blade();
			bladeTwo.bladeId=2;
			bladeTwo.bladeWeight=100.00;
			bladeTwo.bladeThickness=1.5;
			bladeTwo.bladeMaterial="Stainless Steel";
			bladeTwo.bladeLength=6.5;
			bladeTwo.bladeType="Razor Blade";
			bladeTwo.sharpnessLevel="Moderate";
				System.out.println();
				System.out.println("Blade two details : ");
				System.out.println("id of blade is : "+bladeTwo.bladeId);
				System.out.println("weight of the blade is : "+bladeTwo.bladeWeight+" g");
				System.out.println("thickness of the blade is : "+bladeTwo.bladeThickness+" mm");
				System.out.println("material of the blade is : "+bladeTwo.bladeMaterial);
				System.out.println("length of the blade is : "+bladeTwo.bladeLength+" inches");
				System.out.println("type of the blade is : "+bladeTwo.bladeType);
				System.out.println("sharpness level of blade is : "+bladeTwo.sharpnessLevel);
				
			Blade bladeThree = new Blade();
			bladeThree.bladeId=3;
			bladeThree.bladeWeight=200.00;
			bladeThree.bladeThickness=1.75;
			bladeThree.bladeMaterial="Stainless Steel";
			bladeThree.bladeLength=4.5;
			bladeThree.bladeType="Razor Blade";
			bladeThree.sharpnessLevel="Less sharp";
				System.out.println();
				System.out.println("Blade threee details : ");
				System.out.println("id of blade is : "+bladeThree.bladeId);
				System.out.println("weight of the blade is : "+bladeThree.bladeWeight+" g");
				System.out.println("thickness of the blade is : "+bladeThree.bladeThickness+" mm");
				System.out.println("material of the blade is : "+bladeThree.bladeMaterial);
				System.out.println("length of the blade is : "+bladeThree.bladeLength+" inches");
				System.out.println("type of the blade is : "+bladeThree.bladeType);
				System.out.println("sharpness level of blade is : "+bladeThree.sharpnessLevel);
				
			Blade bladeFour = new Blade();
			bladeFour.bladeId=4;
			bladeFour.bladeWeight=180.00;
			bladeFour.bladeThickness=0.75;
			bladeFour.bladeMaterial="Stainless Steel";
			bladeFour.bladeLength=7.5;
			bladeFour.bladeType="Chef's Knife";
			bladeFour.sharpnessLevel="Moderate";
				System.out.println();
				System.out.println("Blade four details : ");
				System.out.println("id of blade is : "+bladeFour.bladeId);
				System.out.println("weight of the blade is : "+bladeFour.bladeWeight+" g");
				System.out.println("thickness of the blade is : "+bladeFour.bladeThickness+" mm");
				System.out.println("material of the blade is : "+bladeFour.bladeMaterial);
				System.out.println("length of the blade is : "+bladeFour.bladeLength+" inches");
				System.out.println("type of the blade is : "+bladeFour.bladeType);
				System.out.println("sharpness level of blade is : "+bladeFour.sharpnessLevel);
				
			Blade bladeFive = new Blade();
			bladeFive.bladeId=5;
			bladeFive.bladeWeight=250.00;
			bladeFive.bladeThickness=2.75;
			bladeFive.bladeMaterial="Stainless Steel";
			bladeFive.bladeLength=5.0;
			bladeFive.bladeType="Razor Blade";
			bladeFive.sharpnessLevel="Ultra Sharp";
				System.out.println();
				System.out.println("Blade five details : ");
				System.out.println("id of blade is : "+bladeFive.bladeId);
				System.out.println("weight of the blade is : "+bladeFive.bladeWeight+" g");
				System.out.println("thickness of the blade is : "+bladeFive.bladeThickness+" mm");
				System.out.println("material of the blade is : "+bladeFive.bladeMaterial);
				System.out.println("length of the blade is : "+bladeFive.bladeLength+" inches");
				System.out.println("type of the blade is : "+bladeFive.bladeType);
				System.out.println("sharpness level of blade is : "+bladeFive.sharpnessLevel);
				
			Blade bladeSix = new Blade();
			bladeSix.bladeId=6;
			bladeSix.bladeWeight=120.00;
			bladeSix.bladeThickness=2.0;
			bladeSix.bladeMaterial="Stainless Steel";
			bladeSix.bladeLength=6.3;
			bladeSix.bladeType="Chef's Knife";
			bladeSix.sharpnessLevel="less Sharp";
				System.out.println();
				System.out.println("Blade six details : ");
				System.out.println("id of blade is : "+bladeSix.bladeId);
				System.out.println("weight of the blade is : "+bladeSix.bladeWeight+" g");
				System.out.println("thickness of the blade is : "+bladeSix.bladeThickness+" mm");
				System.out.println("material of the blade is : "+bladeSix.bladeMaterial);
				System.out.println("length of the blade is : "+bladeSix.bladeLength+" inches");
				System.out.println("type of the blade is : "+bladeSix.bladeType);
				System.out.println("sharpness level of blade is : "+bladeSix.sharpnessLevel);
				
			Blade bladeSeven = new Blade();
			bladeSeven.bladeId=7;
			bladeSeven.bladeWeight=150.00;
			bladeSeven.bladeThickness=1.0;
			bladeSeven.bladeMaterial="Stainless Steel";
			bladeSeven.bladeLength=8.7;
			bladeSeven.bladeType="Razor Blade";
			bladeSeven.sharpnessLevel="Moderate";
				System.out.println();
				System.out.println("Blade seven details : ");
				System.out.println("id of blade is : "+bladeSeven.bladeId);
				System.out.println("weight of the blade is : "+bladeSeven.bladeWeight+" g");
				System.out.println("thickness of the blade is : "+bladeSeven.bladeThickness+" mm");
				System.out.println("material of the blade is : "+bladeSeven.bladeMaterial);
				System.out.println("length of the blade is : "+bladeSeven.bladeLength+" inches");
				System.out.println("type of the blade is : "+bladeSeven.bladeType);
				System.out.println("sharpness level of blade is : "+bladeSeven.sharpnessLevel);
				
			Blade bladeEight = new Blade();
			bladeEight.bladeId=8;
			bladeEight.bladeWeight=175.00;
			bladeEight.bladeThickness=1.2;
			bladeEight.bladeMaterial="Stainless Steel";
			bladeEight.bladeLength=7.5;
			bladeEight.bladeType="Razor Blade";
			bladeEight.sharpnessLevel="Ultra Sharp";
				System.out.println();
				System.out.println("Blade eight details : ");
				System.out.println("id of blade is : "+bladeEight.bladeId);
				System.out.println("weight of the blade is : "+bladeEight.bladeWeight+" g");
				System.out.println("thickness of the blade is : "+bladeEight.bladeThickness+" mm");
				System.out.println("material of the blade is : "+bladeEight.bladeMaterial);
				System.out.println("length of the blade is : "+bladeEight.bladeLength+" inches");
				System.out.println("type of the blade is : "+bladeEight.bladeType);
				System.out.println("sharpness level of blade is : "+bladeEight.sharpnessLevel);
				
			Blade bladeNine = new Blade();
			bladeNine.bladeId=9;
			bladeNine.bladeWeight=145.00;
			bladeNine.bladeThickness=2.3;
			bladeNine.bladeMaterial="Stainless Steel";
			bladeNine.bladeLength=5.5;
			bladeNine.bladeType="Chef's Knife";
			bladeNine.sharpnessLevel="Moderate";
				System.out.println();
				System.out.println("Blade nine details : ");
				System.out.println("id of blade is : "+bladeNine.bladeId);
				System.out.println("weight of the blade is : "+bladeNine.bladeWeight+" g");
				System.out.println("thickness of the blade is : "+bladeNine.bladeThickness+" mm");
				System.out.println("material of the blade is : "+bladeNine.bladeMaterial);
				System.out.println("length of the blade is : "+bladeNine.bladeLength+" inches");
				System.out.println("type of the blade is : "+bladeNine.bladeType);
				System.out.println("sharpness level of blade is : "+bladeNine.sharpnessLevel);
				
			Blade bladeTen = new Blade();
			bladeTen.bladeId=10;
			bladeTen.bladeWeight=245.00;
			bladeTen.bladeThickness=1.3;
			bladeTen.bladeMaterial="Stainless Steel";
			bladeTen.bladeLength=9.5;
			bladeTen.bladeType="Razor Blade";
			bladeTen.sharpnessLevel="Moderate";
				System.out.println();
				System.out.println("Blade ten details : ");
				System.out.println("id of blade is : "+bladeTen.bladeId);
				System.out.println("weight of the blade is : "+bladeTen.bladeWeight+" g");
				System.out.println("thickness of the blade is : "+bladeTen.bladeThickness+" mm");
				System.out.println("material of the blade is : "+bladeTen.bladeMaterial);
				System.out.println("length of the blade is : "+bladeTen.bladeLength+" inches");
				System.out.println("type of the blade is : "+bladeTen.bladeType);
				System.out.println("sharpness level of blade is : "+bladeTen.sharpnessLevel);
				
			Blade bladeEleven = new Blade();
			bladeEleven.bladeId=11;
			bladeEleven.bladeWeight=195.00;
			bladeEleven.bladeThickness=1.9;
			bladeEleven.bladeMaterial="Stainless Steel";
			bladeEleven.bladeLength=6.7;
			bladeEleven.bladeType="Razor Blade";
			bladeEleven.sharpnessLevel="Ultra Sharp";
				System.out.println();
				System.out.println("Blade eleven details : ");
				System.out.println("id of blade is : "+bladeEleven.bladeId);
				System.out.println("weight of the blade is : "+bladeEleven.bladeWeight+" g");
				System.out.println("thickness of the blade is : "+bladeEleven.bladeThickness+" mm");
				System.out.println("material of the blade is : "+bladeEleven.bladeMaterial);
				System.out.println("length of the blade is : "+bladeEleven.bladeLength+" inches");
				System.out.println("type of the blade is : "+bladeEleven.bladeType);
				System.out.println("sharpness level of blade is : "+bladeEleven.sharpnessLevel);
				
			Blade bladeTwelve = new Blade();
			bladeTwelve.bladeId=12;
			bladeTwelve.bladeWeight=255.00;
			bladeTwelve.bladeThickness=0.9;
			bladeTwelve.bladeMaterial="Stainless Steel";
			bladeTwelve.bladeLength=3.7;
			bladeTwelve.bladeType="Chef's Knife";
			bladeTwelve.sharpnessLevel="Less Sharp";
				System.out.println();
				System.out.println("Blade twelve details : ");
				System.out.println("id of blade is : "+bladeTwelve.bladeId);
				System.out.println("weight of the blade is : "+bladeTwelve.bladeWeight+" g");
				System.out.println("thickness of the blade is : "+bladeTwelve.bladeThickness+" mm");
				System.out.println("material of the blade is : "+bladeTwelve.bladeMaterial);
				System.out.println("length of the blade is : "+bladeTwelve.bladeLength+" inches");
				System.out.println("type of the blade is : "+bladeTwelve.bladeType);
				System.out.println("sharpness level of blade is : "+bladeTwelve.sharpnessLevel);
				
			Blade bladeThirteen = new Blade();
			bladeThirteen.bladeId=13;
			bladeThirteen.bladeWeight=205.00;
			bladeThirteen.bladeThickness=1.9;
			bladeThirteen.bladeMaterial="Stainless Steel";
			bladeThirteen.bladeLength=5.7;
			bladeThirteen.bladeType="Chef's Knife";
			bladeThirteen.sharpnessLevel="Moderate";
				System.out.println();
				System.out.println("Blade thirteen details : ");
				System.out.println("id of blade is : "+bladeThirteen.bladeId);
				System.out.println("weight of the blade is : "+bladeThirteen.bladeWeight+" g");
				System.out.println("thickness of the blade is : "+bladeThirteen.bladeThickness+" mm");
				System.out.println("material of the blade is : "+bladeThirteen.bladeMaterial);
				System.out.println("length of the blade is : "+bladeThirteen.bladeLength+" inches");
				System.out.println("type of the blade is : "+bladeThirteen.bladeType);
				System.out.println("sharpness level of blade is : "+bladeThirteen.sharpnessLevel);
				
			Blade bladeFourteen = new Blade();
			bladeFourteen.bladeId=14;
			bladeFourteen.bladeWeight=105.00;
			bladeFourteen.bladeThickness=1.7;
			bladeFourteen.bladeMaterial="Stainless Steel";
			bladeFourteen.bladeLength=7.7;
			bladeFourteen.bladeType="Razor Blade";
			bladeFourteen.sharpnessLevel="Moderate";
				System.out.println();
				System.out.println("Blade fourteen details : ");
				System.out.println("id of blade is : "+bladeFourteen.bladeId);
				System.out.println("weight of the blade is : "+bladeFourteen.bladeWeight+" g");
				System.out.println("thickness of the blade is : "+bladeFourteen.bladeThickness+" mm");
				System.out.println("material of the blade is : "+bladeFourteen.bladeMaterial);
				System.out.println("length of the blade is : "+bladeFourteen.bladeLength+" inches");
				System.out.println("type of the blade is : "+bladeFourteen.bladeType);
				System.out.println("sharpness level of blade is : "+bladeFourteen.sharpnessLevel);
				
			Blade bladeFifteen = new Blade();
			bladeFifteen.bladeId=15;
			bladeFifteen.bladeWeight=225.00;
			bladeFifteen.bladeThickness=2.7;
			bladeFifteen.bladeMaterial="Stainless Steel";
			bladeFifteen.bladeLength=7.1;
			bladeFifteen.bladeType="Razor Blade";
			bladeFifteen.sharpnessLevel="Ultra Sharp";
				System.out.println();
				System.out.println("Blade fifteen details : ");
				System.out.println("id of blade is : "+bladeFifteen.bladeId);
				System.out.println("weight of the blade is : "+bladeFifteen.bladeWeight+" g");
				System.out.println("thickness of the blade is : "+bladeFifteen.bladeThickness+" mm");
				System.out.println("material of the blade is : "+bladeFifteen.bladeMaterial);
				System.out.println("length of the blade is : "+bladeFifteen.bladeLength+" inches");
				System.out.println("type of the blade is : "+bladeFifteen.bladeType);
				System.out.println("sharpness level of blade is : "+bladeFifteen.sharpnessLevel);
				
			Blade bladeSixteen = new Blade();
			bladeSixteen.bladeId=16;
			bladeSixteen.bladeWeight=190.00;
			bladeSixteen.bladeThickness=2.5;
			bladeSixteen.bladeMaterial="Stainless Steel";
			bladeSixteen.bladeLength=4.1;
			bladeSixteen.bladeType="Chef's Knife";
			bladeSixteen.sharpnessLevel="Ultra Sharp";
				System.out.println();
				System.out.println("Blade sixteen details : ");
				System.out.println("id of blade is : "+bladeSixteen.bladeId);
				System.out.println("weight of the blade is : "+bladeSixteen.bladeWeight+" g");
				System.out.println("thickness of the blade is : "+bladeSixteen.bladeThickness+" mm");
				System.out.println("material of the blade is : "+bladeSixteen.bladeMaterial);
				System.out.println("length of the blade is : "+bladeSixteen.bladeLength+" inches");
				System.out.println("type of the blade is : "+bladeSixteen.bladeType);
				System.out.println("sharpness level of blade is : "+bladeSixteen.sharpnessLevel);
			
			Blade bladeSeventeen = new Blade();
			bladeSeventeen.bladeId=17;
			bladeSeventeen.bladeWeight=140.00;
			bladeSeventeen.bladeThickness=1.5;
			bladeSeventeen.bladeMaterial="Stainless Steel";
			bladeSeventeen.bladeLength=4.5;
			bladeSeventeen.bladeType="Chef's Knife";
			bladeSeventeen.sharpnessLevel="Moderate";
				System.out.println();
				System.out.println("Blade seventeen details : ");
				System.out.println("id of blade is : "+bladeSeventeen.bladeId);
				System.out.println("weight of the blade is : "+bladeSeventeen.bladeWeight+" g");
				System.out.println("thickness of the blade is : "+bladeSeventeen.bladeThickness+" mm");
				System.out.println("material of the blade is : "+bladeSeventeen.bladeMaterial);
				System.out.println("length of the blade is : "+bladeSeventeen.bladeLength+" inches");
				System.out.println("type of the blade is : "+bladeSeventeen.bladeType);
				System.out.println("sharpness level of blade is : "+bladeSeventeen.sharpnessLevel);
				
			Blade bladeEighteen = new Blade();
			bladeEighteen.bladeId=18;
			bladeEighteen.bladeWeight=210.00;
			bladeEighteen.bladeThickness=0.5;
			bladeEighteen.bladeMaterial="Stainless Steel";
			bladeEighteen.bladeLength=6.5;
			bladeEighteen.bladeType="Chef's Knife";
			bladeEighteen.sharpnessLevel="Less Sharp";
				System.out.println();
				System.out.println("Blade eighteen details : ");
				System.out.println("id of blade is : "+bladeEighteen.bladeId);
				System.out.println("weight of the blade is : "+bladeEighteen.bladeWeight+" g");
				System.out.println("thickness of the blade is : "+bladeEighteen.bladeThickness+" mm");
				System.out.println("material of the blade is : "+bladeEighteen.bladeMaterial);
				System.out.println("length of the blade is : "+bladeEighteen.bladeLength+" inches");
				System.out.println("type of the blade is : "+bladeEighteen.bladeType);
				System.out.println("sharpness level of blade is : "+bladeEighteen.sharpnessLevel);
				
			Blade bladeNineteen = new Blade();
			bladeNineteen.bladeId=19;
			bladeNineteen.bladeWeight=110.00;
			bladeNineteen.bladeThickness=1.5;
			bladeNineteen.bladeMaterial="Stainless Steel";
			bladeNineteen.bladeLength=6.0;
			bladeNineteen.bladeType="Razor Blade";
			bladeNineteen.sharpnessLevel="Moderate";
				System.out.println();
				System.out.println("Blade nineteen details : ");
				System.out.println("id of blade is : "+bladeNineteen.bladeId);
				System.out.println("weight of the blade is : "+bladeNineteen.bladeWeight+" g");
				System.out.println("thickness of the blade is : "+bladeNineteen.bladeThickness+" mm");
				System.out.println("material of the blade is : "+bladeNineteen.bladeMaterial);
				System.out.println("length of the blade is : "+bladeNineteen.bladeLength+" inches");
				System.out.println("type of the blade is : "+bladeNineteen.bladeType);
				System.out.println("sharpness level of blade is : "+bladeNineteen.sharpnessLevel);
				
			Blade bladeTwenty = new Blade();
			bladeTwenty.bladeId=20;
			bladeTwenty.bladeWeight=130.00;
			bladeTwenty.bladeThickness=2.1;
			bladeTwenty.bladeMaterial="Stainless Steel";
			bladeTwenty.bladeLength=8.4;
			bladeTwenty.bladeType="Razor Blade";
			bladeTwenty.sharpnessLevel="Ultra Sharp";
				System.out.println();
				System.out.println("Blade twenty details : ");
				System.out.println("id of blade is : "+bladeTwenty.bladeId);
				System.out.println("weight of the blade is : "+bladeTwenty.bladeWeight+" g");
				System.out.println("thickness of the blade is : "+bladeTwenty.bladeThickness+" mm");
				System.out.println("material of the blade is : "+bladeTwenty.bladeMaterial);
				System.out.println("length of the blade is : "+bladeTwenty.bladeLength+" inches");
				System.out.println("type of the blade is : "+bladeTwenty.bladeType);
				System.out.println("sharpness level of blade is : "+bladeTwenty.sharpnessLevel);
				System.out.println();

		System.out.println("main ended");
	}

}