class BlazerRunner{

	public static void main(String balzerRef[]){
		System.out.println("main started");
			Blazer blazerOne 	= new Blazer();
			blazerOne.blazerId	= 1;
			blazerOne.brandName	= "Raymond";
			blazerOne.size		= "M";
			blazerOne.color		= "Black";
			blazerOne.materialType	= "Cotton";
			blazerOne.noOfButtons	= 3;
			blazerOne.fitType	= 	"Slim fit";
				System.out.println();
				System.out.println("Blazer one details : ");
				System.out.println("Id of blazer is : "+blazerOne.blazerId);
				System.out.println("brand name of blazer is : "+blazerOne.brandName);
				System.out.println("size of the blazer is : "+blazerOne.size);
				System.out.println("color of the blazer is : "+blazerOne.color);
				System.out.println("material type of the blazer is : "+blazerOne.materialType);
				System.out.println("no of buttons on blazer are : "+blazerOne.noOfButtons);
				System.out.println("fit type of the blazer is : "+blazerOne.fitType);
			
			Blazer blazerTwo    = new Blazer();
			blazerTwo.blazerId = 2;
			blazerTwo.brandName = "Van Heusen";
			blazerTwo.size		= "L";
			blazerTwo.color		= "Brown";
			blazerTwo.materialType = "wool";
			blazerTwo.noOfButtons  = 2;
			blazerTwo.fitType	   = "Regular fit";
				System.out.println();
				System.out.println("Blazer two details : ");
				System.out.println("Id of blazer is : "+blazerTwo.blazerId);
				System.out.println("brand name of blazer is : "+blazerTwo.brandName);
				System.out.println("size of the blazer is : "+blazerTwo.size);
				System.out.println("color of the blazer is : "+blazerTwo.color);
				System.out.println("material type of the blazer is : "+blazerTwo.materialType);
				System.out.println("no of buttons on blazer are : "+blazerTwo.noOfButtons);
				System.out.println("fit type of the blazer is : "+blazerTwo.fitType);
				
			Blazer blazerThree    = new Blazer();
			blazerThree.blazerId = 3;
			blazerThree.brandName = "Louis Philippe";
			blazerThree.size		= "S";
			blazerThree.color		= "Navy Blue";
			blazerThree.materialType = "Linen";
			blazerThree.noOfButtons  = 3;
			blazerThree.fitType	   = "Slim fit";
				System.out.println();
				System.out.println("Blazer three details : ");
				System.out.println("Id of blazer is : "+blazerThree.blazerId);
				System.out.println("brand name of blazer is : "+blazerThree.brandName);
				System.out.println("size of the blazer is : "+blazerThree.size);
				System.out.println("color of the blazer is : "+blazerThree.color);
				System.out.println("material type of the blazer is : "+blazerThree.materialType);
				System.out.println("no of buttons on blazer are : "+blazerThree.noOfButtons);
				System.out.println("fit type of the blazer is : "+blazerThree.fitType);
				
			Blazer blazerFour    = new Blazer();
			blazerFour.blazerId = 4;
			blazerFour.brandName = "Jack & Jones";
			blazerFour.size		= "XL";
			blazerFour.color		= "White";
			blazerFour.materialType = "Cotton";
			blazerFour.noOfButtons  = 2;
			blazerFour.fitType	   = "Regular fit";
				System.out.println();
				System.out.println("Blazer four details : ");
				System.out.println("Id of blazer is : "+blazerFour.blazerId);
				System.out.println("brand name of blazer is : "+blazerFour.brandName);
				System.out.println("size of the blazer is : "+blazerFour.size);
				System.out.println("color of the blazer is : "+blazerFour.color);
				System.out.println("material type of the blazer is : "+blazerFour.materialType);
				System.out.println("no of buttons on blazer are : "+blazerFour.noOfButtons);
				System.out.println("fit type of the blazer is : "+blazerFour.fitType);
				
			Blazer blazerFive    = new Blazer();
			blazerFive.blazerId = 5;
			blazerFive.brandName = "Blackberry";
			blazerFive.size		= "M";
			blazerFive.color		= "Mearun";
			blazerFive.materialType = "Linen";
			blazerFive.noOfButtons  = 3;
			blazerFive.fitType	   = "Slim fit";
				System.out.println();
				System.out.println("Blazer five details : ");
				System.out.println("Id of blazer is : "+blazerFive.blazerId);
				System.out.println("brand name of blazer is : "+blazerFive.brandName);
				System.out.println("size of the blazer is : "+blazerFive.size);
				System.out.println("color of the blazer is : "+blazerFive.color);
				System.out.println("material type of the blazer is : "+blazerFive.materialType);
				System.out.println("no of buttons on blazer are : "+blazerFive.noOfButtons);
				System.out.println("fit type of the blazer is : "+blazerFive.fitType);
				
			Blazer blazerSix    = new Blazer();
			blazerSix.blazerId = 6;
			blazerSix.brandName = "Raymond";
			blazerSix.size		= "S";
			blazerSix.color		= "Pink";
			blazerSix.materialType = "cotton";
			blazerSix.noOfButtons  = 2;
			blazerSix.fitType	   = "Regular fit";
				System.out.println();
				System.out.println("Blazer six details : ");
				System.out.println("Id of blazer is : "+blazerSix.blazerId);
				System.out.println("brand name of blazer is : "+blazerSix.brandName);
				System.out.println("size of the blazer is : "+blazerSix.size);
				System.out.println("color of the blazer is : "+blazerSix.color);
				System.out.println("material type of the blazer is : "+blazerSix.materialType);
				System.out.println("no of buttons on blazer are : "+blazerSix.noOfButtons);
				System.out.println("fit type of the blazer is : "+blazerSix.fitType);
				
			Blazer blazerSeven    = new Blazer();
			blazerSeven.blazerId = 7;
			blazerSeven.brandName = "Allen Solly";
			blazerSeven.size		= "XS";
			blazerSeven.color		= "Lavender";
			blazerSeven.materialType = "Linen";
			blazerSeven.noOfButtons  = 3;
			blazerSeven.fitType	   = "Slim fit";
				System.out.println();
				System.out.println("Blazer seven details : ");
				System.out.println("Id of blazer is : "+blazerSeven.blazerId);
				System.out.println("brand name of blazer is : "+blazerSeven.brandName);
				System.out.println("size of the blazer is : "+blazerSeven.size);
				System.out.println("color of the blazer is : "+blazerSeven.color);
				System.out.println("material type of the blazer is : "+blazerSeven.materialType);
				System.out.println("no of buttons on blazer are : "+blazerSeven.noOfButtons);
				System.out.println("fit type of the blazer is : "+blazerSeven.fitType);
				
			Blazer blazerEight    = new Blazer();
			blazerEight.blazerId = 8;
			blazerEight.brandName = "Marks & Spencer";
			blazerEight.size		= "XXL";
			blazerEight.color		= "Blue";
			blazerEight.materialType = "wool";
			blazerEight.noOfButtons  = 2;
			blazerEight.fitType	   = "Regular fit";
				System.out.println();
				System.out.println("Blazer eight details : ");
				System.out.println("Id of blazer is : "+blazerEight.blazerId);
				System.out.println("brand name of blazer is : "+blazerEight.brandName);
				System.out.println("size of the blazer is : "+blazerEight.size);
				System.out.println("color of the blazer is : "+blazerEight.color);
				System.out.println("material type of the blazer is : "+blazerEight.materialType);
				System.out.println("no of buttons on blazer are : "+blazerEight.noOfButtons);
				System.out.println("fit type of the blazer is : "+blazerEight.fitType);
				
			Blazer blazerNine    = new Blazer();
			blazerNine.blazerId = 9;
			blazerNine.brandName = "Louis Philippe";
			blazerNine.size		= "L";
			blazerNine.color		= "Magenta";
			blazerNine.materialType = "cotton";
			blazerNine.noOfButtons  = 3;
			blazerNine.fitType	   = "Slim fit";
				System.out.println();
				System.out.println("Blazer nine details : ");
				System.out.println("Id of blazer is : "+blazerNine.blazerId);
				System.out.println("brand name of blazer is : "+blazerNine.brandName);
				System.out.println("size of the blazer is : "+blazerNine.size);
				System.out.println("color of the blazer is : "+blazerNine.color);
				System.out.println("material type of the blazer is : "+blazerNine.materialType);
				System.out.println("no of buttons on blazer are : "+blazerNine.noOfButtons);
				System.out.println("fit type of the blazer is : "+blazerNine.fitType);
				
			Blazer blazerTen    = new Blazer();
			blazerTen.blazerId = 10;
			blazerTen.brandName = "Peter England";
			blazerTen.size		= "S";
			blazerTen.color		= "Royal Blue";
			blazerTen.materialType = "Linen";
			blazerTen.noOfButtons  = 2;
			blazerTen.fitType	   = "Slim fit";
				System.out.println();
				System.out.println("Blazer ten details : ");
				System.out.println("Id of blazer is : "+blazerTen.blazerId);
				System.out.println("brand name of blazer is : "+blazerTen.brandName);
				System.out.println("size of the blazer is : "+blazerTen.size);
				System.out.println("color of the blazer is : "+blazerTen.color);
				System.out.println("material type of the blazer is : "+blazerTen.materialType);
				System.out.println("no of buttons on blazer are : "+blazerTen.noOfButtons);
				System.out.println("fit type of the blazer is : "+blazerTen.fitType);
				
			Blazer blazerEleven    = new Blazer();
			blazerEleven.blazerId = 11;
			blazerEleven.brandName = "Van Heusen";
			blazerEleven.size		= "M";
			blazerEleven.color		= "Sky Blue";
			blazerEleven.materialType = "cotton";
			blazerEleven.noOfButtons  = 3;
			blazerEleven.fitType	   = "Regular fit";
				System.out.println();
				System.out.println("Blazer eleven details : ");
				System.out.println("Id of blazer is : "+blazerEleven.blazerId);
				System.out.println("brand name of blazer is : "+blazerEleven.brandName);
				System.out.println("size of the blazer is : "+blazerEleven.size);
				System.out.println("color of the blazer is : "+blazerEleven.color);
				System.out.println("material type of the blazer is : "+blazerEleven.materialType);
				System.out.println("no of buttons on blazer are : "+blazerEleven.noOfButtons);
				System.out.println("fit type of the blazer is : "+blazerEleven.fitType);
				
			Blazer blazerTwelve    = new Blazer();
			blazerTwelve.blazerId = 12;
			blazerTwelve.brandName = "Raymond";
			blazerTwelve.size		= "XL";
			blazerTwelve.color		= "Red";
			blazerTwelve.materialType = "wool";
			blazerTwelve.noOfButtons  = 2;
			blazerTwelve.fitType	   = "Slim fit";
				System.out.println();
				System.out.println("Blazer twelve details : ");
				System.out.println("Id of blazer is : "+blazerTwelve.blazerId);
				System.out.println("brand name of blazer is : "+blazerTwelve.brandName);
				System.out.println("size of the blazer is : "+blazerTwelve.size);
				System.out.println("color of the blazer is : "+blazerTwelve.color);
				System.out.println("material type of the blazer is : "+blazerTwelve.materialType);
				System.out.println("no of buttons on blazer are : "+blazerTwelve.noOfButtons);
				System.out.println("fit type of the blazer is : "+blazerTwelve.fitType);
				
			Blazer blazerThirteen   = new Blazer();
			blazerThirteen.blazerId = 13;
			blazerThirteen.brandName = "Blackberrys";
			blazerThirteen.size		= "M";
			blazerThirteen.color		= "Beige";
			blazerThirteen.materialType = "cotton";
			blazerThirteen.noOfButtons  = 3;
			blazerThirteen.fitType	   = "Slim fit";
				System.out.println();
				System.out.println("Blazer thirteen details : ");
				System.out.println("Id of blazer is : "+blazerThirteen.blazerId);
				System.out.println("brand name of blazer is : "+blazerThirteen.brandName);
				System.out.println("size of the blazer is : "+blazerThirteen.size);
				System.out.println("color of the blazer is : "+blazerThirteen.color);
				System.out.println("material type of the blazer is : "+blazerThirteen.materialType);
				System.out.println("no of buttons on blazer are : "+blazerThirteen.noOfButtons);
				System.out.println("fit type of the blazer is : "+blazerThirteen.fitType);
				
			Blazer blazerFourteen   = new Blazer();
			blazerFourteen.blazerId = 14;
			blazerFourteen.brandName = "Raymond";
			blazerFourteen.size		= "XXL";
			blazerFourteen.color		= "Peach";
			blazerFourteen.materialType = "cotton";
			blazerFourteen.noOfButtons  = 2;
			blazerFourteen.fitType	   = "Regular fit";
				System.out.println();
				System.out.println("Blazer fourteen details : ");
				System.out.println("Id of blazer is : "+blazerFourteen.blazerId);
				System.out.println("brand name of blazer is : "+blazerFourteen.brandName);
				System.out.println("size of the blazer is : "+blazerFourteen.size);
				System.out.println("color of the blazer is : "+blazerFourteen.color);
				System.out.println("material type of the blazer is : "+blazerFourteen.materialType);
				System.out.println("no of buttons on blazer are : "+blazerFourteen.noOfButtons);
				System.out.println("fit type of the blazer is : "+blazerFourteen.fitType);
				
			Blazer blazerFifteen   = new Blazer();
			blazerFifteen.blazerId = 15;
			blazerFifteen.brandName = "Peter England";
			blazerFifteen.size		= "L";
			blazerFifteen.color		= "Ash Grey";
			blazerFifteen.materialType = "cotton";
			blazerFifteen.noOfButtons  = 3;
			blazerFifteen.fitType	   = "Slim fit";
				System.out.println();
				System.out.println("Blazer fifteen details : ");
				System.out.println("Id of blazer is : "+blazerFifteen.blazerId);
				System.out.println("brand name of blazer is : "+blazerFifteen.brandName);
				System.out.println("size of the blazer is : "+blazerFifteen.size);
				System.out.println("color of the blazer is : "+blazerFifteen.color);
				System.out.println("material type of the blazer is : "+blazerFifteen.materialType);
				System.out.println("no of buttons on blazer are : "+blazerFifteen.noOfButtons);
				System.out.println("fit type of the blazer is : "+blazerFifteen.fitType);
				
			Blazer blazerSixteen   = new Blazer();
			blazerSixteen.blazerId = 16;
			blazerSixteen.brandName = "Tommy Hilfiger";
			blazerSixteen.size		= "M";
			blazerSixteen.color		= "Olive Green";
			blazerSixteen.materialType = "Linen";
			blazerSixteen.noOfButtons  = 2;
			blazerSixteen.fitType	   = "Slim fit";
				System.out.println();
				System.out.println("Blazer sixteen details : ");
				System.out.println("Id of blazer is : "+blazerSixteen.blazerId);
				System.out.println("brand name of blazer is : "+blazerSixteen.brandName);
				System.out.println("size of the blazer is : "+blazerSixteen.size);
				System.out.println("color of the blazer is : "+blazerSixteen.color);
				System.out.println("material type of the blazer is : "+blazerSixteen.materialType);
				System.out.println("no of buttons on blazer are : "+blazerSixteen.noOfButtons);
				System.out.println("fit type of the blazer is : "+blazerSixteen.fitType);
				
			Blazer blazerSeventeen   = new Blazer();
			blazerSeventeen.blazerId = 17;
			blazerSeventeen.brandName = "Peter England";
			blazerSeventeen.size		= "M";
			blazerSeventeen.color		= "Black";
			blazerSeventeen.materialType = "Linen";
			blazerSeventeen.noOfButtons  = 3;
			blazerSeventeen.fitType	   = "Slim fit";
				System.out.println();
				System.out.println("Blazer seventeen details : ");
				System.out.println("Id of blazer is : "+blazerSeventeen.blazerId);
				System.out.println("brand name of blazer is : "+blazerSeventeen.brandName);
				System.out.println("size of the blazer is : "+blazerSeventeen.size);
				System.out.println("color of the blazer is : "+blazerSeventeen.color);
				System.out.println("material type of the blazer is : "+blazerSeventeen.materialType);
				System.out.println("no of buttons on blazer are : "+blazerSeventeen.noOfButtons);
				System.out.println("fit type of the blazer is : "+blazerSeventeen.fitType);
				
			Blazer blazerEighteen   = new Blazer();
			blazerEighteen.blazerId = 18;
			blazerEighteen.brandName = "Raymond";
			blazerEighteen.size		= "XL";
			blazerEighteen.color		= "Orange";
			blazerEighteen.materialType = "cotton";
			blazerEighteen.noOfButtons  = 2;
			blazerEighteen.fitType	   = "Regular fit";
				System.out.println();
				System.out.println("Blazer eighteen details : ");
				System.out.println("Id of blazer is : "+blazerEighteen.blazerId);
				System.out.println("brand name of blazer is : "+blazerEighteen.brandName);
				System.out.println("size of the blazer is : "+blazerEighteen.size);
				System.out.println("color of the blazer is : "+blazerEighteen.color);
				System.out.println("material type of the blazer is : "+blazerEighteen.materialType);
				System.out.println("no of buttons on blazer are : "+blazerEighteen.noOfButtons);
				System.out.println("fit type of the blazer is : "+blazerEighteen.fitType);
			
			Blazer blazerNineteen   = new Blazer();
			blazerNineteen.blazerId = 19;
			blazerNineteen.brandName = "Van Heusen";
			blazerNineteen.size		= "L";
			blazerNineteen.color		= "Yellow";
			blazerNineteen.materialType = "wool";
			blazerNineteen.noOfButtons  = 2;
			blazerNineteen.fitType	   = "Slim fit";
				System.out.println();
				System.out.println("Blazer nineteen details : ");
				System.out.println("Id of blazer is : "+blazerNineteen.blazerId);
				System.out.println("brand name of blazer is : "+blazerNineteen.brandName);
				System.out.println("size of the blazer is : "+blazerNineteen.size);
				System.out.println("color of the blazer is : "+blazerNineteen.color);
				System.out.println("material type of the blazer is : "+blazerNineteen.materialType);
				System.out.println("no of buttons on blazer are : "+blazerNineteen.noOfButtons);
				System.out.println("fit type of the blazer is : "+blazerNineteen.fitType);
				
			Blazer blazerTwenty   = new Blazer();
			blazerTwenty.blazerId = 20;
			blazerTwenty.brandName = "Tommy Hilfiger";
			blazerTwenty.size		= "XS";
			blazerTwenty.color		= "Purple";
			blazerTwenty.materialType = "Linen";
			blazerTwenty.noOfButtons  = 3;
			blazerTwenty.fitType	   = "Regular fit";
				System.out.println();
				System.out.println("Blazer twenty details : ");
				System.out.println("Id of blazer is : "+blazerTwenty.blazerId);
				System.out.println("brand name of blazer is : "+blazerTwenty.brandName);
				System.out.println("size of the blazer is : "+blazerTwenty.size);
				System.out.println("color of the blazer is : "+blazerTwenty.color);
				System.out.println("material type of the blazer is : "+blazerTwenty.materialType);
				System.out.println("no of buttons on blazer are : "+blazerTwenty.noOfButtons);
				System.out.println("fit type of the blazer is : "+blazerTwenty.fitType);
				System.out.println();
		System.out.println("main ended");
	}

}