class CasinoRunner{
	public static void main(String[] casino){
	
		System.out.println("main started");
			Casino casinoOne=new Casino();
			casinoOne.casinoId=1;
			casinoOne.casinoName="Casino Royale";
			casinoOne.location= "Las Vegas";
			casinoOne.establishedYear=1995;
			casinoOne.numberOfTablesGames=50;
			casinoOne.numberOfSlotMachines=1500;
				System.out.println();
				System.out.println("casino one details:");
				System.out.println("id of casino is : "+casinoOne.casinoId);
				System.out.println("name of casino is : "+casinoOne.casinoName);
				System.out.println("casino is located at : "+casinoOne.location);
				System.out.println("establishedYear of the casino is : "+casinoOne.establishedYear);
				System.out.println("number of table games : "+casinoOne.numberOfTablesGames);
				System.out.println("number of slot machines :"+casinoOne.numberOfSlotMachines);
			
			Casino casinoTwo=new Casino();
			casinoTwo.casinoId = 2;
			casinoTwo.casinoName = "Golden Mirage";
			casinoTwo.location = "Macau";
			casinoTwo.establishedYear = 2000;
			casinoTwo.numberOfTablesGames = 80;
			casinoTwo.numberOfSlotMachines = 1200;
				System.out.println();
				System.out.println("casino two details:");
				System.out.println("id of casino is : "+casinoTwo.casinoId);
				System.out.println("name of casino is : "+casinoTwo.casinoName);
				System.out.println("casino is located at : "+casinoTwo.location);
				System.out.println("establishedYear of the casino is : "+casinoTwo.establishedYear);
				System.out.println("number of table games : "+casinoTwo.numberOfTablesGames);
				System.out.println("number of slot machines :"+casinoTwo.numberOfSlotMachines);
				
			Casino casinoThree=new Casino();
			casinoThree.casinoId = 3;
			casinoThree.casinoName = "Silver Palace";
			casinoThree.location = "Monaco";
			casinoThree.establishedYear = 1985;
			casinoThree.numberOfTablesGames = 60;
			casinoThree.numberOfSlotMachines = 900;
				System.out.println();
				System.out.println("casino three details:");
				System.out.println("id of casino is : "+casinoThree.casinoId);
				System.out.println("name of casino is : "+casinoThree.casinoName);
				System.out.println("casino is located at : "+casinoThree.location);
				System.out.println("establishedYear of the casino is : "+casinoThree.establishedYear);
				System.out.println("number of table games : "+casinoThree.numberOfTablesGames);
				System.out.println("number of slot machines :"+casinoThree.numberOfSlotMachines);
				
			Casino casinoFour=new Casino();
			casinoFour.casinoId = 4;
			casinoFour.casinoName = "Ocean Luck Casino";
			casinoFour.location = "Goa";
			casinoFour.establishedYear = 2010;
			casinoFour.numberOfTablesGames = 40;
			casinoFour.numberOfSlotMachines = 700;
				System.out.println();
				System.out.println("casino four details:");
				System.out.println("id of casino is : "+casinoFour.casinoId);
				System.out.println("name of casino is : "+casinoFour.casinoName);
				System.out.println("casino is located at : "+casinoFour.location);
				System.out.println("establishedYear of the casino is : "+casinoFour.establishedYear);
				System.out.println("number of table games : "+casinoFour.numberOfTablesGames);
				System.out.println("number of slot machines :"+casinoFour.numberOfSlotMachines);
				
			Casino casinoFive=new Casino();
			casinoFive.casinoId = 5;
			casinoFive.casinoName = "Desert Treasure";
			casinoFive.location = "Dubai";
			casinoFive.establishedYear = 2015;
			casinoFive.numberOfTablesGames = 45;
			casinoFive.numberOfSlotMachines = 1100;
				System.out.println();
				System.out.println("casino five details:");
				System.out.println("id of casino is : "+casinoFive.casinoId);
				System.out.println("name of casino is : "+casinoFive.casinoName);
				System.out.println("casino is located at : "+casinoFive.location);
				System.out.println("establishedYear of the casino is : "+casinoFive.establishedYear);
				System.out.println("number of table games : "+casinoFive.numberOfTablesGames);
				System.out.println("number of slot machines :"+casinoFive.numberOfSlotMachines);
				
			Casino casinoSix=new Casino();
			casinoSix.casinoId = 6;
			casinoSix.casinoName = "Sunset Spin";
			casinoSix.location = "Singapore";
			casinoSix.establishedYear = 2008;
			casinoSix.numberOfTablesGames = 55;
			casinoSix.numberOfSlotMachines = 1300;
				System.out.println();
				System.out.println("casino six details:");
				System.out.println("id of casino is : "+casinoSix.casinoId);
				System.out.println("name of casino is : "+casinoSix.casinoName);
				System.out.println("casino is located at : "+casinoSix.location);
				System.out.println("establishedYear of the casino is : "+casinoSix.establishedYear);
				System.out.println("number of table games : "+casinoSix.numberOfTablesGames);
				System.out.println("number of slot machines :"+casinoSix.numberOfSlotMachines);
				
			Casino casinoSeven=new Casino();
			casinoSeven.casinoId = 7;
			casinoSeven.casinoName = "Royal Ace";
			casinoSeven.location = "London";
			casinoSeven.establishedYear = 1990;
			casinoSeven.numberOfTablesGames = 65;
			casinoSeven.numberOfSlotMachines = 850;
				System.out.println();
				System.out.println("casino seven details:");
				System.out.println("id of casino is : "+casinoSeven.casinoId);
				System.out.println("name of casino is : "+casinoSeven.casinoName);
				System.out.println("casino is located at : "+casinoSeven.location);
				System.out.println("establishedYear of the casino is : "+casinoSeven.establishedYear);
				System.out.println("number of table games : "+casinoSeven.numberOfTablesGames);
				System.out.println("number of slot machines :"+casinoSeven.numberOfSlotMachines);
				
			Casino casinoEight=new Casino();
			casinoEight.casinoId = 8;
			casinoEight.casinoName = "Jungle Jackpot";
			casinoEight.location = "South Africa";
			casinoEight.establishedYear = 2005;
			casinoEight.numberOfTablesGames = 30;
			casinoEight.numberOfSlotMachines = 600;
				System.out.println();
				System.out.println("casino eight details:");
				System.out.println("id of casino is : "+casinoEight.casinoId);
				System.out.println("name of casino is : "+casinoEight.casinoName);
				System.out.println("casino is located at : "+casinoEight.location);
				System.out.println("establishedYear of the casino is : "+casinoEight.establishedYear);
				System.out.println("number of table games : "+casinoEight.numberOfTablesGames);
				System.out.println("number of slot machines :"+casinoEight.numberOfSlotMachines);
				
			Casino casinoNine=new Casino();
			casinoNine.casinoId = 9;
			casinoNine.casinoName = "Emerald Spins";
			casinoNine.location = "Ireland";
			casinoNine.establishedYear = 1998;
			casinoNine.numberOfTablesGames = 35;
			casinoNine.numberOfSlotMachines = 750;
				System.out.println();
				System.out.println("casino nine details:");
				System.out.println("id of casino is : "+casinoNine.casinoId);
				System.out.println("name of casino is : "+casinoNine.casinoName);
				System.out.println("casino is located at : "+casinoNine.location);
				System.out.println("establishedYear of the casino is : "+casinoNine.establishedYear);
				System.out.println("number of table games : "+casinoNine.numberOfTablesGames);
				System.out.println("number of slot machines :"+casinoNine.numberOfSlotMachines);
				
			Casino casinoTen=new Casino();
			casinoTen.casinoId = 10;
			casinoTen.casinoName = "Diamond Wheel";
			casinoTen.location = "Las Vegas";
			casinoTen.establishedYear = 1980;
			casinoTen.numberOfTablesGames = 90;
			casinoTen.numberOfSlotMachines = 2000;
				System.out.println();
				System.out.println("casino ten details:");
				System.out.println("id of casino is : "+casinoTen.casinoId);
				System.out.println("name of casino is : "+casinoTen.casinoName);
				System.out.println("casino is located at : "+casinoTen.location);
				System.out.println("establishedYear of the casino is : "+casinoTen.establishedYear);
				System.out.println("number of table games : "+casinoTen.numberOfTablesGames);
				System.out.println("number of slot machines :"+casinoTen.numberOfSlotMachines);
				
			Casino casinoEleven=new Casino();
			casinoEleven.casinoId = 11;
			casinoEleven.casinoName = "Volcano Vegas";
			casinoEleven.location = "Hawaii";
			casinoEleven.establishedYear = 2012;
			casinoEleven.numberOfTablesGames = 38;
			casinoEleven.numberOfSlotMachines = 720;
				System.out.println();
				System.out.println("casino eleven details:");
				System.out.println("id of casino is : "+casinoEleven.casinoId);
				System.out.println("name of casino is : "+casinoEleven.casinoName);
				System.out.println("casino is located at : "+casinoEleven.location);
				System.out.println("establishedYear of the casino is : "+casinoEleven.establishedYear);
				System.out.println("number of table games : "+casinoEleven.numberOfTablesGames);
				System.out.println("number of slot machines :"+casinoEleven.numberOfSlotMachines);
				
			Casino casinoTwelve=new Casino();
			casinoTwelve.casinoId = 12;
			casinoTwelve.casinoName = "Riverboat Casino";
			casinoTwelve.location = "Mississippi";
			casinoTwelve.establishedYear = 1996;
			casinoTwelve.numberOfTablesGames = 50;
			casinoTwelve.numberOfSlotMachines = 880;
				System.out.println();
				System.out.println("casino twelve details:");
				System.out.println("id of casino is : "+casinoTwelve.casinoId);
				System.out.println("name of casino is : "+casinoTwelve.casinoName);
				System.out.println("casino is located at : "+casinoTwelve.location);
				System.out.println("establishedYear of the casino is : "+casinoTwelve.establishedYear);
				System.out.println("number of table games : "+casinoTwelve.numberOfTablesGames);
				System.out.println("number of slot machines :"+casinoTwelve.numberOfSlotMachines);
				
			Casino casinoThirteen=new Casino();
			casinoThirteen.casinoId = 13;
			casinoThirteen.casinoName = "Sky High Casino";
			casinoThirteen.location = "Dubai";
			casinoThirteen.establishedYear = 2020;
			casinoThirteen.numberOfTablesGames = 70;
			casinoThirteen.numberOfSlotMachines = 1100;
				System.out.println();
				System.out.println("casino thirteen details:");
				System.out.println("id of casino is : "+casinoThirteen.casinoId);
				System.out.println("name of casino is : "+casinoThirteen.casinoName);
				System.out.println("establishedYear of the casino is : "+casinoThirteen.establishedYear);
				System.out.println("number of table games : "+casinoThirteen.numberOfTablesGames);
				System.out.println("number of slot machines :"+casinoThirteen.numberOfSlotMachines);
				
			Casino casinoFourteen=new Casino();
			casinoFourteen.casinoId = 14;
			casinoFourteen.casinoName = "Tropic Bet";
			casinoFourteen.location = "Bahamas";
			casinoFourteen.establishedYear = 2003;
			casinoFourteen.numberOfTablesGames = 60;
			casinoFourteen.numberOfSlotMachines = 970;
				System.out.println();
				System.out.println("casino fourteen details:");
				System.out.println("id of casino is : "+casinoFourteen.casinoId);
				System.out.println("name of casino is : "+casinoFourteen.casinoName);
				System.out.println("casino is located at : "+casinoFourteen.location);
				System.out.println("establishedYear of the casino is : "+casinoFourteen.establishedYear);
				System.out.println("number of table games : "+casinoFourteen.numberOfTablesGames);
				System.out.println("number of slot machines :"+casinoFourteen.numberOfSlotMachines);
				
			Casino casinoFifteen=new Casino();
			casinoFifteen.casinoId = 15;
			casinoFifteen.casinoName = "Monte Glory";
			casinoFifteen.location = "Monte Carlo";
			casinoFifteen.establishedYear = 1975;
			casinoFifteen.numberOfTablesGames = 100;
			casinoFifteen.numberOfSlotMachines = 1900;
				System.out.println();
				System.out.println("casino fifteen details:");
				System.out.println("id of casino is : "+casinoFifteen.casinoId);
				System.out.println("name of casino is : "+casinoFifteen.casinoName);
				System.out.println("casino is located at : "+casinoFifteen.location);
				System.out.println("establishedYear of the casino is : "+casinoFifteen.establishedYear);
				System.out.println("number of table games : "+casinoFifteen.numberOfTablesGames);
				System.out.println("number of slot machines :"+casinoFifteen.numberOfSlotMachines);
				
			Casino casinoSixteen=new Casino();
			casinoSixteen.casinoId = 16;
			casinoSixteen.casinoName = "Zenith Casino";
			casinoSixteen.location = "Tokyo";
			casinoSixteen.establishedYear = 2007;
			casinoSixteen.numberOfTablesGames = 42;
			casinoSixteen.numberOfSlotMachines = 640;
				System.out.println();
				System.out.println("casino sixteen details:");
				System.out.println("id of casino is : "+casinoSixteen.casinoId);
				System.out.println("name of casino is : "+casinoSixteen.casinoName);
				System.out.println("casino is located at : "+casinoSixteen.location);
				System.out.println("establishedYear of the casino is : "+casinoSixteen.establishedYear);
				System.out.println("number of table games : "+casinoSixteen.numberOfTablesGames);
				System.out.println("number of slot machines :"+casinoSixteen.numberOfSlotMachines);
				
			
			Casino casinoSeventeen=new Casino();
			casinoSeventeen.casinoId = 17;
			casinoSeventeen.casinoName = "Starlight Spins";
			casinoSeventeen.location = "Malaysia";
			casinoSeventeen.establishedYear = 2001;
			casinoSeventeen.numberOfTablesGames = 48;
			casinoSeventeen.numberOfSlotMachines = 770;
				System.out.println();
				System.out.println("casino seventeen details:");
				System.out.println("id of casino is : "+casinoSeventeen.casinoId);
				System.out.println("name of casino is : "+casinoSeventeen.casinoName);
				System.out.println("casino is located at : "+casinoSeventeen.location);
				System.out.println("establishedYear of the casino is : "+casinoSeventeen.establishedYear);
				System.out.println("number of table games : "+casinoSeventeen.numberOfTablesGames);
				System.out.println("number of slot machines :"+casinoSeventeen.numberOfSlotMachines);
				
			Casino casinoEighteen=new Casino();
			casinoEighteen.casinoId = 18;
			casinoEighteen.casinoName = "Moonlight Palace";
			casinoEighteen.location = "Vietnam";
			casinoEighteen.establishedYear = 2016;
			casinoEighteen.numberOfTablesGames = 36;
			casinoEighteen.numberOfSlotMachines = 830;
				System.out.println();
				System.out.println("casino eighteen details:");
				System.out.println("id of casino is : "+casinoEighteen.casinoId);
				System.out.println("name of casino is : "+casinoEighteen.casinoName);
				System.out.println("casino is located at : "+casinoEighteen.location);
				System.out.println("establishedYear of the casino is : "+casinoEighteen.establishedYear);
				System.out.println("number of table games : "+casinoEighteen.numberOfTablesGames);
				System.out.println("number of slot machines :"+casinoEighteen.numberOfSlotMachines);
				
			Casino casinoNineteen=new Casino();
			casinoNineteen.casinoId = 19;
			casinoNineteen.casinoName = "Casino Horizon";
			casinoNineteen.location = "New Zealand";
			casinoNineteen.establishedYear = 2004;
			casinoNineteen.numberOfTablesGames = 58;
			casinoNineteen.numberOfSlotMachines = 980;
				System.out.println();
				System.out.println("casino nineteen details:");
				System.out.println("id of casino is : "+casinoNineteen.casinoId);
				System.out.println("name of casino is : "+casinoNineteen.casinoName);
				System.out.println("casino is located at : "+casinoNineteen.location);
				System.out.println("establishedYear of the casino is : "+casinoNineteen.establishedYear);
				System.out.println("number of table games : "+casinoNineteen.numberOfTablesGames);
				System.out.println("number of slot machines :"+casinoNineteen.numberOfSlotMachines);
				
			Casino casinoTwenty=new Casino();
			casinoTwenty.casinoId = 20;
			casinoTwenty.casinoName = "Phoenix Gamble";
			casinoTwenty.location = "Philippines";
			casinoTwenty.establishedYear = 2018;
			casinoTwenty.numberOfTablesGames = 44;
			casinoTwenty.numberOfSlotMachines = 1010;
				System.out.println();
				System.out.println("casino twenty details:");
				System.out.println("id of casino is : "+casinoTwenty.casinoId);
				System.out.println("name of casino is : "+casinoTwenty.casinoName);
				System.out.println("casino is located at : "+casinoTwenty.location);
				System.out.println("establishedYear of the casino is : "+casinoTwenty.establishedYear);
				System.out.println("number of table games : "+casinoTwenty.numberOfTablesGames);
				System.out.println("number of slot machines :"+casinoTwenty.numberOfSlotMachines);
			
		System.out.println("main ended");
	}

}