class CourtCaseRunner{
	public static void main(String[] cases){
		System.out.println("main started");
			CourtCase caseOne= new CourtCase();
			caseOne.caseId=1;
			caseOne.caseType="Civil Case";
			caseOne.caseTitle="State vs BBMP";
			caseOne.courtName="High Court";
			caseOne.filingDate="23/07/2025";
			caseOne.plaintiffName="Rashmi";
			caseOne.defendantName="BBMP";
				System.out.println();
				System.out.println("first court case details :");
				System.out.println("id of the case is : "+caseOne.caseId);
				System.out.println("type of the case is : "+caseOne.caseType);
				System.out.println("title of the case is : "+caseOne.caseTitle);
				System.out.println("name of the court is : "+caseOne.courtName);
				System.out.println("filing date of the case is : "+caseOne.filingDate);
				System.out.println("plaintiffName of the case is : "+caseOne.plaintiffName);
				System.out.println("defendantName of the case is : "+caseOne.defendantName);
			
			CourtCase caseTwo= new CourtCase();
			caseTwo.caseId = 2;
			caseTwo.caseType = "Criminal Case";
			caseTwo.caseTitle = "State vs Rahul";
			caseTwo.courtName = "Supreme Court";
			caseTwo.filingDate = "12/06/2024";
			caseTwo.plaintiffName = "Government of India";
			caseTwo.defendantName = "Rahul K";
				System.out.println();
				System.out.println("second court case details :");
				System.out.println("id of the case is : "+caseTwo.caseId);
				System.out.println("type of the case is : "+caseTwo.caseType);
				System.out.println("title of the case is : "+caseTwo.caseTitle);
				System.out.println("name of the court is : "+caseTwo.courtName);
				System.out.println("filing date of the case is : "+caseTwo.filingDate);
				System.out.println("plaintiffName of the case is : "+caseTwo.plaintiffName);
				System.out.println("defendantName of the case is : "+caseTwo.defendantName);
			
			CourtCase caseThree= new CourtCase();
			caseThree.caseId = 3;
			caseThree.caseType = "Family Case";
			caseThree.caseTitle = "Anjali vs Mohan";
			caseThree.courtName = "Family Court";
			caseThree.filingDate = "01/03/2023";
			caseThree.plaintiffName = "Anjali M";
			caseThree.defendantName = "Mohan B";
				System.out.println();
				System.out.println("third court case details :");
				System.out.println("id of the case is : "+caseThree.caseId);
				System.out.println("type of the case is : "+caseThree.caseType);
				System.out.println("title of the case is : "+caseThree.caseTitle);
				System.out.println("name of the court is : "+caseThree.courtName);
				System.out.println("filing date of the case is : "+caseThree.filingDate);
				System.out.println("plaintiffName of the case is : "+caseThree.plaintiffName);
				System.out.println("defendantName of the case is : "+caseThree.defendantName);
			
			CourtCase caseFour= new CourtCase();
			caseFour.caseId = 4;
			caseFour.caseType = "Civil Case";
			caseFour.caseTitle = "Shruthi vs BBMP";
			caseFour.courtName = "City Civil Court";
			caseFour.filingDate = "19/08/2022";
			caseFour.plaintiffName = "Shruthi H";
			caseFour.defendantName = "BBMP";
				System.out.println();
				System.out.println("fourth court case details :");
				System.out.println("id of the case is : "+caseFour.caseId);
				System.out.println("type of the case is : "+caseFour.caseType);
				System.out.println("title of the case is : "+caseFour.caseTitle);
				System.out.println("name of the court is : "+caseFour.courtName);
				System.out.println("filing date of the case is : "+caseFour.filingDate);
				System.out.println("plaintiffName of the case is : "+caseFour.plaintiffName);
				System.out.println("defendantName of the case is : "+caseFour.defendantName);
			
			CourtCase caseFive= new CourtCase();
			caseFive.caseId = 5;
			caseFive.caseType = "Criminal Case";
			caseFive.caseTitle = "State vs Arjun";
			caseFive.courtName = "Sessions Court";
			caseFive.filingDate = "10/11/2021";
			caseFive.plaintiffName = "State Police";
			caseFive.defendantName = "Arjun K";
				System.out.println();
				System.out.println("fifth court case details :");
				System.out.println("id of the case is : "+caseFive.caseId);
				System.out.println("type of the case is : "+caseFive.caseType);
				System.out.println("title of the case is : "+caseFive.caseTitle);
				System.out.println("name of the court is : "+caseFive.courtName);
				System.out.println("filing date of the case is : "+caseFive.filingDate);
				System.out.println("plaintiffName of the case is : "+caseFive.plaintiffName);
				System.out.println("defendantName of the case is : "+caseFive.defendantName);
			
			CourtCase caseSix= new CourtCase();
			caseSix.caseId = 6;
			caseSix.caseType = "Corporate Dispute";
			caseSix.caseTitle = "TCS vs Infosys";
			caseSix.courtName = "Commercial Court";
			caseSix.filingDate = "15/01/2022";
			caseSix.plaintiffName = "TCS Ltd.";
			caseSix.defendantName = "Infosys Ltd.";
				System.out.println();
				System.out.println("sixth court case details :");
				System.out.println("id of the case is : "+caseSix.caseId);
				System.out.println("type of the case is : "+caseSix.caseType);
				System.out.println("title of the case is : "+caseSix.caseTitle);
				System.out.println("name of the court is : "+caseSix.courtName);
				System.out.println("filing date of the case is : "+caseSix.filingDate);
				System.out.println("plaintiffName of the case is : "+caseSix.plaintiffName);
				System.out.println("defendantName of the case is : "+caseSix.defendantName);
			
			CourtCase caseSeven= new CourtCase();
			caseSeven.caseId = 7;
			caseSeven.caseType = "Labour Case";
			caseSeven.caseTitle = "Shiva vs ABC Pvt Ltd";
			caseSeven.courtName = "Labour Court";
			caseSeven.filingDate = "08/04/2023";
			caseSeven.plaintiffName = "Shiva N";
			caseSeven.defendantName = "ABC Pvt Ltd";
				System.out.println();
				System.out.println("seventh court case details :");
				System.out.println("id of the case is : "+caseSeven.caseId);
				System.out.println("type of the case is : "+caseSeven.caseType);
				System.out.println("title of the case is : "+caseSeven.caseTitle);
				System.out.println("name of the court is : "+caseSeven.courtName);
				System.out.println("filing date of the case is : "+caseSeven.filingDate);
				System.out.println("plaintiffName of the case is : "+caseSeven.plaintiffName);
				System.out.println("defendantName of the case is : "+caseSeven.defendantName);
			
			CourtCase caseEight= new CourtCase();
			caseEight.caseId = 8;
			caseEight.caseType = "Property Dispute";
			caseEight.caseTitle = "Ravi vs Ramesh";
			caseEight.courtName = "District Court";
			caseEight.filingDate = "27/02/2024";
			caseEight.plaintiffName = "Ravi P";
			caseEight.defendantName = "Ramesh R";
				System.out.println();
				System.out.println("eighth court case details :");
				System.out.println("id of the case is : "+caseEight.caseId);
				System.out.println("type of the case is : "+caseEight.caseType);
				System.out.println("title of the case is : "+caseEight.caseTitle);
				System.out.println("name of the court is : "+caseEight.courtName);
				System.out.println("filing date of the case is : "+caseEight.filingDate);
				System.out.println("plaintiffName of the case is : "+caseEight.plaintiffName);
				System.out.println("defendantName of the case is : "+caseEight.defendantName);
			
			CourtCase caseNine= new CourtCase();
			caseNine.caseId = 9;
			caseNine.caseType = "Divorce Case";
			caseNine.caseTitle = "Suma vs Manju";
			caseNine.courtName = "Family Court";
			caseNine.filingDate = "30/09/2021";
			caseNine.plaintiffName = "Suma M";
			caseNine.defendantName = "Manju V";
				System.out.println();
				System.out.println("ninth court case details :");
				System.out.println("id of the case is : "+caseNine.caseId);
				System.out.println("type of the case is : "+caseNine.caseType);
				System.out.println("title of the case is : "+caseNine.caseTitle);
				System.out.println("name of the court is : "+caseNine.courtName);
				System.out.println("filing date of the case is : "+caseNine.filingDate);
				System.out.println("plaintiffName of the case is : "+caseNine.plaintiffName);
				System.out.println("defendantName of the case is : "+caseNine.defendantName);
			
			CourtCase caseTen= new CourtCase();
			caseTen.caseId = 10;
			caseTen.caseType = "Cyber Crime";
			caseTen.caseTitle = "State vs Unknown Hacker";
			caseTen.courtName = "Cyber Crime Court";
			caseTen.filingDate = "05/06/2024";
			caseTen.plaintiffName = "Cyber Cell";
			caseTen.defendantName = "Unknown";
				System.out.println();
				System.out.println("tenth court case details :");
				System.out.println("id of the case is : "+caseTen.caseId);
				System.out.println("type of the case is : "+caseTen.caseType);
				System.out.println("title of the case is : "+caseTen.caseTitle);
				System.out.println("name of the court is : "+caseTen.courtName);
				System.out.println("filing date of the case is : "+caseTen.filingDate);
				System.out.println("plaintiffName of the case is : "+caseTen.plaintiffName);
				System.out.println("defendantName of the case is : "+caseTen.defendantName);
			
			CourtCase caseEleven= new CourtCase();
			caseEleven.caseId = 11;
			caseEleven.caseType = "Civil Case";
			caseEleven.caseTitle = "Priya vs Water Board";
			caseEleven.courtName = "High Court";
			caseEleven.filingDate = "11/01/2023";
			caseEleven.plaintiffName = "Priya D";
				System.out.println();
				System.out.println("eleventh court case details :");
				System.out.println("id of the case is : "+caseEleven.caseId);
				System.out.println("type of the case is : "+caseEleven.caseType);
				System.out.println("title of the case is : "+caseEleven.caseTitle);
				System.out.println("name of the court is : "+caseEleven.courtName);
				System.out.println("filing date of the case is : "+caseEleven.filingDate);
				System.out.println("plaintiffName of the case is : "+caseEleven.plaintiffName);
				System.out.println("defendantName of the case is : "+caseEleven.defendantName);
			
			CourtCase caseTwelve= new CourtCase();
			caseTwelve.caseId = 12;
			caseTwelve.caseType = "Criminal Case";
			caseTwelve.caseTitle = "State vs Sagar";
			caseTwelve.courtName = "Sessions Court";
			caseTwelve.filingDate = "09/12/2022";
			caseTwelve.plaintiffName = "Police Department";
			caseTwelve.defendantName = "Sagar R";
				System.out.println();
				System.out.println("twelveth court case details :");
				System.out.println("id of the case is : "+caseTwelve.caseId);
				System.out.println("type of the case is : "+caseTwelve.caseType);
				System.out.println("title of the case is : "+caseOne.caseTitle);
				System.out.println("name of the court is : "+caseTwelve.courtName);
				System.out.println("filing date of the case is : "+caseTwelve.filingDate);
				System.out.println("plaintiffName of the case is : "+caseTwelve.plaintiffName);
				System.out.println("defendantName of the case is : "+caseTwelve.defendantName);
			
			CourtCase caseThirteen= new CourtCase();
			caseThirteen.caseId = 13;
			caseThirteen.caseType = "Cheque Bounce";
			caseThirteen.caseTitle = "Nithin vs Shilpa";
			caseThirteen.courtName = "Magistrate Court";
			caseThirteen.filingDate = "03/10/2023";
			caseThirteen.plaintiffName = "Nithin V";
			caseThirteen.defendantName = "Shilpa S";
				System.out.println();
				System.out.println("first court case details :");
				System.out.println("id of the case is : "+caseThirteen.caseId);
				System.out.println("type of the case is : "+caseThirteen.caseType);
				System.out.println("title of the case is : "+caseThirteen.caseTitle);
				System.out.println("name of the court is : "+caseThirteen.courtName);
				System.out.println("filing date of the case is : "+caseThirteen.filingDate);
				System.out.println("plaintiffName of the case is : "+caseThirteen.plaintiffName);
				System.out.println("defendantName of the case is : "+caseThirteen.defendantName);
			
			CourtCase caseFourteen= new CourtCase();
			caseFourteen.caseId = 14;
			caseFourteen.caseType = "Environmental Case";
			caseFourteen.caseTitle = "NGO vs Factory X";
			caseFourteen.courtName = "Green Tribunal";
			caseFourteen.filingDate = "20/05/2024";
			caseFourteen.plaintiffName = "Green Future NGO";
			caseFourteen.defendantName = "Factory X Pvt Ltd";
				System.out.println();
				System.out.println("first court case details :");
				System.out.println("id of the case is : "+caseFourteen.caseId);
				System.out.println("type of the case is : "+caseFourteen.caseType);
				System.out.println("title of the case is : "+caseFourteen.caseTitle);
				System.out.println("name of the court is : "+caseFourteen.courtName);
				System.out.println("filing date of the case is : "+caseFourteen.filingDate);
				System.out.println("plaintiffName of the case is : "+caseFourteen.plaintiffName);
				System.out.println("defendantName of the case is : "+caseFourteen.defendantName);
			
			CourtCase caseFifteen= new CourtCase();
			caseFifteen.caseId = 15;
			caseFifteen.caseType = "Consumer Case";
			caseFifteen.caseTitle = "Rohit vs OnlineStore";
			caseFifteen.courtName = "Consumer Court";
			caseFifteen.filingDate = "14/02/2022";
			caseFifteen.plaintiffName = "Rohit G";
			caseFifteen.defendantName = "QuickShop Ltd";
			System.out.println();
			System.out.println("fifteenth court case details :");
			System.out.println("id of the case is : "+caseFifteen.caseId);
			System.out.println("type of the case is : "+caseFifteen.caseType);
			System.out.println("title of the case is : "+caseFifteen.caseTitle);
			System.out.println("name of the court is : "+caseFifteen.courtName);
			System.out.println("filing date of the case is : "+caseFifteen.filingDate);
			System.out.println("plaintiffName of the case is : "+caseFifteen.plaintiffName);
			System.out.println("defendantName of the case is : "+caseFifteen.defendantName);
			
			CourtCase caseSixteen= new CourtCase();
			caseSixteen.caseId = 16;
			caseSixteen.caseType = "Land Dispute";
			caseSixteen.caseTitle = "Villagers vs Builder";
			caseSixteen.courtName = "District Court";
			caseSixteen.filingDate = "21/07/2023";
			caseSixteen.plaintiffName = "Rural Committee";
			caseSixteen.defendantName = "Skyline Developers";
			System.out.println();
			System.out.println("sixteenth court case details :");
			System.out.println("id of the case is : "+caseSixteen.caseId);
			System.out.println("type of the case is : "+caseSixteen.caseType);
			System.out.println("title of the case is : "+caseSixteen.caseTitle);
			System.out.println("name of the court is : "+caseSixteen.courtName);
			System.out.println("filing date of the case is : "+caseSixteen.filingDate);
			System.out.println("plaintiffName of the case is : "+caseSixteen.plaintiffName);
			System.out.println("defendantName of the case is : "+caseSixteen.defendantName);
			
			CourtCase caseSeventeen= new CourtCase();
			caseSeventeen.caseId = 17;
			caseSeventeen.caseType = "Murder Trial";
			caseSeventeen.caseTitle = "State vs Devraj";
			caseSeventeen.courtName = "High Court";
			caseSeventeen.filingDate = "18/12/2021";
			caseSeventeen.plaintiffName = "State Prosecutor";
			caseSeventeen.defendantName = "Devraj P";
			System.out.println();
			System.out.println("seventeenth court case details :");
			System.out.println("id of the case is : "+caseSeventeen.caseId);
			System.out.println("type of the case is : "+caseSeventeen.caseType);
			System.out.println("title of the case is : "+caseSeventeen.caseTitle);
			System.out.println("name of the court is : "+caseSeventeen.courtName);
			System.out.println("filing date of the case is : "+caseSeventeen.filingDate);
			System.out.println("plaintiffName of the case is : "+caseSeventeen.plaintiffName);
			System.out.println("defendantName of the case is : "+caseSeventeen.defendantName);
			
			CourtCase caseEighteen= new CourtCase();
			caseEighteen.caseId = 18;
			caseEighteen.caseType = "Inheritance Dispute";
			caseEighteen.caseTitle = "Kiran vs Family Members";
			caseEighteen.courtName = "Civil Court";
			caseEighteen.filingDate = "04/03/2022";
			caseEighteen.plaintiffName = "Kiran B";
			caseEighteen.defendantName = "Siblings";
			System.out.println();
			System.out.println("eighteenth court case details :");
			System.out.println("id of the case is : "+caseEighteen.caseId);
			System.out.println("type of the case is : "+caseEighteen.caseType);
			System.out.println("title of the case is : "+caseEighteen.caseTitle);
			System.out.println("name of the court is : "+caseEighteen.courtName);
			System.out.println("filing date of the case is : "+caseEighteen.filingDate);
			System.out.println("plaintiffName of the case is : "+caseEighteen.plaintiffName);
			System.out.println("defendantName of the case is : "+caseEighteen.defendantName);
			
			CourtCase caseNineteen= new CourtCase();
			caseNineteen.caseId = 19;
			caseNineteen.caseType = "Trademark Violation";
			caseNineteen.caseTitle = "BrandX vs CopyCo";
			caseNineteen.courtName = "IPR Court";
			caseNineteen.filingDate = "07/09/2023";
			caseNineteen.plaintiffName = "BrandX Ltd";
			caseNineteen.defendantName = "CopyCo Pvt Ltd";
			System.out.println();
			System.out.println("nineteenth court case details :");
			System.out.println("id of the case is : "+caseNineteen.caseId);
			System.out.println("type of the case is : "+caseNineteen.caseType);
			System.out.println("title of the case is : "+caseNineteen.caseTitle);
			System.out.println("name of the court is : "+caseNineteen.courtName);
			System.out.println("filing date of the case is : "+caseNineteen.filingDate);
			System.out.println("plaintiffName of the case is : "+caseNineteen.plaintiffName);
			System.out.println("defendantName of the case is : "+caseNineteen.defendantName);
			
			CourtCase caseTwenty= new CourtCase();
			caseTwenty.caseId = 20;
			caseTwenty.caseType = "Service Dispute";
			caseTwenty.caseTitle = "Employee A vs Company B";
			caseTwenty.courtName = "Labour Court";
			caseTwenty.filingDate = "25/06/2024";
			caseTwenty.plaintiffName = "Employee A";
			caseTwenty.defendantName = "Company B Pvt Ltd";
			System.out.println();
			System.out.println("first court case details :");
			System.out.println("id of the case is : "+caseTwenty.caseId);
			System.out.println("type of the case is : "+caseTwenty.caseType);
			System.out.println("title of the case is : "+caseTwenty.caseTitle);
			System.out.println("name of the court is : "+caseTwenty.courtName);
			System.out.println("filing date of the case is : "+caseTwenty.filingDate);
			System.out.println("plaintiffName of the case is : "+caseTwenty.plaintiffName);
			System.out.println("defendantName of the case is : "+caseTwenty.defendantName);
		System.out.println("main ended");
	}

}