class Court{
	static String courtName;
	static String location;
	static int  establishedYear;
	static int  noOfJudges;
	static String cheifJusticeName;
	static int noOfbenches;
	static boolean hasLawLibrary;
	static boolean isVideoConferenceAvailable;
	static String landmarkNearBy;
	static int noOfCasesHandeledPerYear;
	static int noOfCourtRooms;
	static String workimgDays;
	static boolean hasCctv;
	static String typesOfCases;
	static int noOfCivilCasesHandled;
	static int noOfCriminalCasesHandled;
	static int noOfWorkers;
	static boolean hasFoodStalls;
	static String motto;
	static String buildingStyle;
	public static void main(String court[]){
		System.out.println("The name of the court is "+courtName);
		System.out.println("The court is located at "+location);
		System.out.println("The court was established in the year "+establishedYear);
		System.out.println("The number of Judges in the court are "+noOfJudges);
		System.out.println("The cheif justice name is "+cheifJusticeName);
		System.out.println("The number of benches for the citizens are "+noOfbenches);
		System.out.println("does the court has law library? "+hasLawLibrary);
		System.out.println("is video conference available in the court? "+isVideoConferenceAvailable);
		System.out.println("The landmark near by the court is "+landmarkNearBy);
		System.out.println("The number of cases handled per yer are "+noOfCasesHandeledPerYear);
		System.out.println("The number of court rooms are "+noOfCourtRooms);
		System.out.println("The Working days of the court are "+workimgDays);
		System.out.println("does the court has CCTV Surveillance? "+hasCctv);
		System.out.println("The types of cases handled in the court are : "+typesOfCases);
		System.out.println("The number of civil cases handled are "+noOfCivilCasesHandled);
		System.out.println("The number of criminal cases handled are "+noOfCriminalCasesHandled);
		System.out.println("The number of workers in the court are "+noOfWorkers);
		System.out.println("Does the court has food stalls? "+hasFoodStalls);
		System.out.println("The motto of the court is "+motto);
		System.out.println("The building style of the court is "+buildingStyle);
		System.out.println();
	 String courtName="Karnataka High Court";
	 String location="Bengaluru";
	 int  establishedYear =1884;
	 int  noOfJudges=50;
	 String cheifJusticeName="Valluri Kameswar Rao";
	 int noOfbenches=20;
	 boolean hasLawLibrary=true;
	 boolean isVideoConferenceAvailable=true;
	 String landmarkNearBy="Vidhan soudha";
	 int noOfCasesHandeledPerYear=50000;
	 int noOfCourtRooms=10;
	 String workimgDays="Monday to Friday";
	 boolean hasCctv=true;
	 String typesOfCases="Civil, Criminal, Public Interest Litigation";
	 int noOfCivilCasesHandled=25000;
	 int noOfCriminalCasesHandled=30000;
	 int noOfWorkers=100;
	 boolean hasFoodStalls=true;
	 String motto="Yato Dharma Tato Jaya";
	 String buildingStyle="Neo-classical";
		System.out.println("after re-initialization");
		System.out.println("The name of the court is "+courtName);
		System.out.println("The court is located at "+location);
		System.out.println("The court was established in the year "+establishedYear);
		System.out.println("The number of Judges in the court are "+noOfJudges);
		System.out.println("The cheif justice name is "+cheifJusticeName);
		System.out.println("The number of benches for the citizens are "+noOfbenches);
		System.out.println("does the court has law library? "+hasLawLibrary);
		System.out.println("is video conference available in the court? "+isVideoConferenceAvailable);
		System.out.println("The landmark near by the court is "+landmarkNearBy);
		System.out.println("The number of cases handled per yer are "+noOfCasesHandeledPerYear);
		System.out.println("The number of court rooms are "+noOfCourtRooms);
		System.out.println("The Working days of the court are "+workimgDays);
		System.out.println("does the court has CCTV Surveillance? "+hasCctv);
		System.out.println("The types of cases handled in the court are : "+typesOfCases);
		System.out.println("The number of civil cases handled are "+noOfCivilCasesHandled);
		System.out.println("The number of criminal cases handled are "+noOfCriminalCasesHandled);
		System.out.println("The number of workers in the court are "+noOfWorkers);
		System.out.println("Does the court has food stalls? "+hasFoodStalls);
		System.out.println("The motto of the court is "+motto);
		System.out.println("The building style of the court is "+buildingStyle);
	}
}