class Desktop{
	static String brandName;
	static String modelName;
	static String processor;
	static int ramSize;
	static String storageType;
	static int storageCapacity;
	static String os;
	static double screenSize;
	static boolean isTouchScreen;
	static String graphicsCard;
	static int noOfUsbPorts;
	static boolean hasHdmi;
	static String color;
	static boolean isWebCamIncluded;
	static int warrantyYears;
	static String audioOutput;
	static String serialNumber;
	static String preInstalledSoftware;
	static double price;
	static String coolingSystem;
	public static void main(String desktop[]){
			System.out.println("The brand name of the desktop is "+brandName);
			System.out.println("The model name of the desktop is "+modelName);
			System.out.println("The ram size of the desktop is "+ramSize+" Gb");
			System.out.println("The storage type of this desktop is "+storageType);
			System.out.println("The storage capacity of this desktop is "+storageCapacity+" Gb");
			System.out.println("The os of this desktop is "+os);
			System.out.println("The screen size of this desktop is "+screenSize+" inches");
			System.out.println("Is the desktop touch screen? "+isTouchScreen);
			System.out.println("The graphics card of this desktop is "+graphicsCard);
			System.out.println("The number of usb ports present are "+noOfUsbPorts);
			System.out.println("does the desktop has HDMI? "+hasHdmi);
			System.out.println("The color of the desktop is "+color);
			System.out.println("is web cam included in the desktop? "+isWebCamIncluded);
			System.out.println("The number of the warranty years are "+warrantyYears);
			System.out.println("The audio output of the desktop is "+audioOutput);
			System.out.println("The serial number of this desktop is "+serialNumber);
			System.out.println("The pre installed softwares are "+preInstalledSoftware);
			System.out.println("The price of the desktop is "+price);
			System.out.println("The cooling system of the desktop is "+coolingSystem);
			System.out.println();
	 String brandName="Dell";
	 String modelName="OptiPlex 7090";
	 String processor="Intel Core i7";
	 int ramSize=16;
	 String storageType="SSD";
	 int storageCapacity=512;
	 String os="Windows 11";
	 double screenSize=24.0d;
	 boolean isTouchScreen = false;
	 String graphicsCard="NVIDIA GeForce GTX 1650";
	 int noOfUsbPorts=6;
	 boolean hasHdmi=true;
	 String color="black";
	 boolean isWebCamIncluded=true;
	 int warrantyYears=3;
	 String audioOutput="3.5mm Jack, HDMI Audio";
	 String serialNumber="SN-DESK20250622A";
	 String preInstalledSoftware="MS Office, Chrome, Zoom";
	 double price=62000.00d;
	 String coolingSystem="Air Cooling";
		System.out.println("After re-initialization");
		System.out.println("The brand name of the desktop is "+brandName);
		System.out.println("The model name of the desktop is "+modelName);
		System.out.println("The ram size of the desktop is "+ramSize+" Gb");
		System.out.println("The storage type of this desktop is "+storageType);
		System.out.println("The storage capacity of this desktop is "+storageCapacity+" Gb");
		System.out.println("The os of this desktop is "+os);
		System.out.println("The screen size of this desktop is "+screenSize+" inches");
		System.out.println("Is the desktop touch screen? "+isTouchScreen);
		System.out.println("The graphics card of this desktop is "+graphicsCard);
		System.out.println("The number of usb ports present are "+noOfUsbPorts);
		System.out.println("does the desktop has HDMI? "+hasHdmi);
		System.out.println("The color of the desktop is "+color);
		System.out.println("is web cam included in the desktop? "+isWebCamIncluded);
		System.out.println("The number of the warranty years are "+warrantyYears);
		System.out.println("The audio output of the desktop is "+audioOutput);
		System.out.println("The serial number of this desktop is "+serialNumber);
		System.out.println("The pre installed softwares are "+preInstalledSoftware);
		System.out.println("The price of the desktop is "+price);
		System.out.println("The cooling system of the desktop is "+coolingSystem);
	}
}