class FlowersRunner{

	public static void main(String[] flowers){
	
		System.out.println("main started");
			Flowers flowerOne=new Flowers();
			flowerOne.flowerId=1;
			flowerOne.flowerName="Tulip";
			flowerOne.color="Color";
			flowerOne.scientificName="Tulipa gesneriana";
			flowerOne.nativeRegion="India";
			flowerOne.lifespan="Annual";
				System.out.println();
				System.out.println("flower one details:");
				System.out.println("id of the flower : "+flowerOne.flowerId);
				System.out.println("name of the flower is : "+flowerOne.flowerName);
				System.out.println("color of the flower is : "+flowerOne.flowerName);
				System.out.println("scientificName of the flower is : "+flowerOne.scientificName);
				System.out.println("native region of the flower is : "+flowerOne.nativeRegion);
				System.out.println("lifespan of the flower is : "+flowerOne.lifespan);
			
			Flowers flowerTwo=new Flowers();
			flowerTwo.flowerId = 2;
			flowerTwo.flowerName = "Rose";
			flowerTwo.color = "Pink";
			flowerTwo.scientificName = "Rosa";
			flowerTwo.nativeRegion = "Asia";
			flowerTwo.lifespan = "Perennial";
				System.out.println();
				System.out.println("flower two details:");
				System.out.println("id of the flower : "+flowerTwo.flowerId);
				System.out.println("name of the flower is : "+flowerTwo.flowerName);
				System.out.println("color of the flower is : "+flowerTwo.flowerName);
				System.out.println("scientificName of the flower is : "+flowerTwo.scientificName);
				System.out.println("native region of the flower is : "+flowerTwo.nativeRegion);
				System.out.println("lifespan of the flower is : "+flowerTwo.lifespan);
			
			Flowers flowerThree=new Flowers();
			flowerThree.flowerId = 3;
			flowerThree.flowerName = "Sunflower";
			flowerThree.color = "Yellow";
			flowerThree.scientificName = "Helianthus annuus";
			flowerThree.nativeRegion = "North America";
			flowerThree.lifespan = "Annual";
				System.out.println();
				System.out.println("flower three details:");
				System.out.println("id of the flower : "+flowerThree.flowerId);
				System.out.println("name of the flower is : "+flowerThree.flowerName);
				System.out.println("color of the flower is : "+flowerThree.flowerName);
				System.out.println("scientificName of the flower is : "+flowerThree.scientificName);
				System.out.println("native region of the flower is : "+flowerThree.nativeRegion);
				System.out.println("lifespan of the flower is : "+flowerThree.lifespan);
			
			Flowers flowerFour=new Flowers();
			flowerFour.flowerId = 4;
			flowerFour.flowerName = "Lily";
			flowerFour.color = "White";
			flowerFour.scientificName = "Lilium";
			flowerFour.nativeRegion = "Europe";
			flowerFour.lifespan = "Perennial";
				System.out.println();
				System.out.println("flower four details:");
				System.out.println("id of the flower : "+flowerFour.flowerId);
				System.out.println("name of the flower is : "+flowerFour.flowerName);
				System.out.println("color of the flower is : "+flowerFour.flowerName);
				System.out.println("scientificName of the flower is : "+flowerFour.scientificName);
				System.out.println("native region of the flower is : "+flowerFour.nativeRegion);
				System.out.println("lifespan of the flower is : "+flowerFour.lifespan);
			
			
			Flowers flowerFive=new Flowers();
			flowerFive.flowerId = 5;
			flowerFive.flowerName = "Orchid";
			flowerFive.color = "Purple";
			flowerFive.scientificName = "Orchidaceae";
			flowerFive.nativeRegion = "Worldwide";
			flowerFive.lifespan = "Perennial";
				System.out.println();
				System.out.println("flower five details:");
				System.out.println("id of the flower : "+flowerFive.flowerId);
				System.out.println("name of the flower is : "+flowerFive.flowerName);
				System.out.println("color of the flower is : "+flowerFive.flowerName);
				System.out.println("scientificName of the flower is : "+flowerFive.scientificName);
				System.out.println("native region of the flower is : "+flowerFive.nativeRegion);
				System.out.println("lifespan of the flower is : "+flowerFive.lifespan);
			
			Flowers flowerSix=new Flowers();
			flowerSix.flowerId = 6;
			flowerSix.flowerName = "Marigold";
			flowerSix.color = "Orange";
			flowerSix.scientificName = "Tagetes";
			flowerSix.nativeRegion = "Mexico";
			flowerSix.lifespan = "Annual";
				System.out.println();
				System.out.println("flower six details:");
				System.out.println("id of the flower : "+flowerSix.flowerId);
				System.out.println("name of the flower is : "+flowerSix.flowerName);
				System.out.println("color of the flower is : "+flowerSix.flowerName);
				System.out.println("scientificName of the flower is : "+flowerSix.scientificName);
				System.out.println("native region of the flower is : "+flowerSix.nativeRegion);
				System.out.println("lifespan of the flower is : "+flowerSix.lifespan);
			
			Flowers flowerSeven=new Flowers();
			flowerSeven.flowerId = 7;
			flowerSeven.flowerName = "Daffodil";
			flowerSeven.color = "Yellow";
			flowerSeven.scientificName = "Narcissus";
			flowerSeven.nativeRegion = "Europe";
			flowerSeven.lifespan = "Perennial";
				System.out.println();
				System.out.println("flower seven details:");
				System.out.println("id of the flower : "+flowerSeven.flowerId);
				System.out.println("name of the flower is : "+flowerSeven.flowerName);
				System.out.println("color of the flower is : "+flowerSeven.flowerName);
				System.out.println("scientificName of the flower is : "+flowerSeven.scientificName);
				System.out.println("native region of the flower is : "+flowerSeven.nativeRegion);
				System.out.println("lifespan of the flower is : "+flowerSeven.lifespan);
			
			Flowers flowerEight=new Flowers();
			flowerEight.flowerId = 8;
			flowerEight.flowerName = "Hibiscus";
			flowerEight.color = "Red";
			flowerEight.scientificName = "Hibiscus rosa-sinensis";
			flowerEight.nativeRegion = "Asia";
			flowerEight.lifespan = "Perennial";
				System.out.println();
				System.out.println("flower eight details:");
				System.out.println("id of the flower : "+flowerEight.flowerId);
				System.out.println("name of the flower is : "+flowerEight.flowerName);
				System.out.println("color of the flower is : "+flowerEight.flowerName);
				System.out.println("scientificName of the flower is : "+flowerEight.scientificName);
				System.out.println("native region of the flower is : "+flowerEight.nativeRegion);
				System.out.println("lifespan of the flower is : "+flowerEight.lifespan);
			
			Flowers flowerNine=new Flowers();
			flowerNine.flowerId = 9;
			flowerNine.flowerName = "Daisy";
			flowerNine.color = "White";
			flowerNine.scientificName = "Bellis perennis";
			flowerNine.nativeRegion = "Europe";
			flowerNine.lifespan = "Perennial";
				System.out.println();
				System.out.println("flower nine details:");
				System.out.println("id of the flower : "+flowerNine.flowerId);
				System.out.println("name of the flower is : "+flowerNine.flowerName);
				System.out.println("color of the flower is : "+flowerNine.flowerName);
				System.out.println("scientificName of the flower is : "+flowerNine.scientificName);
				System.out.println("native region of the flower is : "+flowerNine.nativeRegion);
				System.out.println("lifespan of the flower is : "+flowerNine.lifespan);
			
			Flowers flowerTen=new Flowers();
			flowerTen.flowerId = 10;
			flowerTen.flowerName = "Jasmine";
			flowerTen.color = "White";
			flowerTen.scientificName = "Jasminum";
			flowerTen.nativeRegion = "India";
			flowerTen.lifespan = "Perennial";
				System.out.println();
				System.out.println("flower ten details:");
				System.out.println("id of the flower : "+flowerTen.flowerId);
				System.out.println("name of the flower is : "+flowerTen.flowerName);
				System.out.println("color of the flower is : "+flowerTen.flowerName);
				System.out.println("scientificName of the flower is : "+flowerTen.scientificName);
				System.out.println("native region of the flower is : "+flowerTen.nativeRegion);
				System.out.println("lifespan of the flower is : "+flowerTen.lifespan);
			
			Flowers flowerEleven=new Flowers();
			flowerEleven.flowerId = 11;
			flowerEleven.flowerName = "Lavender";
			flowerEleven.color = "Lavender";
			flowerEleven.scientificName = "Lavandula";
			flowerEleven.nativeRegion = "Mediterranean";
			flowerEleven.lifespan = "Perennial";
				System.out.println();
				System.out.println("flower eleven details:");
				System.out.println("id of the flower : "+flowerEleven.flowerId);
				System.out.println("name of the flower is : "+flowerEleven.flowerName);
				System.out.println("color of the flower is : "+flowerEleven.flowerName);
				System.out.println("scientificName of the flower is : "+flowerEleven.scientificName);
				System.out.println("native region of the flower is : "+flowerEleven.nativeRegion);
				System.out.println("lifespan of the flower is : "+flowerEleven.lifespan);
			
			Flowers flowerTwelve=new Flowers();
			flowerTwelve.flowerId = 12;
			flowerTwelve.flowerName = "Lotus";
			flowerTwelve.color = "Pink";
			flowerTwelve.scientificName = "Nelumbo nucifera";
			flowerTwelve.nativeRegion = "Asia";
			flowerTwelve.lifespan = "Perennial";
				System.out.println();
				System.out.println("flower twelve details:");
				System.out.println("id of the flower : "+flowerTwelve.flowerId);
				System.out.println("name of the flower is : "+flowerTwelve.flowerName);
				System.out.println("color of the flower is : "+flowerTwelve.flowerName);
				System.out.println("scientificName of the flower is : "+flowerTwelve.scientificName);
				System.out.println("native region of the flower is : "+flowerTwelve.nativeRegion);
				System.out.println("lifespan of the flower is : "+flowerTwelve.lifespan);
			
			Flowers flowerThirteen=new Flowers();
			flowerThirteen.flowerId = 13;
			flowerThirteen.flowerName = "Zinnia";
			flowerThirteen.color = "Orange";
			flowerThirteen.scientificName = "Zinnia elegans";
			flowerThirteen.nativeRegion = "Mexico";
			flowerThirteen.lifespan = "Annual";
				System.out.println();
				System.out.println("flower thirteen details:");
				System.out.println("id of the flower : "+flowerThirteen.flowerId);
				System.out.println("name of the flower is : "+flowerThirteen.flowerName);
				System.out.println("color of the flower is : "+flowerThirteen.flowerName);
				System.out.println("scientificName of the flower is : "+flowerThirteen.scientificName);
				System.out.println("native region of the flower is : "+flowerThirteen.nativeRegion);
				System.out.println("lifespan of the flower is : "+flowerThirteen.lifespan);
			
			Flowers flowerFourteen=new Flowers();
			flowerFourteen.flowerId = 14;
			flowerFourteen.flowerName = "Peony";
			flowerFourteen.color = "Pink";
			flowerFourteen.scientificName = "Paeonia";
			flowerFourteen.nativeRegion = "Asia";
			flowerFourteen.lifespan = "Perennial";
				System.out.println();
				System.out.println("flower fourteen details:");
				System.out.println("id of the flower : "+flowerFourteen.flowerId);
				System.out.println("name of the flower is : "+flowerFourteen.flowerName);
				System.out.println("color of the flower is : "+flowerFourteen.flowerName);
				System.out.println("scientificName of the flower is : "+flowerFourteen.scientificName);
				System.out.println("native region of the flower is : "+flowerFourteen.nativeRegion);
				System.out.println("lifespan of the flower is : "+flowerFourteen.lifespan);
			
			Flowers flowerFifteen=new Flowers();
			flowerFifteen.flowerId = 15;
			flowerFifteen.flowerName = "Chrysanthemum";
			flowerFifteen.color = "Yellow";
			flowerFifteen.scientificName = "Chrysanthemum indicum";
			flowerFifteen.nativeRegion = "China";
			flowerFifteen.lifespan = "Perennial";
				System.out.println();
				System.out.println("flower fifteen details:");
				System.out.println("id of the flower : "+flowerFifteen.flowerId);
				System.out.println("name of the flower is : "+flowerFifteen.flowerName);
				System.out.println("color of the flower is : "+flowerFifteen.flowerName);
				System.out.println("scientificName of the flower is : "+flowerFifteen.scientificName);
				System.out.println("native region of the flower is : "+flowerFifteen.nativeRegion);
				System.out.println("lifespan of the flower is : "+flowerFifteen.lifespan);
			
			Flowers flowerSixteen=new Flowers();
			flowerSixteen.flowerId = 16;
			flowerSixteen.flowerName = "Gladiolus";
			flowerSixteen.color = "Purple";
			flowerSixteen.scientificName = "Gladiolus hortulanus";
			flowerSixteen.nativeRegion = "South Africa";
			flowerSixteen.lifespan = "Perennial";
				System.out.println();
				System.out.println("flower sixteen details:");
				System.out.println("id of the flower : "+flowerSixteen.flowerId);
				System.out.println("name of the flower is : "+flowerSixteen.flowerName);
				System.out.println("color of the flower is : "+flowerSixteen.flowerName);
				System.out.println("scientificName of the flower is : "+flowerSixteen.scientificName);
				System.out.println("native region of the flower is : "+flowerSixteen.nativeRegion);
				System.out.println("lifespan of the flower is : "+flowerSixteen.lifespan);
			
			Flowers flowerSeventeen=new Flowers();
			flowerSeventeen.flowerId = 17;
			flowerSeventeen.flowerName = "Poppy";
			flowerSeventeen.color = "Red";
			flowerSeventeen.scientificName = "Papaver somniferum";
			flowerSeventeen.nativeRegion = "Europe";
			flowerSeventeen.lifespan = "Annual";
				System.out.println();
				System.out.println("flower seventeen details:");
				System.out.println("id of the flower : "+flowerSeventeen.flowerId);
				System.out.println("name of the flower is : "+flowerSeventeen.flowerName);
				System.out.println("color of the flower is : "+flowerSeventeen.flowerName);
				System.out.println("scientificName of the flower is : "+flowerSeventeen.scientificName);
				System.out.println("native region of the flower is : "+flowerSeventeen.nativeRegion);
				System.out.println("lifespan of the flower is : "+flowerSeventeen.lifespan);
			
			Flowers flowerEighteen=new Flowers();
			flowerEighteen.flowerId = 18;
			flowerEighteen.flowerName = "Bluebell";
			flowerEighteen.color = "Blue";
			flowerEighteen.scientificName = "Hyacinthoides non-scripta";
			flowerEighteen.nativeRegion = "UK";
			flowerEighteen.lifespan = "Perennial";
				System.out.println();
				System.out.println("flower eighteen details:");
				System.out.println("id of the flower : "+flowerEighteen.flowerId);
				System.out.println("name of the flower is : "+flowerEighteen.flowerName);
				System.out.println("color of the flower is : "+flowerEighteen.flowerName);
				System.out.println("scientificName of the flower is : "+flowerEighteen.scientificName);
				System.out.println("native region of the flower is : "+flowerEighteen.nativeRegion);
				System.out.println("lifespan of the flower is : "+flowerEighteen.lifespan);
			
			Flowers flowerNineteen=new Flowers();
			flowerNineteen.flowerId = 19;
			flowerNineteen.flowerName = "Iris";
			flowerNineteen.color = "Violet";
			flowerNineteen.scientificName = "Iris germanica";
			flowerNineteen.nativeRegion = "Europe";
			flowerNineteen.lifespan = "Perennial";
				System.out.println();
				System.out.println("flower nineteen details:");
				System.out.println("id of the flower : "+flowerNineteen.flowerId);
				System.out.println("name of the flower is : "+flowerNineteen.flowerName);
				System.out.println("color of the flower is : "+flowerNineteen.flowerName);
				System.out.println("scientificName of the flower is : "+flowerNineteen.scientificName);
				System.out.println("native region of the flower is : "+flowerNineteen.nativeRegion);
				System.out.println("lifespan of the flower is : "+flowerNineteen.lifespan);
				
			Flowers flowerTwenty=new Flowers();
			flowerTwenty.flowerId = 20;
			flowerTwenty.flowerName = "Snapdragon";
			flowerTwenty.color = "Multicolor";
			flowerTwenty.scientificName = "Antirrhinum majus";
			flowerTwenty.nativeRegion = "Mediterranean";
			flowerTwenty.lifespan = "Annual";
				System.out.println();
				System.out.println("flower twenty details:");
				System.out.println("id of the flower : "+flowerTwenty.flowerId);
				System.out.println("name of the flower is : "+flowerTwenty.flowerName);
				System.out.println("color of the flower is : "+flowerTwenty.flowerName);
				System.out.println("scientificName of the flower is : "+flowerTwenty.scientificName);
				System.out.println("native region of the flower is : "+flowerTwenty.nativeRegion);
				System.out.println("lifespan of the flower is : "+flowerTwenty.lifespan);	
			
				System.out.println("main ended");
	}
}