class ForestSafariRunner{
	public static void main(String[] safari){
		System.out.println("main started");
		
			ForestSafari safariOne=new ForestSafari();
			safariOne.safariId=1;
			safariOne.safariName="Bandipura safari";
			safariOne.safariType="Zeep safari";
			safariOne.safariTimings="10:00 AM to 12:00 PM";
			safariOne.groupSizeLimit=6;
			safariOne.isGuideAvailable=true;
				System.out.println();
				System.out.println("safari one details :");
				System.out.println("id of the safari is :"+safariOne.safariId);
				System.out.println("name of the safari : "+safariOne.safariName);
				System.out.println("type of safari : "+safariOne.safariType);
				System.out.println("timings of safari : "+safariOne.safariTimings);
				System.out.println("group size limit of safari is : "+safariOne.groupSizeLimit);
				System.out.println("is guide avaialable? "+safariOne.isGuideAvailable);
			
			ForestSafari safariTwo=new ForestSafari();
			safariTwo.safariId = 2;
			safariTwo.safariName = "Nagarhole Safari";
			safariTwo.safariType = "Canter Safari";
			safariTwo.safariTimings = "6:00 AM to 8:00 AM";
			safariTwo.groupSizeLimit = 20;
			safariTwo.isGuideAvailable = true;
				System.out.println();
				System.out.println("safari two details :");
				System.out.println("id of the safari is :"+safariTwo.safariId);
				System.out.println("name of the safari : "+safariTwo.safariName);
				System.out.println("type of safari : "+safariTwo.safariType);
				System.out.println("timings of safari : "+safariTwo.safariTimings);
				System.out.println("group size limit of safari is : "+safariTwo.groupSizeLimit);
				System.out.println("is guide avaialable? "+safariTwo.isGuideAvailable);
			
			ForestSafari safariThree=new ForestSafari();
			safariThree.safariId = 3;
			safariThree.safariName = "Ranthambore Safari";
			safariThree.safariType = "Jeep Safari";
			safariThree.safariTimings = "4:00 PM to 6:00 PM";
			safariThree.groupSizeLimit = 6;
			safariThree.isGuideAvailable = true;
				System.out.println();
				System.out.println("safari three details :");
				System.out.println("id of the safari is :"+safariThree.safariId);
				System.out.println("name of the safari : "+safariThree.safariName);
				System.out.println("type of safari : "+safariThree.safariType);
				System.out.println("timings of safari : "+safariThree.safariTimings);
				System.out.println("group size limit of safari is : "+safariThree.groupSizeLimit);
				System.out.println("is guide avaialable? "+safariThree.isGuideAvailable);
			
			ForestSafari safariFour=new ForestSafari();
			safariFour.safariId = 4;
			safariFour.safariName = "Jim Corbett Safari";
			safariFour.safariType = "Elephant Safari";
			safariFour.safariTimings = "7:00 AM to 9:00 AM";
			safariFour.groupSizeLimit = 4;
			safariFour.isGuideAvailable = true;
				System.out.println();
				System.out.println("safari four details :");
				System.out.println("id of the safari is :"+safariFour.safariId);
				System.out.println("name of the safari : "+safariFour.safariName);
				System.out.println("type of safari : "+safariFour.safariType);
				System.out.println("timings of safari : "+safariFour.safariTimings);
				System.out.println("group size limit of safari is : "+safariFour.groupSizeLimit);
				System.out.println("is guide avaialable? "+safariFour.isGuideAvailable);
			
			ForestSafari safariFive=new ForestSafari();
			safariFive.safariId = 5;
			safariFive.safariName = "Kanha Safari";
			safariFive.safariType = "Jeep Safari";
			safariFive.safariTimings = "3:00 PM to 5:00 PM";
			safariFive.groupSizeLimit = 6;
			safariFive.isGuideAvailable = true;
				System.out.println();
				System.out.println("safari five details :");
				System.out.println("id of the safari is :"+safariFive.safariId);
				System.out.println("name of the safari : "+safariFive.safariName);
				System.out.println("type of safari : "+safariFive.safariType);
				System.out.println("timings of safari : "+safariFive.safariTimings);
				System.out.println("group size limit of safari is : "+safariFive.groupSizeLimit);
				System.out.println("is guide avaialable? "+safariFive.isGuideAvailable);
				
			ForestSafari safariSix=new ForestSafari();
			safariSix.safariId = 6;
			safariSix.safariName = "Gir Safari";
			safariSix.safariType = "Bus Safari";
			safariSix.safariTimings = "9:00 AM to 11:00 AM";
			safariSix.groupSizeLimit = 15;
			safariSix.isGuideAvailable = true;
				System.out.println();
				System.out.println("safari six details :");
				System.out.println("id of the safari is :"+safariSix.safariId);
				System.out.println("name of the safari : "+safariSix.safariName);
				System.out.println("type of safari : "+safariSix.safariType);
				System.out.println("timings of safari : "+safariSix.safariTimings);
				System.out.println("group size limit of safari is : "+safariSix.groupSizeLimit);
				System.out.println("is guide avaialable? "+safariSix.isGuideAvailable);
			
			ForestSafari safariSeven=new ForestSafari();
			safariSeven.safariId = 7;
			safariSeven.safariName = "Kaziranga Safari";
			safariSeven.safariType = "Elephant Safari";
			safariSeven.safariTimings = "5:30 AM to 7:30 AM";
			safariSeven.groupSizeLimit = 4;
			safariSeven.isGuideAvailable = true;
				System.out.println();
				System.out.println("safari seven details :");
				System.out.println("id of the safari is :"+safariSeven.safariId);
				System.out.println("name of the safari : "+safariSeven.safariName);
				System.out.println("type of safari : "+safariSeven.safariType);
				System.out.println("timings of safari : "+safariSeven.safariTimings);
				System.out.println("group size limit of safari is : "+safariSeven.groupSizeLimit);
				System.out.println("is guide avaialable? "+safariSeven.isGuideAvailable);
			
			ForestSafari safariEight=new ForestSafari();
			safariEight.safariId = 8;
			safariEight.safariName = "Sundarbans Safari";
			safariEight.safariType = "Boat Safari";
			safariEight.safariTimings = "8:00 AM to 10:00 AM";
			safariEight.groupSizeLimit = 10;
			safariEight.isGuideAvailable = false;
				System.out.println();
				System.out.println("safari one details :");
				System.out.println("id of the safari is :"+safariEight.safariId);
				System.out.println("name of the safari : "+safariEight.safariName);
				System.out.println("type of safari : "+safariEight.safariType);
				System.out.println("timings of safari : "+safariEight.safariTimings);
				System.out.println("group size limit of safari is : "+safariEight.groupSizeLimit);
				System.out.println("is guide avaialable? "+safariEight.isGuideAvailable);
			
			
			ForestSafari safariNine=new ForestSafari();
			safariNine.safariId = 9;
			safariNine.safariName = "Mudumalai Safari";
			safariNine.safariType = "Van Safari";
			safariNine.safariTimings = "4:30 PM to 6:30 PM";
			safariNine.groupSizeLimit = 12;
			safariNine.isGuideAvailable = true;
				System.out.println();
				System.out.println("safari nine details :");
				System.out.println("id of the safari is :"+safariNine.safariId);
				System.out.println("name of the safari : "+safariNine.safariName);
				System.out.println("type of safari : "+safariNine.safariType);
				System.out.println("timings of safari : "+safariNine.safariTimings);
				System.out.println("group size limit of safari is : "+safariNine.groupSizeLimit);
				System.out.println("is guide avaialable? "+safariNine.isGuideAvailable);
			
			ForestSafari safariTen=new ForestSafari();
			safariTen.safariId = 10;
			safariTen.safariName = "Tadoba Safari";
			safariTen.safariType = "Gypsy Safari";
			safariTen.safariTimings = "6:00 AM to 8:00 AM";
			safariTen.groupSizeLimit = 6;
			safariTen.isGuideAvailable = true;
				System.out.println();
				System.out.println("safari ten details :");
				System.out.println("id of the safari is :"+safariTen.safariId);
				System.out.println("name of the safari : "+safariTen.safariName);
				System.out.println("type of safari : "+safariTen.safariType);
				System.out.println("timings of safari : "+safariTen.safariTimings);
				System.out.println("group size limit of safari is : "+safariTen.groupSizeLimit);
				System.out.println("is guide avaialable? "+safariTen.isGuideAvailable);
			
			ForestSafari safariEleven=new ForestSafari();
			safariEleven.safariId = 11;
			safariEleven.safariName = "Periyar Safari";
			safariEleven.safariType = "Boat Safari";
			safariEleven.safariTimings = "3:00 PM to 5:00 PM";
			safariEleven.groupSizeLimit = 10;
			safariEleven.isGuideAvailable = false;
				System.out.println();
				System.out.println("safari eleven details :");
				System.out.println("id of the safari is :"+safariEleven.safariId);
				System.out.println("name of the safari : "+safariEleven.safariName);
				System.out.println("type of safari : "+safariEleven.safariType);
				System.out.println("timings of safari : "+safariEleven.safariTimings);
				System.out.println("group size limit of safari is : "+safariEleven.groupSizeLimit);
				System.out.println("is guide avaialable? "+safariEleven.isGuideAvailable);
			
			
			ForestSafari safariTwelve=new ForestSafari();
			safariTwelve.safariId = 12;
			safariTwelve.safariName = "Manas Safari";
			safariTwelve.safariType = "Elephant Safari";
			safariTwelve.safariTimings = "7:00 AM to 9:00 AM";
			safariTwelve.groupSizeLimit = 4;
			safariTwelve.isGuideAvailable = true;
				System.out.println();
				System.out.println("safari twelve details :");
				System.out.println("id of the safari is :"+safariTwelve.safariId);
				System.out.println("name of the safari : "+safariTwelve.safariName);
				System.out.println("type of safari : "+safariTwelve.safariType);
				System.out.println("timings of safari : "+safariTwelve.safariTimings);
				System.out.println("group size limit of safari is : "+safariTwelve.groupSizeLimit);
				System.out.println("is guide avaialable? "+safariTwelve.isGuideAvailable);
			
			ForestSafari safariThirteen=new ForestSafari();
			safariThirteen.safariId = 13;
			safariThirteen.safariName = "Satpura Safari";
			safariThirteen.safariType = "Walking Safari";
			safariThirteen.safariTimings = "6:00 AM to 8:00 AM";
			safariThirteen.groupSizeLimit = 5;
			safariThirteen.isGuideAvailable = true;
				System.out.println();
				System.out.println("safari thirteen details :");
				System.out.println("id of the safari is :"+safariThirteen.safariId);
				System.out.println("name of the safari : "+safariThirteen.safariName);
				System.out.println("type of safari : "+safariThirteen.safariType);
				System.out.println("timings of safari : "+safariThirteen.safariTimings);
				System.out.println("group size limit of safari is : "+safariThirteen.groupSizeLimit);
				System.out.println("is guide avaialable? "+safariThirteen.isGuideAvailable);
			
			ForestSafari safariFourteen=new ForestSafari();
			safariFourteen.safariId = 14;
			safariFourteen.safariName = "Pench Safari";
			safariFourteen.safariType = "Jeep Safari";
			safariFourteen.safariTimings = "4:00 PM to 6:00 PM";
			safariFourteen.groupSizeLimit = 6;
			safariFourteen.isGuideAvailable = true;
				System.out.println();
				System.out.println("safari fourteen details :");
				System.out.println("id of the safari is :"+safariFourteen.safariId);
				System.out.println("name of the safari : "+safariFourteen.safariName);
				System.out.println("type of safari : "+safariFourteen.safariType);
				System.out.println("timings of safari : "+safariFourteen.safariTimings);
				System.out.println("group size limit of safari is : "+safariFourteen.groupSizeLimit);
				System.out.println("is guide avaialable? "+safariFourteen.isGuideAvailable);
			
			ForestSafari safariFifteen=new ForestSafari();
			safariFifteen.safariId = 15;
			safariFifteen.safariName = "Dudhwa Safari";
			safariFifteen.safariType = "Van Safari";
			safariFifteen.safariTimings = "8:00 AM to 10:00 AM";
			safariFifteen.groupSizeLimit = 12;
			safariFifteen.isGuideAvailable = true;
			System.out.println();
			System.out.println("safari fifteen details :");
			System.out.println("id of the safari is :"+safariFifteen.safariId);
			System.out.println("name of the safari : "+safariFifteen.safariName);
			System.out.println("type of safari : "+safariFifteen.safariType);
			System.out.println("timings of safari : "+safariFifteen.safariTimings);
			System.out.println("group size limit of safari is : "+safariFifteen.groupSizeLimit);
			System.out.println("is guide avaialable? "+safariFifteen.isGuideAvailable);
			
			ForestSafari safariSeventeen=new ForestSafari();
			safariSeventeen.safariId = 17;
			safariSeventeen.safariName = "Simlipal Safari";
			safariSeventeen.safariType = "Bus Safari";
			safariSeventeen.safariTimings = "9:00 AM to 11:00 AM";
			safariSeventeen.groupSizeLimit = 15;
			safariSeventeen.isGuideAvailable = false;
				System.out.println();
				System.out.println("safari seventeen details :");
				System.out.println("id of the safari is :"+safariSeventeen.safariId);
				System.out.println("name of the safari : "+safariSeventeen.safariName);
				System.out.println("type of safari : "+safariSeventeen.safariType);
				System.out.println("timings of safari : "+safariSeventeen.safariTimings);
				System.out.println("group size limit of safari is : "+safariSeventeen.groupSizeLimit);
				System.out.println("is guide avaialable? "+safariSeventeen.isGuideAvailable);
			
			ForestSafari safariEighteen=new ForestSafari();
			safariEighteen.safariId = 18;
			safariEighteen.safariName = "Rajaji Safari";
			safariEighteen.safariType = "Canter Safari";
			safariEighteen.safariTimings = "3:00 PM to 5:00 PM";
			safariEighteen.groupSizeLimit = 20;
			safariEighteen.isGuideAvailable = true;
				System.out.println();
				System.out.println("safari eighteen details :");
				System.out.println("id of the safari is :"+safariEighteen.safariId);
				System.out.println("name of the safari : "+safariEighteen.safariName);
				System.out.println("type of safari : "+safariEighteen.safariType);
				System.out.println("timings of safari : "+safariEighteen.safariTimings);
				System.out.println("group size limit of safari is : "+safariEighteen.groupSizeLimit);
				System.out.println("is guide avaialable? "+safariEighteen.isGuideAvailable);
			
			ForestSafari safariNineteen=new ForestSafari();
			safariNineteen.safariId = 19;
			safariNineteen.safariName = "Hemis Safari";
			safariNineteen.safariType = "Hiking Safari";
			safariNineteen.safariTimings = "7:00 AM to 9:00 AM";
			safariNineteen.groupSizeLimit = 5;
			safariNineteen.isGuideAvailable = true;
				System.out.println();
				System.out.println("safari nineteen details :");
				System.out.println("id of the safari is :"+safariNineteen.safariId);
				System.out.println("name of the safari : "+safariNineteen.safariName);
				System.out.println("type of safari : "+safariNineteen.safariType);
				System.out.println("timings of safari : "+safariNineteen.safariTimings);
				System.out.println("group size limit of safari is : "+safariNineteen.groupSizeLimit);
				System.out.println("is guide avaialable? "+safariNineteen.isGuideAvailable);
			
			ForestSafari safariTwenty=new ForestSafari();
			safariTwenty.safariId = 20;
			safariTwenty.safariName = "Bhitarkanika Safari";
			safariTwenty.safariType = "Boat Safari";
			safariTwenty.safariTimings = "10:00 AM to 12:00 PM";
			safariTwenty.groupSizeLimit = 10;
			safariTwenty.isGuideAvailable = false;
			System.out.println();
			System.out.println("safari twenty details :");
			System.out.println("id of the safari is :"+safariTwenty.safariId);
			System.out.println("name of the safari : "+safariTwenty.safariName);
			System.out.println("type of safari : "+safariTwenty.safariType);
			System.out.println("timings of safari : "+safariTwenty.safariTimings);
			System.out.println("group size limit of safari is : "+safariTwenty.groupSizeLimit);
			System.out.println("is guide avaialable? "+safariTwenty.isGuideAvailable);
			
		System.out.println("main ended");
	}

}