class Gym{
	static String gymName;
	static String location;
	static int establishedYear;
	static long contactNumber;
	static String email;
	static String gymType;
	static int noOfTrainers;
	static int noOfMembers;
	static double monthlyMembershipFee;
	static String paymentModes;
	static String gymTimingWeekdays;
	static String gymTimingWeekends;
	static String dressCode;
	static String gymMotto;
	static boolean hasParking;
	static double googleRating;
	static String nearestMetroStation;
	static int noOfTreadMills;
	static int noOfFreeWeightbenches;
	static boolean hasDietCounseling;
	public static void main(String gym[]){
		System.out.println("The name of the gym is "+gymName);
		System.out.println("The gym is located at "+location);
		System.out.println("The contact number of the gym is "+contactNumber);
		System.out.println("The email id of the gym is "+email);
		System.out.println("The gym type is "+gymType);
		System.out.println("The number of trainers in the gym are "+noOfTrainers);
		System.out.println("The number of members in this gym are "+noOfMembers);
		System.out.println("The monthly membership fee of the gym is "+monthlyMembershipFee);
		System.out.println("The payment methods of the gym is "+paymentModes);
		System.out.println("The gym timings on weekdays is "+gymTimingWeekdays);
		System.out.println("The gym timings on weekends is "+gymTimingWeekends);
		System.out.println("The dress code of the gym is "+dressCode);
		System.out.println("The motto of the gym is "+gymMotto);
		System.out.println("does the gym has parking? "+hasParking);
		System.out.println("The google rating of the gym is "+googleRating);
		System.out.println("The nearest metro station of the gym is "+nearestMetroStation);
		System.out.println("The number of treadmills in the gym are "+noOfTreadMills);
		System.out.println("The number of free weight benches in the gym are "+noOfFreeWeightbenches);
		System.out.println("Does the gym has diet counseling? "+hasDietCounseling);
		System.out.println();
	 String gymName="Propel Fitness";
	 String location="Indiranagr, Bengaluru";
	 int establishedYear=2016;
	 long contactNumber=9876543210l;
	 String email="contact@propelfitness.in";
	 String gymType="Unisex";
	 int noOfTrainers=15;
	 int noOfMembers=200;
	 double monthlyMembershipFee=2499.00d;
	 String paymentModes="Cash, Card, UPI, Net Banking";
	 String gymTimingWeekdays="5:00 AM to 11:00 PM";
	 String gymTimingWeekends="6:00 AM to 9:00 PM";
	 String dressCode="Athletic wear and gym shoes";
	 String gymMotto="Push. Power. Propel.";
	 boolean hasParking=true;
	 double googleRating=4.7d;
	 String nearestMetroStation="Jaynagar Metro station";
	 int noOfTreadMills=12;
	 int noOfFreeWeightbenches=10;
	 boolean hasDietCounseling=true;
		System.out.println("After re-initialization");
		System.out.println("The name of the gym is "+gymName);
		System.out.println("The gym is located at "+location);
		System.out.println("The contact number of the gym is "+contactNumber);
		System.out.println("The email id of the gym is "+email);
		System.out.println("The gym type is "+gymType);
		System.out.println("The number of trainers in the gym are "+noOfTrainers);
		System.out.println("The number of members in this gym are "+noOfMembers);
		System.out.println("The monthly membership fee of the gym is "+monthlyMembershipFee);
		System.out.println("The payment methods of the gym is "+paymentModes);
		System.out.println("The gym timings on weekdays is "+gymTimingWeekdays);
		System.out.println("The gym timings on weekends is "+gymTimingWeekends);
		System.out.println("The dress code of the gym is "+dressCode);
		System.out.println("The motto of the gym is "+gymMotto);
		System.out.println("does the gym has parking? "+hasParking);
		System.out.println("The google rating of the gym is "+googleRating);
		System.out.println("The nearest metro station of the gym is "+nearestMetroStation);
		System.out.println("The number of treadmills in the gym are "+noOfTreadMills);
		System.out.println("The number of free weight benches in the gym are "+noOfFreeWeightbenches);
		System.out.println("Does the gym has diet counseling? "+hasDietCounseling);
	
	}
}