class GymEquipmentRunner{

	public static void main(String[] gym){
		System.out.println("main started");
			GymEquipment firstGymEquipment = new GymEquipment();
			firstGymEquipment.equipmentId=1;
			firstGymEquipment.equipmentName="Dumbles";
			firstGymEquipment.equipmentType="Strength";
			firstGymEquipment.equipmentWeight=20;
			firstGymEquipment.equipmentPowerSource="Manual";
			firstGymEquipment.costOfEquipment=5000.00;
			firstGymEquipment.equipmentMaterial="Aluminium";
				System.out.println();
				System.out.println("First Gym equipment Details : ");
				System.out.println("id of the gym equipment is : "+firstGymEquipment.equipmentId);
				System.out.println("name of the gym equipment is : "+firstGymEquipment.equipmentName);
				System.out.println("type of the gym equipment is : "+firstGymEquipment.equipmentType);
				System.out.println("weight of the gym equipment is : "+firstGymEquipment.equipmentWeight+" Kg");
				System.out.println("power source of the gym equipment is  : "+firstGymEquipment.equipmentPowerSource);
				System.out.println("cost of the gym equipment is : "+firstGymEquipment.costOfEquipment);
				System.out.println("material of the equipment is  : "+firstGymEquipment.equipmentMaterial);
				
			GymEquipment secondGymEquipment = new GymEquipment();
			secondGymEquipment.equipmentId=2;
			secondGymEquipment.equipmentName="Treadmill";
			secondGymEquipment.equipmentType="Cardio";
			secondGymEquipment.equipmentWeight=150;
			secondGymEquipment.equipmentPowerSource="Electric";
			secondGymEquipment.costOfEquipment=15000.00;
			secondGymEquipment.equipmentMaterial="Aluminium";
				System.out.println();
				System.out.println("Second Gym equipment Details : ");
				System.out.println("id of the gym equipment is : "+secondGymEquipment.equipmentId);
				System.out.println("name of the gym equipment is : "+secondGymEquipment.equipmentName);
				System.out.println("type of the gym equipment is : "+secondGymEquipment.equipmentType);
				System.out.println("weight of the gym equipment is : "+secondGymEquipment.equipmentWeight+" Kg");
				System.out.println("power source of the gym equipment is  : "+secondGymEquipment.equipmentPowerSource);
				System.out.println("cost of the gym equipment is : "+secondGymEquipment.costOfEquipment);
				System.out.println("material of the equipment is  : "+secondGymEquipment.equipmentMaterial);
			
			GymEquipment thirdGymEquipment = new GymEquipment();
			thirdGymEquipment.equipmentId=3;
			thirdGymEquipment.equipmentName="Kettlebell";
			thirdGymEquipment.equipmentType="Strength/Cardio";
			thirdGymEquipment.equipmentWeight=70;
			thirdGymEquipment.equipmentPowerSource="Manual";
			thirdGymEquipment.costOfEquipment=2000.00;
			thirdGymEquipment.equipmentMaterial="Steel";
				System.out.println();
				System.out.println("Third Gym equipment Details : ");
				System.out.println("id of the gym equipment is : "+thirdGymEquipment.equipmentId);
				System.out.println("name of the gym equipment is : "+thirdGymEquipment.equipmentName);
				System.out.println("type of the gym equipment is : "+thirdGymEquipment.equipmentType);
				System.out.println("weight of the gym equipment is : "+thirdGymEquipment.equipmentWeight+" Kg");
				System.out.println("power source of the gym equipment is  : "+thirdGymEquipment.equipmentPowerSource);
				System.out.println("cost of the gym equipment is : "+thirdGymEquipment.costOfEquipment);
				System.out.println("material of the equipment is  : "+thirdGymEquipment.equipmentMaterial);
				
			GymEquipment fourthGymEquipment = new GymEquipment();
			fourthGymEquipment.equipmentId=4;
			fourthGymEquipment.equipmentName="Stationary Bike";
			fourthGymEquipment.equipmentType="Cardio";
			fourthGymEquipment.equipmentWeight=250;
			fourthGymEquipment.equipmentPowerSource="Battery";
			fourthGymEquipment.costOfEquipment=20000.00;
			fourthGymEquipment.equipmentMaterial="Steel";
				System.out.println();
				System.out.println("fourth Gym equipment Details : ");
				System.out.println("id of the gym equipment is : "+fourthGymEquipment.equipmentId);
				System.out.println("name of the gym equipment is : "+fourthGymEquipment.equipmentName);
				System.out.println("type of the gym equipment is : "+fourthGymEquipment.equipmentType);
				System.out.println("weight of the gym equipment is : "+fourthGymEquipment.equipmentWeight+" Kg");
				System.out.println("power source of the gym equipment is  : "+fourthGymEquipment.equipmentPowerSource);
				System.out.println("cost of the gym equipment is : "+fourthGymEquipment.costOfEquipment);
				System.out.println("material of the equipment is  : "+fourthGymEquipment.equipmentMaterial);
			
			GymEquipment fifthGymEquipment = new GymEquipment();
			fifthGymEquipment.equipmentId=5;
			fifthGymEquipment.equipmentName="Leg Press Machine";
			fifthGymEquipment.equipmentType="Strength";
			fifthGymEquipment.equipmentWeight=275;
			fifthGymEquipment.equipmentPowerSource="Manual";
			fifthGymEquipment.costOfEquipment=25000.00;
			fifthGymEquipment.equipmentMaterial="Aluminium";
				System.out.println();
				System.out.println("fifth Gym equipment Details : ");
				System.out.println("id of the gym equipment is : "+fifthGymEquipment.equipmentId);
				System.out.println("name of the gym equipment is : "+fifthGymEquipment.equipmentName);
				System.out.println("type of the gym equipment is : "+fifthGymEquipment.equipmentType);
				System.out.println("weight of the gym equipment is : "+fifthGymEquipment.equipmentWeight+" Kg");
				System.out.println("power source of the gym equipment is  : "+fifthGymEquipment.equipmentPowerSource);
				System.out.println("cost of the gym equipment is : "+fifthGymEquipment.costOfEquipment);
				System.out.println("material of the equipment is  : "+fifthGymEquipment.equipmentMaterial);
				
			GymEquipment sixthGymEquipment = new GymEquipment();
			sixthGymEquipment.equipmentId=6;
			sixthGymEquipment.equipmentName="Pull-up Bar";
			sixthGymEquipment.equipmentType="Strength";
			sixthGymEquipment.equipmentWeight=50;
			sixthGymEquipment.equipmentPowerSource="Manual";
			sixthGymEquipment.costOfEquipment=7000.00;
			sixthGymEquipment.equipmentMaterial="Steel";
				System.out.println();
				System.out.println("sixth Gym equipment Details : ");
				System.out.println("id of the gym equipment is : "+sixthGymEquipment.equipmentId);
				System.out.println("name of the gym equipment is : "+sixthGymEquipment.equipmentName);
				System.out.println("type of the gym equipment is : "+sixthGymEquipment.equipmentType);
				System.out.println("weight of the gym equipment is : "+sixthGymEquipment.equipmentWeight+" Kg");
				System.out.println("power source of the gym equipment is  : "+sixthGymEquipment.equipmentPowerSource);
				System.out.println("cost of the gym equipment is : "+sixthGymEquipment.costOfEquipment);
				System.out.println("material of the equipment is  : "+sixthGymEquipment.equipmentMaterial);
				
			GymEquipment sevenGymEquipment = new GymEquipment();
			sevenGymEquipment.equipmentId=7;
			sevenGymEquipment.equipmentName="Resistance Bands";
			sevenGymEquipment.equipmentType="Flexibility";
			sevenGymEquipment.equipmentWeight=5;
			sevenGymEquipment.equipmentPowerSource="Manual";
			sevenGymEquipment.costOfEquipment=1000.00;
			sevenGymEquipment.equipmentMaterial="Rubber";
				System.out.println();
				System.out.println("seventh Gym equipment Details : ");
				System.out.println("id of the gym equipment is : "+sevenGymEquipment.equipmentId);
				System.out.println("name of the gym equipment is : "+sevenGymEquipment.equipmentName);
				System.out.println("type of the gym equipment is : "+sevenGymEquipment.equipmentType);
				System.out.println("weight of the gym equipment is : "+sevenGymEquipment.equipmentWeight+" Kg");
				System.out.println("power source of the gym equipment is  : "+sevenGymEquipment.equipmentPowerSource);
				System.out.println("cost of the gym equipment is : "+sevenGymEquipment.costOfEquipment);
				System.out.println("material of the equipment is  : "+sevenGymEquipment.equipmentMaterial);
				
			GymEquipment eighthGymEquipment = new GymEquipment();
			eighthGymEquipment.equipmentId=8;
			eighthGymEquipment.equipmentName="Foam Roller";
			eighthGymEquipment.equipmentType="Recovery";
			eighthGymEquipment.equipmentWeight=7;
			eighthGymEquipment.equipmentPowerSource="Manual";
			eighthGymEquipment.costOfEquipment=1500.00;
			eighthGymEquipment.equipmentMaterial="Steel";
				System.out.println();
				System.out.println("Eighth  Gym equipment Details : ");
				System.out.println("id of the gym equipment is : "+eighthGymEquipment.equipmentId);
				System.out.println("name of the gym equipment is : "+eighthGymEquipment.equipmentName);
				System.out.println("type of the gym equipment is : "+eighthGymEquipment.equipmentType);
				System.out.println("weight of the gym equipment is : "+eighthGymEquipment.equipmentWeight+" Kg");
				System.out.println("power source of the gym equipment is  : "+eighthGymEquipment.equipmentPowerSource);
				System.out.println("cost of the gym equipment is : "+eighthGymEquipment.costOfEquipment);
				System.out.println("material of the equipment is  : "+eighthGymEquipment.equipmentMaterial);
				
			GymEquipment ninthGymEquipment = new GymEquipment();
			ninthGymEquipment.equipmentId=9;
			ninthGymEquipment.equipmentName="Stair Climber";
			ninthGymEquipment.equipmentType="Cardio";
			ninthGymEquipment.equipmentWeight=15;
			ninthGymEquipment.equipmentPowerSource="Manual";
			ninthGymEquipment.costOfEquipment=5500.00;
			ninthGymEquipment.equipmentMaterial="Aluminium";
				System.out.println();
				System.out.println("Ninth  Gym equipment Details : ");
				System.out.println("id of the gym equipment is : "+ninthGymEquipment.equipmentId);
				System.out.println("name of the gym equipment is : "+ninthGymEquipment.equipmentName);
				System.out.println("type of the gym equipment is : "+ninthGymEquipment.equipmentType);
				System.out.println("weight of the gym equipment is : "+ninthGymEquipment.equipmentWeight+" Kg");
				System.out.println("power source of the gym equipment is  : "+ninthGymEquipment.equipmentPowerSource);
				System.out.println("cost of the gym equipment is : "+ninthGymEquipment.costOfEquipment);
				System.out.println("material of the equipment is  : "+ninthGymEquipment.equipmentMaterial);
				
			GymEquipment tenthGymEquipment = new GymEquipment();
			tenthGymEquipment.equipmentId=10;
			tenthGymEquipment.equipmentName="Barbell";
			tenthGymEquipment.equipmentType="Strength";
			tenthGymEquipment.equipmentWeight=350;
			tenthGymEquipment.equipmentPowerSource="Manual";
			tenthGymEquipment.costOfEquipment=10500.00;
			tenthGymEquipment.equipmentMaterial="Aluminium";
				System.out.println();
				System.out.println("tenth Gym equipment Details : ");
				System.out.println("id of the gym equipment is : "+tenthGymEquipment.equipmentId);
				System.out.println("name of the gym equipment is : "+tenthGymEquipment.equipmentName);
				System.out.println("type of the gym equipment is : "+tenthGymEquipment.equipmentType);
				System.out.println("weight of the gym equipment is : "+tenthGymEquipment.equipmentWeight+" Kg");
				System.out.println("power source of the gym equipment is  : "+tenthGymEquipment.equipmentPowerSource);
				System.out.println("cost of the gym equipment is : "+tenthGymEquipment.costOfEquipment);
				System.out.println("material of the equipment is  : "+tenthGymEquipment.equipmentMaterial);
				
			GymEquipment eleventhGymEquipment = new GymEquipment();
			eleventhGymEquipment.equipmentId=11;
			eleventhGymEquipment.equipmentName="Smith Machine";
			eleventhGymEquipment.equipmentType="Strength";
			eleventhGymEquipment.equipmentWeight=250;
			eleventhGymEquipment.equipmentPowerSource="Electric";
			eleventhGymEquipment.costOfEquipment=12500.00;
			eleventhGymEquipment.equipmentMaterial="Aluminium";
				System.out.println();
				System.out.println("eleventh Gym equipment Details : ");
				System.out.println("id of the gym equipment is : "+eleventhGymEquipment.equipmentId);
				System.out.println("name of the gym equipment is : "+eleventhGymEquipment.equipmentName);
				System.out.println("type of the gym equipment is : "+eleventhGymEquipment.equipmentType);
				System.out.println("weight of the gym equipment is : "+eleventhGymEquipment.equipmentWeight+" Kg");
				System.out.println("power source of the gym equipment is  : "+eleventhGymEquipment.equipmentPowerSource);
				System.out.println("cost of the gym equipment is : "+eleventhGymEquipment.costOfEquipment);
				System.out.println("material of the equipment is  : "+eleventhGymEquipment.equipmentMaterial);
				
			GymEquipment twelvethGymEquipment = new GymEquipment();
			twelvethGymEquipment.equipmentId=12;
			twelvethGymEquipment.equipmentName="Battle Ropes";
			twelvethGymEquipment.equipmentType="Cardio/Strength";
			twelvethGymEquipment.equipmentWeight=75;
			twelvethGymEquipment.equipmentPowerSource="Manual";
			twelvethGymEquipment.costOfEquipment=9500.00;
			twelvethGymEquipment.equipmentMaterial="Aluminium";
				System.out.println();
				System.out.println("twelveth Gym equipment Details : ");
				System.out.println("id of the gym equipment is : "+twelvethGymEquipment.equipmentId);
				System.out.println("name of the gym equipment is : "+twelvethGymEquipment.equipmentName);
				System.out.println("type of the gym equipment is : "+twelvethGymEquipment.equipmentType);
				System.out.println("weight of the gym equipment is : "+twelvethGymEquipment.equipmentWeight+" Kg");
				System.out.println("power source of the gym equipment is  : "+twelvethGymEquipment.equipmentPowerSource);
				System.out.println("cost of the gym equipment is : "+twelvethGymEquipment.costOfEquipment);
				System.out.println("material of the equipment is  : "+twelvethGymEquipment.equipmentMaterial);
				
			GymEquipment thirteenthGymEquipment = new GymEquipment();
			thirteenthGymEquipment.equipmentId=13;
			thirteenthGymEquipment.equipmentName="Yoga Mat";
			thirteenthGymEquipment.equipmentType="Flexibility";
			thirteenthGymEquipment.equipmentWeight=750;
			thirteenthGymEquipment.equipmentPowerSource="Manual";
			thirteenthGymEquipment.costOfEquipment=1400.00;
			thirteenthGymEquipment.equipmentMaterial="Rubber";
				System.out.println();
				System.out.println("thirteenth Gym equipment Details : ");
				System.out.println("id of the gym equipment is : "+thirteenthGymEquipment.equipmentId);
				System.out.println("name of the gym equipment is : "+thirteenthGymEquipment.equipmentName);
				System.out.println("type of the gym equipment is : "+thirteenthGymEquipment.equipmentType);
				System.out.println("weight of the gym equipment is : "+thirteenthGymEquipment.equipmentWeight+" g");
				System.out.println("power source of the gym equipment is  : "+thirteenthGymEquipment.equipmentPowerSource);
				System.out.println("cost of the gym equipment is : "+thirteenthGymEquipment.costOfEquipment);
				System.out.println("material of the equipment is  : "+thirteenthGymEquipment.equipmentMaterial);
				
			GymEquipment fourteenthGymEquipment = new GymEquipment();
			fourteenthGymEquipment.equipmentId=14;
			fourteenthGymEquipment.equipmentName="Ab Wheel";
			fourteenthGymEquipment.equipmentType="Core Training";
			fourteenthGymEquipment.equipmentWeight=500;
			fourteenthGymEquipment.equipmentPowerSource="Manual";
			fourteenthGymEquipment.costOfEquipment=1500.00;
			fourteenthGymEquipment.equipmentMaterial="Aluminium";
				System.out.println();
				System.out.println("fourteenth Gym equipment Details : ");
				System.out.println("id of the gym equipment is : "+fourteenthGymEquipment.equipmentId);
				System.out.println("name of the gym equipment is : "+fourteenthGymEquipment.equipmentName);
				System.out.println("type of the gym equipment is : "+fourteenthGymEquipment.equipmentType);
				System.out.println("weight of the gym equipment is : "+fourteenthGymEquipment.equipmentWeight+" g");
				System.out.println("power source of the gym equipment is  : "+fourteenthGymEquipment.equipmentPowerSource);
				System.out.println("cost of the gym equipment is : "+fourteenthGymEquipment.costOfEquipment);
				System.out.println("material of the equipment is  : "+fourteenthGymEquipment.equipmentMaterial);
				
			GymEquipment fifteenthGymEquipment = new GymEquipment();
			fifteenthGymEquipment.equipmentId=15;
			fifteenthGymEquipment.equipmentName="Cable Crossover Machine";
			fifteenthGymEquipment.equipmentType="Strength";
			fifteenthGymEquipment.equipmentWeight=350;
			fifteenthGymEquipment.equipmentPowerSource="Manual";
			fifteenthGymEquipment.costOfEquipment=3500.00;
			fifteenthGymEquipment.equipmentMaterial="Steel";
				System.out.println();
				System.out.println("fifteenth Gym equipment Details : ");
				System.out.println("id of the gym equipment is : "+fifteenthGymEquipment.equipmentId);
				System.out.println("name of the gym equipment is : "+fifteenthGymEquipment.equipmentName);
				System.out.println("type of the gym equipment is : "+fifteenthGymEquipment.equipmentType);
				System.out.println("weight of the gym equipment is : "+fifteenthGymEquipment.equipmentWeight+" g");
				System.out.println("power source of the gym equipment is  : "+fifteenthGymEquipment.equipmentPowerSource);
				System.out.println("cost of the gym equipment is : "+fifteenthGymEquipment.costOfEquipment);
				System.out.println("material of the equipment is  : "+fifteenthGymEquipment.equipmentMaterial);
				
			GymEquipment sixteenthGymEquipment = new GymEquipment();
			sixteenthGymEquipment.equipmentId=16;
			sixteenthGymEquipment.equipmentName="T Bar";
			sixteenthGymEquipment.equipmentType="Strength";
			sixteenthGymEquipment.equipmentWeight=20;
			sixteenthGymEquipment.equipmentPowerSource="Manual";
			sixteenthGymEquipment.costOfEquipment=6500.00;
			sixteenthGymEquipment.equipmentMaterial="Steel";
				System.out.println();
				System.out.println("sixteenth Gym equipment Details : ");
				System.out.println("id of the gym equipment is : "+sixteenthGymEquipment.equipmentId);
				System.out.println("name of the gym equipment is : "+sixteenthGymEquipment.equipmentName);
				System.out.println("type of the gym equipment is : "+sixteenthGymEquipment.equipmentType);
				System.out.println("weight of the gym equipment is : "+sixteenthGymEquipment.equipmentWeight+" g");
				System.out.println("power source of the gym equipment is  : "+sixteenthGymEquipment.equipmentPowerSource);
				System.out.println("cost of the gym equipment is : "+sixteenthGymEquipment.costOfEquipment);
				System.out.println("material of the equipment is  : "+sixteenthGymEquipment.equipmentMaterial);
			
			GymEquipment seventeenthGymEquipment = new GymEquipment();
			seventeenthGymEquipment.equipmentId=17;
			seventeenthGymEquipment.equipmentName="Peck Deck Machine";
			seventeenthGymEquipment.equipmentType="Cardio";
			seventeenthGymEquipment.equipmentWeight=450;
			seventeenthGymEquipment.equipmentPowerSource="Manual";
			seventeenthGymEquipment.costOfEquipment=40000.00;
			seventeenthGymEquipment.equipmentMaterial="Aluminium";
				System.out.println();
				System.out.println("seventeenth Gym equipment Details : ");
				System.out.println("id of the gym equipment is : "+seventeenthGymEquipment.equipmentId);
				System.out.println("name of the gym equipment is : "+seventeenthGymEquipment.equipmentName);
				System.out.println("type of the gym equipment is : "+seventeenthGymEquipment.equipmentType);
				System.out.println("weight of the gym equipment is : "+seventeenthGymEquipment.equipmentWeight+" g");
				System.out.println("power source of the gym equipment is  : "+seventeenthGymEquipment.equipmentPowerSource);
				System.out.println("cost of the gym equipment is : "+seventeenthGymEquipment.costOfEquipment);
				System.out.println("material of the equipment is  : "+seventeenthGymEquipment.equipmentMaterial);
				
			GymEquipment eighteenthGymEquipment = new GymEquipment();
			eighteenthGymEquipment.equipmentId=18;
			eighteenthGymEquipment.equipmentName="Leg Curl Machine";
			eighteenthGymEquipment.equipmentType="Cardio";
			eighteenthGymEquipment.equipmentWeight=120;
			eighteenthGymEquipment.equipmentPowerSource="Manual";
			eighteenthGymEquipment.costOfEquipment=11000.00;
			eighteenthGymEquipment.equipmentMaterial="Steel";
				System.out.println();
				System.out.println("eighteenth Gym equipment Details : ");
				System.out.println("id of the gym equipment is : "+eighteenthGymEquipment.equipmentId);
				System.out.println("name of the gym equipment is : "+eighteenthGymEquipment.equipmentName);
				System.out.println("type of the gym equipment is : "+eighteenthGymEquipment.equipmentType);
				System.out.println("weight of the gym equipment is : "+eighteenthGymEquipment.equipmentWeight+" g");
				System.out.println("power source of the gym equipment is  : "+eighteenthGymEquipment.equipmentPowerSource);
				System.out.println("cost of the gym equipment is : "+eighteenthGymEquipment.costOfEquipment);
				System.out.println("material of the equipment is  : "+eighteenthGymEquipment.equipmentMaterial);
				
			GymEquipment nineteenthGymEquipment = new GymEquipment();
			nineteenthGymEquipment.equipmentId=19;
			nineteenthGymEquipment.equipmentName="Hammer Strength Machine";
			nineteenthGymEquipment.equipmentType="Strength";
			nineteenthGymEquipment.equipmentWeight=150;
			nineteenthGymEquipment.equipmentPowerSource="Manual";
			nineteenthGymEquipment.costOfEquipment=21000.00;
			nineteenthGymEquipment.equipmentMaterial="Aluminium";
				System.out.println();
				System.out.println("nineteenth Gym equipment Details : ");
				System.out.println("id of the gym equipment is : "+nineteenthGymEquipment.equipmentId);
				System.out.println("name of the gym equipment is : "+nineteenthGymEquipment.equipmentName);
				System.out.println("type of the gym equipment is : "+nineteenthGymEquipment.equipmentType);
				System.out.println("weight of the gym equipment is : "+nineteenthGymEquipment.equipmentWeight+" g");
				System.out.println("power source of the gym equipment is  : "+nineteenthGymEquipment.equipmentPowerSource);
				System.out.println("cost of the gym equipment is : "+nineteenthGymEquipment.costOfEquipment);
				System.out.println("material of the equipment is  : "+nineteenthGymEquipment.equipmentMaterial);
				
			GymEquipment twentiethGymEquipment = new GymEquipment();
			twentiethGymEquipment.equipmentId=20;
			twentiethGymEquipment.equipmentName="Lat Pulldown Machine";
			twentiethGymEquipment.equipmentType="Strength";
			twentiethGymEquipment.equipmentWeight=250;
			twentiethGymEquipment.equipmentPowerSource="Manual";
			twentiethGymEquipment.costOfEquipment=25000.00;
			twentiethGymEquipment.equipmentMaterial="Aluminium";
				System.out.println();
				System.out.println("twentieth Gym equipment Details : ");
				System.out.println("id of the gym equipment is : "+twentiethGymEquipment.equipmentId);
				System.out.println("name of the gym equipment is : "+twentiethGymEquipment.equipmentName);
				System.out.println("type of the gym equipment is : "+twentiethGymEquipment.equipmentType);
				System.out.println("weight of the gym equipment is : "+twentiethGymEquipment.equipmentWeight+" g");
				System.out.println("power source of the gym equipment is  : "+twentiethGymEquipment.equipmentPowerSource);
				System.out.println("cost of the gym equipment is : "+twentiethGymEquipment.costOfEquipment);
				System.out.println("material of the equipment is  : "+twentiethGymEquipment.equipmentMaterial);
				System.out.println();
		System.out.println("main ended");
	}
}