class HairClipRunner{

	public static void main(String[] clip){
	
		System.out.println("main started");
			HairClip hairClipOne = new HairClip();
			hairClipOne.hairClipId=1;
			hairClipOne.hairClipColor="Blue";
			hairClipOne.hairClipMaterial="Plastic";
			hairClipOne.hairClipType="Jaw";
			hairClipOne.hairClipPrice=50.0;
			hairClipOne.hairClipSize="Large";
				System.out.println();
				System.out.println("HairClip one details : ");
				System.out.println("id of the hair clip is : "+hairClipOne.hairClipId);
				System.out.println("color of hair clip is : "+hairClipOne.hairClipColor);
				System.out.println("material of hair clip is : "+hairClipOne.hairClipMaterial);
				System.out.println("type of hair clip is : "+hairClipOne.hairClipType);
				System.out.println("price of the hair clip is : "+hairClipOne.hairClipPrice);
				System.out.println("size of the hair clip is : "+hairClipOne.hairClipSize);
				
			HairClip hairClipTwo = new HairClip();
			hairClipTwo.hairClipId=2;
			hairClipTwo.hairClipColor="Black";
			hairClipTwo.hairClipMaterial="Plastic";
			hairClipTwo.hairClipType="Jaw";
			hairClipTwo.hairClipPrice=25.0;
			hairClipTwo.hairClipSize="Medium";
				System.out.println();
				System.out.println("HairClip two details : ");
				System.out.println("id of the hair clip is : "+hairClipTwo.hairClipId);
				System.out.println("color of hair clip is : "+hairClipTwo.hairClipColor);
				System.out.println("material of hair clip is : "+hairClipTwo.hairClipMaterial);
				System.out.println("type of hair clip is : "+hairClipTwo.hairClipType);
				System.out.println("price of the hair clip is : "+hairClipTwo.hairClipPrice);
				System.out.println("size of the hair clip is : "+hairClipTwo.hairClipSize);
				
			HairClip hairClipThree = new HairClip();
			hairClipThree.hairClipId=3;
			hairClipThree.hairClipColor="Pink";
			hairClipThree.hairClipMaterial="Plastic";
			hairClipThree.hairClipType="Jaw";
			hairClipThree.hairClipPrice=15.0;
			hairClipThree.hairClipSize="Small";
				System.out.println();
				System.out.println("HairClip three details : ");
				System.out.println("id of the hair clip is : "+hairClipThree.hairClipId);
				System.out.println("color of hair clip is : "+hairClipThree.hairClipColor);
				System.out.println("material of hair clip is : "+hairClipThree.hairClipMaterial);
				System.out.println("type of hair clip is : "+hairClipThree.hairClipType);
				System.out.println("price of the hair clip is : "+hairClipThree.hairClipPrice);
				System.out.println("size of the hair clip is : "+hairClipThree.hairClipSize);
			
			HairClip hairClipFour = new HairClip();
			hairClipFour.hairClipId=4;
			hairClipFour.hairClipColor="White";
			hairClipFour.hairClipMaterial="Acrclic";
			hairClipFour.hairClipType="Clasp";
			hairClipFour.hairClipPrice=55.0;
			hairClipFour.hairClipSize="Large";
				System.out.println();
				System.out.println("HairClip four details : ");
				System.out.println("id of the hair clip is : "+hairClipFour.hairClipId);
				System.out.println("color of hair clip is : "+hairClipFour.hairClipColor);
				System.out.println("material of hair clip is : "+hairClipFour.hairClipMaterial);
				System.out.println("type of hair clip is : "+hairClipFour.hairClipType);
				System.out.println("price of the hair clip is : "+hairClipFour.hairClipPrice);
				System.out.println("size of the hair clip is : "+hairClipFour.hairClipSize);
				
			HairClip hairClipFive = new HairClip();
			hairClipFive.hairClipId=5;
			hairClipFive.hairClipColor="Peach";
			hairClipFive.hairClipMaterial="Acrclic";
			hairClipFive.hairClipType="Clasp";
			hairClipFive.hairClipPrice=35.0;
			hairClipFive.hairClipSize="Medium";
				System.out.println();
				System.out.println("HairClip five details : ");
				System.out.println("id of the hair clip is : "+hairClipFive.hairClipId);
				System.out.println("color of hair clip is : "+hairClipFive.hairClipColor);
				System.out.println("material of hair clip is : "+hairClipFive.hairClipMaterial);
				System.out.println("type of hair clip is : "+hairClipFive.hairClipType);
				System.out.println("price of the hair clip is : "+hairClipFive.hairClipPrice);
				System.out.println("size of the hair clip is : "+hairClipFive.hairClipSize);
				
			HairClip hairClipSix = new HairClip();
			hairClipSix.hairClipId=6;
			hairClipSix.hairClipColor="Brown";
			hairClipSix.hairClipMaterial="Acrclic";
			hairClipSix.hairClipType="Clasp";
			hairClipSix.hairClipPrice=15.0;
			hairClipSix.hairClipSize="Small";
				System.out.println();
				System.out.println("HairClip six details : ");
				System.out.println("id of the hair clip is : "+hairClipSix.hairClipId);
				System.out.println("color of hair clip is : "+hairClipSix.hairClipColor);
				System.out.println("material of hair clip is : "+hairClipSix.hairClipMaterial);
				System.out.println("type of hair clip is : "+hairClipSix.hairClipType);
				System.out.println("price of the hair clip is : "+hairClipSix.hairClipPrice);
				System.out.println("size of the hair clip is : "+hairClipSix.hairClipSize);
				
			HairClip hairClipSeven = new HairClip();
			hairClipSeven.hairClipId=7;
			hairClipSeven.hairClipColor="Beige";
			hairClipSeven.hairClipMaterial="Plastic";
			hairClipSeven.hairClipType="Alligator";
			hairClipSeven.hairClipPrice=20.0;
			hairClipSeven.hairClipSize="Medium";
				System.out.println();
				System.out.println("HairClip seven details : ");
				System.out.println("id of the hair clip is : "+hairClipSeven.hairClipId);
				System.out.println("color of hair clip is : "+hairClipSeven.hairClipColor);
				System.out.println("material of hair clip is : "+hairClipSeven.hairClipMaterial);
				System.out.println("type of hair clip is : "+hairClipSeven.hairClipType);
				System.out.println("price of the hair clip is : "+hairClipSeven.hairClipPrice);
				System.out.println("size of the hair clip is : "+hairClipSeven.hairClipSize);
				
			HairClip hairClipEight = new HairClip();
			hairClipEight.hairClipId=8;
			hairClipEight.hairClipColor="Red";
			hairClipEight.hairClipMaterial="Plastic";
			hairClipEight.hairClipType="Alligator";
			hairClipEight.hairClipPrice=10.0;
			hairClipEight.hairClipSize="Small";
				System.out.println();
				System.out.println("HairClip eight details : ");
				System.out.println("id of the hair clip is : "+hairClipEight.hairClipId);
				System.out.println("color of hair clip is : "+hairClipEight.hairClipColor);
				System.out.println("material of hair clip is : "+hairClipEight.hairClipMaterial);
				System.out.println("type of hair clip is : "+hairClipEight.hairClipType);
				System.out.println("price of the hair clip is : "+hairClipEight.hairClipPrice);
				System.out.println("size of the hair clip is : "+hairClipEight.hairClipSize);
				
			HairClip hairClipNine = new HairClip();
			hairClipNine.hairClipId=9;
			hairClipNine.hairClipColor="Purple";
			hairClipNine.hairClipMaterial="Plastic";
			hairClipNine.hairClipType="Alligator";
			hairClipNine.hairClipPrice=30.0;
			hairClipNine.hairClipSize="Large";
				System.out.println();
				System.out.println("HairClip nine details : ");
				System.out.println("id of the hair clip is : "+hairClipNine.hairClipId);
				System.out.println("color of hair clip is : "+hairClipNine.hairClipColor);
				System.out.println("material of hair clip is : "+hairClipNine.hairClipMaterial);
				System.out.println("type of hair clip is : "+hairClipNine.hairClipType);
				System.out.println("price of the hair clip is : "+hairClipNine.hairClipPrice);
				System.out.println("size of the hair clip is : "+hairClipNine.hairClipSize);
				
			HairClip hairClipTen = new HairClip();
			hairClipTen.hairClipId=10;
			hairClipTen.hairClipColor="yellow";
			hairClipTen.hairClipMaterial="Acrylic";
			hairClipTen.hairClipType="French Clip";
			hairClipTen.hairClipPrice=70.0;
			hairClipTen.hairClipSize="Large";
				System.out.println();
				System.out.println("HairClip ten details : ");
				System.out.println("id of the hair clip is : "+hairClipTen.hairClipId);
				System.out.println("color of hair clip is : "+hairClipTen.hairClipColor);
				System.out.println("material of hair clip is : "+hairClipTen.hairClipMaterial);
				System.out.println("type of hair clip is : "+hairClipTen.hairClipType);
				System.out.println("price of the hair clip is : "+hairClipTen.hairClipPrice);
				System.out.println("size of the hair clip is : "+hairClipTen.hairClipSize);
				
			HairClip hairClipEleven = new HairClip();
			hairClipEleven.hairClipId=11;
			hairClipEleven.hairClipColor="Grey";
			hairClipEleven.hairClipMaterial="Acrylic";
			hairClipEleven.hairClipType="French Clip";
			hairClipEleven.hairClipPrice=35.0;
			hairClipEleven.hairClipSize="Medium";
				System.out.println();
				System.out.println("HairClip eleven details : ");
				System.out.println("id of the hair clip is : "+hairClipEleven.hairClipId);
				System.out.println("color of hair clip is : "+hairClipEleven.hairClipColor);
				System.out.println("material of hair clip is : "+hairClipEleven.hairClipMaterial);
				System.out.println("type of hair clip is : "+hairClipEleven.hairClipType);
				System.out.println("price of the hair clip is : "+hairClipEleven.hairClipPrice);
				System.out.println("size of the hair clip is : "+hairClipEleven.hairClipSize);
				
			HairClip hairClipTwelve = new HairClip();
			hairClipTwelve.hairClipId=12;
			hairClipTwelve.hairClipColor="olive green";
			hairClipTwelve.hairClipMaterial="Acrylic";
			hairClipTwelve.hairClipType="French Clip";
			hairClipTwelve.hairClipPrice=15.0;
			hairClipTwelve.hairClipSize="Small";
				System.out.println();
				System.out.println("HairClip twelve details : ");
				System.out.println("id of the hair clip is : "+hairClipTwelve.hairClipId);
				System.out.println("color of hair clip is : "+hairClipTwelve.hairClipColor);
				System.out.println("material of hair clip is : "+hairClipTwelve.hairClipMaterial);
				System.out.println("type of hair clip is : "+hairClipTwelve.hairClipType);
				System.out.println("price of the hair clip is : "+hairClipTwelve.hairClipPrice);
				System.out.println("size of the hair clip is : "+hairClipTwelve.hairClipSize);
				
			HairClip hairClipThirteen = new HairClip();
			hairClipThirteen.hairClipId=13;
			hairClipThirteen.hairClipColor="Black";
			hairClipThirteen.hairClipMaterial="Metal";
			hairClipThirteen.hairClipType="Tic Tac Clip";
			hairClipThirteen.hairClipPrice=10.0;
			hairClipThirteen.hairClipSize="Small";
				System.out.println();
				System.out.println("HairClip thirteen details : ");
				System.out.println("id of the hair clip is : "+hairClipThirteen.hairClipId);
				System.out.println("color of hair clip is : "+hairClipThirteen.hairClipColor);
				System.out.println("material of hair clip is : "+hairClipThirteen.hairClipMaterial);
				System.out.println("type of hair clip is : "+hairClipThirteen.hairClipType);
				System.out.println("price of the hair clip is : "+hairClipThirteen.hairClipPrice);
				System.out.println("size of the hair clip is : "+hairClipThirteen.hairClipSize);
				
			HairClip hairClipFourteen = new HairClip();
			hairClipFourteen.hairClipId=14;
			hairClipFourteen.hairClipColor="Black";
			hairClipFourteen.hairClipMaterial="Metal";
			hairClipFourteen.hairClipType="Tic Tac Clip";
			hairClipFourteen.hairClipPrice=15.0;
			hairClipFourteen.hairClipSize="Medium";
				System.out.println();
				System.out.println("HairClip fourteen details : ");
				System.out.println("id of the hair clip is : "+hairClipFourteen.hairClipId);
				System.out.println("color of hair clip is : "+hairClipFourteen.hairClipColor);
				System.out.println("material of hair clip is : "+hairClipFourteen.hairClipMaterial);
				System.out.println("type of hair clip is : "+hairClipFourteen.hairClipType);
				System.out.println("price of the hair clip is : "+hairClipFourteen.hairClipPrice);
				System.out.println("size of the hair clip is : "+hairClipFourteen.hairClipSize);
			
			HairClip hairClipFifteen = new HairClip();
			hairClipFifteen.hairClipId=15;
			hairClipFifteen.hairClipColor="Black";
			hairClipFifteen.hairClipMaterial="Metal";
			hairClipFifteen.hairClipType="Tic Tac Clip";
			hairClipFifteen.hairClipPrice=25.0;
			hairClipFifteen.hairClipSize="Large";
				System.out.println();
				System.out.println("HairClip fifteen details : ");
				System.out.println("id of the hair clip is : "+hairClipFifteen.hairClipId);
				System.out.println("color of hair clip is : "+hairClipFifteen.hairClipColor);
				System.out.println("material of hair clip is : "+hairClipFifteen.hairClipMaterial);
				System.out.println("type of hair clip is : "+hairClipFifteen.hairClipType);
				System.out.println("price of the hair clip is : "+hairClipFifteen.hairClipPrice);
				System.out.println("size of the hair clip is : "+hairClipFifteen.hairClipSize);
				
			HairClip hairClipSixteen = new HairClip();
			hairClipSixteen.hairClipId=16;
			hairClipSixteen.hairClipColor="Sky Blue";
			hairClipSixteen.hairClipMaterial="Acrylic";
			hairClipSixteen.hairClipType=" Clutch Clip";
			hairClipSixteen.hairClipPrice=15.0;
			hairClipSixteen.hairClipSize="Small";
				System.out.println();
				System.out.println("HairClip sixteen details : ");
				System.out.println("id of the hair clip is : "+hairClipSixteen.hairClipId);
				System.out.println("color of hair clip is : "+hairClipSixteen.hairClipColor);
				System.out.println("material of hair clip is : "+hairClipSixteen.hairClipMaterial);
				System.out.println("type of hair clip is : "+hairClipSixteen.hairClipType);
				System.out.println("price of the hair clip is : "+hairClipSixteen.hairClipPrice);
				System.out.println("size of the hair clip is : "+hairClipSixteen.hairClipSize);
				
			HairClip hairClipSeventeen = new HairClip();
			hairClipSeventeen.hairClipId=17;
			hairClipSeventeen.hairClipColor="Turquoise";
			hairClipSeventeen.hairClipMaterial="Acrylic";
			hairClipSeventeen.hairClipType=" Clutch Clip";
			hairClipSeventeen.hairClipPrice=25.0;
			hairClipSeventeen.hairClipSize="Medium";
				System.out.println();
				System.out.println("HairClip seventeen details : ");
				System.out.println("id of the hair clip is : "+hairClipSeventeen.hairClipId);
				System.out.println("color of hair clip is : "+hairClipSeventeen.hairClipColor);
				System.out.println("material of hair clip is : "+hairClipSeventeen.hairClipMaterial);
				System.out.println("type of hair clip is : "+hairClipSeventeen.hairClipType);
				System.out.println("price of the hair clip is : "+hairClipSeventeen.hairClipPrice);
				System.out.println("size of the hair clip is : "+hairClipSeventeen.hairClipSize);
				
			HairClip hairClipEighteen = new HairClip();
			hairClipEighteen.hairClipId=18;
			hairClipEighteen.hairClipColor="Mearun";
			hairClipEighteen.hairClipMaterial="Acrylic";
			hairClipEighteen.hairClipType=" Arcylic Clip";
			hairClipEighteen.hairClipPrice=45.0;
			hairClipEighteen.hairClipSize="Large";
				System.out.println();
				System.out.println("HairClip eighteen details : ");
				System.out.println("id of the hair clip is : "+hairClipEighteen.hairClipId);
				System.out.println("color of hair clip is : "+hairClipEighteen.hairClipColor);
				System.out.println("material of hair clip is : "+hairClipEighteen.hairClipMaterial);
				System.out.println("type of hair clip is : "+hairClipEighteen.hairClipType);
				System.out.println("price of the hair clip is : "+hairClipEighteen.hairClipPrice);
				System.out.println("size of the hair clip is : "+hairClipEighteen.hairClipSize);
				
			HairClip hairClipNineteen = new HairClip();
			hairClipNineteen.hairClipId=19;
			hairClipNineteen.hairClipColor="Lime Green";
			hairClipNineteen.hairClipMaterial="Acrylic";
			hairClipNineteen.hairClipType=" Clutch Clip";
			hairClipNineteen.hairClipPrice=35.0;
			hairClipNineteen.hairClipSize="Medium";
				System.out.println();
				System.out.println("HairClip nineteen details : ");
				System.out.println("id of the hair clip is : "+hairClipNineteen.hairClipId);
				System.out.println("color of hair clip is : "+hairClipNineteen.hairClipColor);
				System.out.println("material of hair clip is : "+hairClipNineteen.hairClipMaterial);
				System.out.println("type of hair clip is : "+hairClipNineteen.hairClipType);
				System.out.println("price of the hair clip is : "+hairClipNineteen.hairClipPrice);
				System.out.println("size of the hair clip is : "+hairClipNineteen.hairClipSize);
				
			HairClip hairClipTwenty = new HairClip();
			hairClipTwenty.hairClipId=20;
			hairClipTwenty.hairClipColor="Magenta";
			hairClipTwenty.hairClipMaterial="Acrylic";
			hairClipTwenty.hairClipType=" Arcylic Clip";
			hairClipTwenty.hairClipPrice=15.0;
			hairClipTwenty.hairClipSize="Small";
				System.out.println();
				System.out.println("HairClip twenty details : ");
				System.out.println("id of the hair clip is : "+hairClipTwenty.hairClipId);
				System.out.println("color of hair clip is : "+hairClipTwenty.hairClipColor);
				System.out.println("material of hair clip is : "+hairClipTwenty.hairClipMaterial);
				System.out.println("type of hair clip is : "+hairClipTwenty.hairClipType);
				System.out.println("price of the hair clip is : "+hairClipTwenty.hairClipPrice);
				System.out.println("size of the hair clip is : "+hairClipTwenty.hairClipSize);
				System.out.println();
		System.out.println("main ended");
	}
}