class HatRunner{

	public static void main(String[] args){
	System.out.println("main started");
		Hat firstHat= new Hat();
		firstHat.hatId=1;
		firstHat.hatType="Fedora";
		firstHat.hatColor="Navy Blue";
		firstHat.brandName="Adidas";
		firstHat.price=499.00;
		firstHat.material="cotton";
			System.out.println();
			System.out.println("first hat details : ");
			System.out.println("id of hat is :"+firstHat.hatId);
			System.out.println("type of the hat is : "+firstHat.hatType);
			System.out.println("color of the hat is : "+firstHat.hatColor);
			System.out.println("brand name of the hat is : "+firstHat.brandName);
			System.out.println("price of the hat is : "+firstHat.price);
			System.out.println("material of the hat is : "+firstHat.material);
			
		Hat secondHat= new Hat();
		secondHat.hatId = 2;
		secondHat.hatType = "Baseball Cap";
		secondHat.hatColor = "Black";
		secondHat.brandName = "Nike";
		secondHat.price = 399.00;
		secondHat.material = "Polyester";
			System.out.println();
			System.out.println("second hat details : ");
			System.out.println("id of hat is :"+secondHat.hatId);
			System.out.println("type of the hat is : "+secondHat.hatType);
			System.out.println("color of the hat is : "+secondHat.hatColor);
			System.out.println("brand name of the hat is : "+secondHat.brandName);
			System.out.println("price of the hat is : "+secondHat.price);
			System.out.println("material of the hat is : "+secondHat.material);
			
		Hat thirdHat= new Hat();
		thirdHat.hatId = 3;
		thirdHat.hatType = "Beanie";
		thirdHat.hatColor = "Grey";
		thirdHat.brandName = "Puma";
		thirdHat.price = 299.00;
		thirdHat.material = "Wool";
			System.out.println();
			System.out.println("third hat details : ");
			System.out.println("id of hat is :"+thirdHat.hatId);
			System.out.println("type of the hat is : "+thirdHat.hatType);
			System.out.println("color of the hat is : "+thirdHat.hatColor);
			System.out.println("brand name of the hat is : "+thirdHat.brandName);
			System.out.println("price of the hat is : "+thirdHat.price);
			System.out.println("material of the hat is : "+thirdHat.material);
			
		Hat fourthHat= new Hat();
		fourthHat.hatId = 4;
		fourthHat.hatType = "Panama";
		fourthHat.hatColor = "White";
		fourthHat.brandName = "H&M";
		fourthHat.price = 699.00;
		fourthHat.material = "Straw";
			System.out.println();
			System.out.println("fourth hat details : ");
			System.out.println("id of hat is :"+fourthHat.hatId);
			System.out.println("type of the hat is : "+fourthHat.hatType);
			System.out.println("color of the hat is : "+fourthHat.hatColor);
			System.out.println("brand name of the hat is : "+fourthHat.brandName);
			System.out.println("price of the hat is : "+fourthHat.price);
			System.out.println("material of the hat is : "+fourthHat.material);
			
		Hat fifthHat= new Hat();
		fifthHat.hatId = 5;
		fifthHat.hatType = "Beret";
		fifthHat.hatColor = "Red";
		fifthHat.brandName = "Zara";
		fifthHat.price = 549.00;
		fifthHat.material = "Wool";
			System.out.println();
			System.out.println("fifth hat details : ");
			System.out.println("id of hat is :"+fifthHat.hatId);
			System.out.println("type of the hat is : "+fifthHat.hatType);
			System.out.println("color of the hat is : "+fifthHat.hatColor);
			System.out.println("brand name of the hat is : "+fifthHat.brandName);
			System.out.println("price of the hat is : "+fifthHat.price);
			System.out.println("material of the hat is : "+fifthHat.material);
			
		Hat sixthHat= new Hat();
		sixthHat.hatId = 6;
		sixthHat.hatType = "Bucket Hat";
		sixthHat.hatColor = "Olive";
		sixthHat.brandName = "Levi’s";
		sixthHat.price = 449.00;
		sixthHat.material = "Canvas";
			System.out.println();
			System.out.println("sixth hat details : ");
			System.out.println("id of hat is :"+sixthHat.hatId);
			System.out.println("type of the hat is : "+sixthHat.hatType);
			System.out.println("color of the hat is : "+sixthHat.hatColor);
			System.out.println("brand name of the hat is : "+sixthHat.brandName);
			System.out.println("price of the hat is : "+sixthHat.price);
			System.out.println("material of the hat is : "+sixthHat.material);
			
		Hat seventhHat= new Hat();		
		seventhHat.hatId = 7;
		seventhHat.hatType = "Snapback";
		seventhHat.hatColor = "Blue";
		seventhHat.brandName = "New Era";
		seventhHat.price = 499.00;
		seventhHat.material = "Cotton Blend";
			System.out.println();
			System.out.println("seventh hat details : ");
			System.out.println("id of hat is :"+seventhHat.hatId);
			System.out.println("type of the hat is : "+seventhHat.hatType);
			System.out.println("color of the hat is : "+seventhHat.hatColor);
			System.out.println("brand name of the hat is : "+seventhHat.brandName);
			System.out.println("price of the hat is : "+seventhHat.price);
			System.out.println("material of the hat is : "+seventhHat.material);
			
		Hat eighthHat= new Hat();
		eighthHat.hatId = 8;
		eighthHat.hatType = "Boater";
		eighthHat.hatColor = "Beige";
		eighthHat.brandName = "Forever 21";
		eighthHat.price = 599.00;
		eighthHat.material = "Straw";
			System.out.println();
			System.out.println("eighth hat details : ");
			System.out.println("id of hat is :"+eighthHat.hatId);
			System.out.println("type of the hat is : "+eighthHat.hatType);
			System.out.println("color of the hat is : "+eighthHat.hatColor);
			System.out.println("brand name of the hat is : "+eighthHat.brandName);
			System.out.println("price of the hat is : "+eighthHat.price);
			System.out.println("material of the hat is : "+eighthHat.material);
			
		Hat ninthHat= new Hat();
		ninthHat.hatId = 9;
		ninthHat.hatType = "Trilby";
		ninthHat.hatColor = "Brown";
		ninthHat.brandName = "Woodland";
		ninthHat.price = 699.00;
		ninthHat.material = "Wool Blend";
			System.out.println();
			System.out.println("ninth hat details : ");
			System.out.println("id of hat is :"+ninthHat.hatId);
			System.out.println("type of the hat is : "+ninthHat.hatType);
			System.out.println("color of the hat is : "+ninthHat.hatColor);
			System.out.println("brand name of the hat is : "+ninthHat.brandName);
			System.out.println("price of the hat is : "+ninthHat.price);
			System.out.println("material of the hat is : "+ninthHat.material);
			
		Hat tenthHat= new Hat();
		tenthHat.hatId = 10;
		tenthHat.hatType = "Cowboy Hat";
		tenthHat.hatColor = "Tan";
		tenthHat.brandName = "Wrangler";
		tenthHat.price = 799.00;
		tenthHat.material = "Leather";
			System.out.println();
			System.out.println("tenth hat details : ");
			System.out.println("id of hat is :"+tenthHat.hatId);
			System.out.println("type of the hat is : "+tenthHat.hatType);
			System.out.println("color of the hat is : "+tenthHat.hatColor);
			System.out.println("brand name of the hat is : "+tenthHat.brandName);
			System.out.println("price of the hat is : "+tenthHat.price);
			System.out.println("material of the hat is : "+tenthHat.material);
			
		Hat eleventhHat= new Hat();
		eleventhHat.hatId = 11;
		eleventhHat.hatType = "Newsboy Cap";
		eleventhHat.hatColor = "Charcoal";
		eleventhHat.brandName = "Gap";
		eleventhHat.price = 499.00;
		eleventhHat.material = "Tweed";
			System.out.println();
			System.out.println("eleventh hat details : ");
			System.out.println("id of hat is :"+eleventhHat.hatId);
			System.out.println("type of the hat is : "+eleventhHat.hatType);
			System.out.println("color of the hat is : "+eleventhHat.hatColor);
			System.out.println("brand name of the hat is : "+eleventhHat.brandName);
			System.out.println("price of the hat is : "+eleventhHat.price);
			System.out.println("material of the hat is : "+eleventhHat.material);
			
		Hat twelfthHat= new Hat();
		twelfthHat.hatId = 12;
		twelfthHat.hatType = "Sun Hat";
		twelfthHat.hatColor = "Cream";
		twelfthHat.brandName = "Marks & Spencer";
		twelfthHat.price = 699.00;
		twelfthHat.material = "Linen";
			System.out.println();
			System.out.println("twelfth hat details : ");
			System.out.println("id of hat is :"+twelfthHat.hatId);
			System.out.println("type of the hat is : "+twelfthHat.hatType);
			System.out.println("color of the hat is : "+twelfthHat.hatColor);
			System.out.println("brand name of the hat is : "+twelfthHat.brandName);
			System.out.println("price of the hat is : "+twelfthHat.price);
			System.out.println("material of the hat is : "+twelfthHat.material);
			
		Hat thirteenthHat= new Hat();
		thirteenthHat.hatId = 13;
		thirteenthHat.hatType = "Top Hat";
		thirteenthHat.hatColor = "Black";
		thirteenthHat.brandName = "Vintage Wear";
		thirteenthHat.price = 999.00;
		thirteenthHat.material = "Satin";
			System.out.println();
			System.out.println("thirteenth hat details : ");
			System.out.println("id of hat is :"+thirteenthHat.hatId);
			System.out.println("type of the hat is : "+thirteenthHat.hatType);
			System.out.println("color of the hat is : "+thirteenthHat.hatColor);
			System.out.println("brand name of the hat is : "+thirteenthHat.brandName);
			System.out.println("price of the hat is : "+thirteenthHat.price);
			System.out.println("material of the hat is : "+thirteenthHat.material);
			
		Hat fourteenthHat= new Hat();
		fourteenthHat.hatId = 14;
		fourteenthHat.hatType = "Visor";
		fourteenthHat.hatColor = "Neon Green";
		fourteenthHat.brandName = "Reebok";
		fourteenthHat.price = 399.00;
		fourteenthHat.material = "Nylon";
			System.out.println();
			System.out.println("fourteenth hat details : ");
			System.out.println("id of hat is :"+fourteenthHat.hatId);
			System.out.println("type of the hat is : "+fourteenthHat.hatType);
			System.out.println("color of the hat is : "+fourteenthHat.hatColor);
			System.out.println("brand name of the hat is : "+fourteenthHat.brandName);
			System.out.println("price of the hat is : "+fourteenthHat.price);
			System.out.println("material of the hat is : "+fourteenthHat.material);
			
		Hat fifteenthHat= new Hat();
		fifteenthHat.hatId = 15;
		fifteenthHat.hatType = "Safari Hat";
		fifteenthHat.hatColor = "Khaki";
		fifteenthHat.brandName = "Columbia";
		fifteenthHat.price = 749.00;
		fifteenthHat.material = "Canvas";
			System.out.println();
			System.out.println("fifteenth hat details : ");
			System.out.println("id of hat is :"+fifteenthHat.hatId);
			System.out.println("type of the hat is : "+fifteenthHat.hatType);
			System.out.println("color of the hat is : "+fifteenthHat.hatColor);
			System.out.println("brand name of the hat is : "+fifteenthHat.brandName);
			System.out.println("price of the hat is : "+fifteenthHat.price);
			System.out.println("material of the hat is : "+fifteenthHat.material);
			
		Hat sixteenthHat= new Hat();
		sixteenthHat.hatId = 16;
		sixteenthHat.hatType = "Cloche";
		sixteenthHat.hatColor = "Peach";
		sixteenthHat.brandName = "Chanel";
		sixteenthHat.price = 1299.00;
		sixteenthHat.material = "Wool Felt";
			System.out.println();
			System.out.println("sixteenth hat details : ");
			System.out.println("id of hat is :"+sixteenthHat.hatId);
			System.out.println("type of the hat is : "+sixteenthHat.hatType);
			System.out.println("color of the hat is : "+sixteenthHat.hatColor);
			System.out.println("brand name of the hat is : "+sixteenthHat.brandName);
			System.out.println("price of the hat is : "+sixteenthHat.price);
			System.out.println("material of the hat is : "+sixteenthHat.material);
			
		Hat seventeenthHat= new Hat();
		seventeenthHat.hatId = 17;
		seventeenthHat.hatType = "Ascot Cap";
		seventeenthHat.hatColor = "Dark Green";
		seventeenthHat.brandName = "Gucci";
		seventeenthHat.price = 1399.00;
		seventeenthHat.material = "Leather";
			System.out.println();
			System.out.println("seventeenth hat details : ");
			System.out.println("id of hat is :"+seventeenthHat.hatId);
			System.out.println("type of the hat is : "+seventeenthHat.hatType);
			System.out.println("color of the hat is : "+seventeenthHat.hatColor);
			System.out.println("brand name of the hat is : "+seventeenthHat.brandName);
			System.out.println("price of the hat is : "+seventeenthHat.price);
			System.out.println("material of the hat is : "+seventeenthHat.material);
			
		Hat eighteenthHat= new Hat();
		eighteenthHat.hatId = 18;
		eighteenthHat.hatType = "Flat Cap";
		eighteenthHat.hatColor = "Navy";
		eighteenthHat.brandName = "Lacoste";
		eighteenthHat.price = 849.00;
		eighteenthHat.material = "Wool Blend";
			System.out.println();
			System.out.println("eighteenth hat details : ");
			System.out.println("id of hat is :"+eighteenthHat.hatId);
			System.out.println("type of the hat is : "+eighteenthHat.hatType);
			System.out.println("color of the hat is : "+eighteenthHat.hatColor);
			System.out.println("brand name of the hat is : "+eighteenthHat.brandName);
			System.out.println("price of the hat is : "+eighteenthHat.price);
			System.out.println("material of the hat is : "+eighteenthHat.material);
			
		Hat nineteenthHat= new Hat();
		nineteenthHat.hatId = 19;
		nineteenthHat.hatType = "Pillbox Hat";
		nineteenthHat.hatColor = "Maroon";
		nineteenthHat.brandName = "Dior";
		nineteenthHat.price = 1599.00;
		nineteenthHat.material = "Velvet";
			System.out.println();
			System.out.println("nineteenth hat details : ");
			System.out.println("id of hat is :"+nineteenthHat.hatId);
			System.out.println("type of the hat is : "+nineteenthHat.hatType);
			System.out.println("color of the hat is : "+nineteenthHat.hatColor);
			System.out.println("brand name of the hat is : "+nineteenthHat.brandName);
			System.out.println("price of the hat is : "+nineteenthHat.price);
			System.out.println("material of the hat is : "+nineteenthHat.material);
			
		Hat twentiethHat= new Hat();
		twentiethHat.hatId = 20;
		twentiethHat.hatType = "Deerstalker";
		twentiethHat.hatColor = "Plaid";
		twentiethHat.brandName = "Sherlock Gear";
		twentiethHat.price = 999.00;
		twentiethHat.material = "Wool Tweed";
			System.out.println();
			System.out.println("twentieth hat details : ");
			System.out.println("id of hat is :"+twentiethHat.hatId);
			System.out.println("type of the hat is : "+twentiethHat.hatType);
			System.out.println("color of the hat is : "+twentiethHat.hatColor);
			System.out.println("brand name of the hat is : "+twentiethHat.brandName);
			System.out.println("price of the hat is : "+twentiethHat.price);
			System.out.println("material of the hat is : "+twentiethHat.material);
			
	System.out.println("main ended");
	}
}