class JewelleryRunner{

	public static void main(String[] jewels){
		System.out.println("main started");
			Jewellery jewelleryOne = new Jewellery();
			jewelleryOne.jewelleryId=1;
			jewelleryOne.jewelleryType="Gold";
			jewelleryOne.jewelleryName="Bangles";
			jewelleryOne.makingCharges=3.5;
			jewelleryOne.jewelleryPrice=50000.00;
			jewelleryOne.jewelleryDesignStyle="Traditional";
			jewelleryOne.warrantyPeriod=3;
				System.out.println();
				System.out.println("Jewellery One details : ");
				System.out.println("id of jewellery is : "+jewelleryOne.jewelleryId);
				System.out.println("the type of the jewellery is : "+jewelleryOne.jewelleryType);
				System.out.println("the jewellery name is : "+jewelleryOne.jewelleryName);
				System.out.println("the making charges of the jewellery is : "+jewelleryOne.makingCharges+" %");
				System.out.println("the price of the jewellery is : "+jewelleryOne.jewelleryPrice);
				System.out.println("the design style of the jewellery is : "+jewelleryOne.jewelleryDesignStyle);
				System.out.println("the warranty period of the jewellery is  : "+jewelleryOne.warrantyPeriod);
				
			Jewellery jewelleryTwo = new Jewellery();
			jewelleryTwo.jewelleryId=2;
			jewelleryTwo.jewelleryType="Gold";
			jewelleryTwo.jewelleryName="Necklace";
			jewelleryTwo.makingCharges=3;
			jewelleryTwo.jewelleryPrice=250000.00;
			jewelleryTwo.jewelleryDesignStyle="Antique";
			jewelleryTwo.warrantyPeriod=5;
				System.out.println();
				System.out.println("Jewellery Two details : ");
				System.out.println("id of jewellery is : "+jewelleryTwo.jewelleryId);
				System.out.println("the type of the jewellery is : "+jewelleryTwo.jewelleryType);
				System.out.println("the jewellery name is : "+jewelleryTwo.jewelleryName);
				System.out.println("the making charges of the jewellery is : "+jewelleryTwo.makingCharges+" %");
				System.out.println("the price of the jewellery is : "+jewelleryTwo.jewelleryPrice);
				System.out.println("the design style of the jewellery is : "+jewelleryTwo.jewelleryDesignStyle);
				System.out.println("the warranty period of the jewellery is  : "+jewelleryTwo.warrantyPeriod);
				
			Jewellery jewelleryThree = new Jewellery();
			jewelleryThree.jewelleryId=3;
			jewelleryThree.jewelleryType="Silver";
			jewelleryThree.jewelleryName="Neck Chain";
			jewelleryThree.makingCharges=1;
			jewelleryThree.jewelleryPrice=5000.00;
			jewelleryThree.jewelleryDesignStyle="Modern";
			jewelleryThree.warrantyPeriod=1;
				System.out.println();
				System.out.println("Jewellery Three details : ");
				System.out.println("id of jewellery is : "+jewelleryThree.jewelleryId);
				System.out.println("the type of the jewellery is : "+jewelleryThree.jewelleryType);
				System.out.println("the jewellery name is : "+jewelleryThree.jewelleryName);
				System.out.println("the making charges of the jewellery is : "+jewelleryThree.makingCharges+" %");
				System.out.println("the price of the jewellery is : "+jewelleryThree.jewelleryPrice);
				System.out.println("the design style of the jewellery is : "+jewelleryThree.jewelleryDesignStyle);
				System.out.println("the warranty period of the jewellery is  : "+jewelleryThree.warrantyPeriod);
			
			Jewellery jewelleryFour = new Jewellery();
			jewelleryFour.jewelleryId=4;
			jewelleryFour.jewelleryType="Platinum";
			jewelleryFour.jewelleryName="Ring";
			jewelleryFour.makingCharges=5;
			jewelleryFour.jewelleryPrice=500000.00;
			jewelleryFour.jewelleryDesignStyle="Antique";
			jewelleryFour.warrantyPeriod=7;
				System.out.println();
				System.out.println("Jewellery Four details : ");
				System.out.println("id of jewellery is : "+jewelleryFour.jewelleryId);
				System.out.println("the type of the jewellery is : "+jewelleryFour.jewelleryType);
				System.out.println("the jewellery name is : "+jewelleryFour.jewelleryName);
				System.out.println("the making charges of the jewellery is : "+jewelleryFour.makingCharges+" %");
				System.out.println("the price of the jewellery is : "+jewelleryFour.jewelleryPrice);
				System.out.println("the design style of the jewellery is : "+jewelleryFour.jewelleryDesignStyle);
				System.out.println("the warranty period of the jewellery is  : "+jewelleryFour.warrantyPeriod);
			
			Jewellery jewelleryFive = new Jewellery();
			jewelleryFive.jewelleryId=5;
			jewelleryFive.jewelleryType="Daimond";
			jewelleryFive.jewelleryName="Earrings";
			jewelleryFive.makingCharges=4.5;
			jewelleryFive.jewelleryPrice=200000.00;
			jewelleryFive.jewelleryDesignStyle="Uncut";
			jewelleryFive.warrantyPeriod=5;
				System.out.println();
				System.out.println("Jewellery Five details : ");
				System.out.println("id of jewellery is : "+jewelleryFive.jewelleryId);
				System.out.println("the type of the jewellery is : "+jewelleryFive.jewelleryType);
				System.out.println("the jewellery name is : "+jewelleryFive.jewelleryName);
				System.out.println("the making charges of the jewellery is : "+jewelleryFive.makingCharges+" %");
				System.out.println("the price of the jewellery is : "+jewelleryFive.jewelleryPrice);
				System.out.println("the design style of the jewellery is : "+jewelleryFive.jewelleryDesignStyle);
				System.out.println("the warranty period of the jewellery is  : "+jewelleryFive.warrantyPeriod);
				
			Jewellery jewellerySix = new Jewellery();
			jewellerySix.jewelleryId=6;
			jewellerySix.jewelleryType="Gold";
			jewellerySix.jewelleryName="Jhumka";
			jewellerySix.makingCharges=3.1;
			jewellerySix.jewelleryPrice=45000.00;
			jewellerySix.jewelleryDesignStyle="Modern";
			jewellerySix.warrantyPeriod=2;
				System.out.println();
				System.out.println("Jewellery Six details : ");
				System.out.println("id of jewellery is : "+jewellerySix.jewelleryId);
				System.out.println("the type of the jewellery is : "+jewellerySix.jewelleryType);
				System.out.println("the jewellery name is : "+jewellerySix.jewelleryName);
				System.out.println("the making charges of the jewellery is : "+jewellerySix.makingCharges+" %");
				System.out.println("the price of the jewellery is : "+jewellerySix.jewelleryPrice);
				System.out.println("the design style of the jewellery is : "+jewellerySix.jewelleryDesignStyle);
				System.out.println("the warranty period of the jewellery is  : "+jewellerySix.warrantyPeriod);
				
			Jewellery jewellerySeven = new Jewellery();
			jewellerySeven.jewelleryId=7;
			jewellerySeven.jewelleryType="Gold";
			jewellerySeven.jewelleryName="Bracelet";
			jewellerySeven.makingCharges=4;
			jewellerySeven.jewelleryPrice=99000.00;
			jewellerySeven.jewelleryDesignStyle="Antique";
			jewellerySeven.warrantyPeriod=1;
				System.out.println();
				System.out.println("Jewellery Seven details : ");
				System.out.println("id of jewellery is : "+jewellerySeven.jewelleryId);
				System.out.println("the type of the jewellery is : "+jewellerySeven.jewelleryType);
				System.out.println("the jewellery name is : "+jewellerySeven.jewelleryName);
				System.out.println("the making charges of the jewellery is : "+jewellerySeven.makingCharges+" %");
				System.out.println("the price of the jewellery is : "+jewellerySeven.jewelleryPrice);
				System.out.println("the design style of the jewellery is : "+jewellerySeven.jewelleryDesignStyle);
				System.out.println("the warranty period of the jewellery is  : "+jewellerySeven.warrantyPeriod);
				
			Jewellery jewelleryEight = new Jewellery();
			jewelleryEight.jewelleryId=8;
			jewelleryEight.jewelleryType="Silver";
			jewelleryEight.jewelleryName="Anklets";
			jewelleryEight.makingCharges=1;
			jewelleryEight.jewelleryPrice=3200.00;
			jewelleryEight.jewelleryDesignStyle="Modern";
			jewelleryEight.warrantyPeriod=1;
				System.out.println();
				System.out.println("Jewellery Eight details : ");
				System.out.println("id of jewellery is : "+jewelleryEight.jewelleryId);
				System.out.println("the type of the jewellery is : "+jewelleryEight.jewelleryType);
				System.out.println("the jewellery name is : "+jewelleryEight.jewelleryName);
				System.out.println("the making charges of the jewellery is : "+jewelleryEight.makingCharges+" %");
				System.out.println("the price of the jewellery is : "+jewelleryEight.jewelleryPrice);
				System.out.println("the design style of the jewellery is : "+jewelleryEight.jewelleryDesignStyle);
				System.out.println("the warranty period of the jewellery is  : "+jewelleryEight.warrantyPeriod);
				
			Jewellery jewelleryNine = new Jewellery();
			jewelleryNine.jewelleryId=9;
			jewelleryNine.jewelleryType="Diamond";
			jewelleryNine.jewelleryName="Neck Chain";
			jewelleryNine.makingCharges=6;
			jewelleryNine.jewelleryPrice=350200.00;
			jewelleryNine.jewelleryDesignStyle="Traditional";
			jewelleryNine.warrantyPeriod=7;
				System.out.println();
				System.out.println("Jewellery Nine details : ");
				System.out.println("id of jewellery is : "+jewelleryNine.jewelleryId);
				System.out.println("the type of the jewellery is : "+jewelleryNine.jewelleryType);
				System.out.println("the jewellery name is : "+jewelleryNine.jewelleryName);
				System.out.println("the making charges of the jewellery is : "+jewelleryNine.makingCharges+" %");
				System.out.println("the price of the jewellery is : "+jewelleryNine.jewelleryPrice);
				System.out.println("the design style of the jewellery is : "+jewelleryNine.jewelleryDesignStyle);
				System.out.println("the warranty period of the jewellery is  : "+jewelleryNine.warrantyPeriod);
				
			Jewellery jewelleryTen = new Jewellery();
			jewelleryTen.jewelleryId=10;
			jewelleryTen.jewelleryType="Platinum";
			jewelleryTen.jewelleryName="Bracelet";
			jewelleryTen.makingCharges=5;
			jewelleryTen.jewelleryPrice=750200.00;
			jewelleryTen.jewelleryDesignStyle="Modern";
			jewelleryTen.warrantyPeriod=7;
				System.out.println();
				System.out.println("Jewellery Ten details : ");
				System.out.println("id of jewellery is : "+jewelleryTen.jewelleryId);
				System.out.println("the type of the jewellery is : "+jewelleryTen.jewelleryType);
				System.out.println("the jewellery name is : "+jewelleryTen.jewelleryName);
				System.out.println("the making charges of the jewellery is : "+jewelleryTen.makingCharges+" %");
				System.out.println("the price of the jewellery is : "+jewelleryTen.jewelleryPrice);
				System.out.println("the design style of the jewellery is : "+jewelleryTen.jewelleryDesignStyle);
				System.out.println("the warranty period of the jewellery is  : "+jewelleryTen.warrantyPeriod);
				
			Jewellery jewelleryEleven  = new Jewellery();
			jewelleryEleven.jewelleryId=11;
			jewelleryEleven.jewelleryType="GOld";
			jewelleryEleven.jewelleryName="Bracelet";
			jewelleryEleven.makingCharges=3;
			jewelleryEleven.jewelleryPrice=58200.00;
			jewelleryEleven.jewelleryDesignStyle="Traditional";
			jewelleryEleven.warrantyPeriod=7;
				System.out.println();
				System.out.println("Jewellery Eleventh details : ");
				System.out.println("id of jewellery is : "+jewelleryEleven.jewelleryId);
				System.out.println("the type of the jewellery is : "+jewelleryEleven.jewelleryType);
				System.out.println("the jewellery name is : "+jewelleryEleven.jewelleryName);
				System.out.println("the making charges of the jewellery is : "+jewelleryEleven.makingCharges+" %");
				System.out.println("the price of the jewellery is : "+jewelleryEleven.jewelleryPrice);
				System.out.println("the design style of the jewellery is : "+jewelleryEleven.jewelleryDesignStyle);
				System.out.println("the warranty period of the jewellery is  : "+jewelleryEleven.warrantyPeriod);
				
			Jewellery jewelleryTwelve = new Jewellery();
			jewelleryTwelve.jewelleryId=12;
			jewelleryTwelve.jewelleryType="GOld";
			jewelleryTwelve.jewelleryName="Bracelet";
			jewelleryTwelve.makingCharges=3;
			jewelleryTwelve.jewelleryPrice=58200.00;
			jewelleryTwelve.jewelleryDesignStyle="Traditional";
			jewelleryTwelve.warrantyPeriod=7;
				System.out.println();
				System.out.println("Jewellery Twelve details : ");
				System.out.println("id of jewellery is : "+jewelleryTwelve.jewelleryId);
				System.out.println("the type of the jewellery is : "+jewelleryTwelve.jewelleryType);
				System.out.println("the jewellery name is : "+jewelleryTwelve.jewelleryName);
				System.out.println("the making charges of the jewellery is : "+jewelleryTwelve.makingCharges+" %");
				System.out.println("the price of the jewellery is : "+jewelleryTwelve.jewelleryPrice);
				System.out.println("the design style of the jewellery is : "+jewelleryTwelve.jewelleryDesignStyle);
				System.out.println("the warranty period of the jewellery is  : "+jewelleryTwelve.warrantyPeriod);
				
			Jewellery jewelleryThirteen = new Jewellery();
			jewelleryThirteen.jewelleryId=13;
			jewelleryThirteen.jewelleryType="Silver";
			jewelleryThirteen.jewelleryName="Ring";
			jewelleryThirteen.makingCharges=1;
			jewelleryThirteen.jewelleryPrice=5800.00;
			jewelleryThirteen.jewelleryDesignStyle="Antique";
			jewelleryThirteen.warrantyPeriod=3;
				System.out.println();
				System.out.println("Jewellery Thirteen details : ");
				System.out.println("id of jewellery is : "+jewelleryThirteen.jewelleryId);
				System.out.println("the type of the jewellery is : "+jewelleryThirteen.jewelleryType);
				System.out.println("the jewellery name is : "+jewelleryThirteen.jewelleryName);
				System.out.println("the making charges of the jewellery is : "+jewelleryThirteen.makingCharges+" %");
				System.out.println("the price of the jewellery is : "+jewelleryThirteen.jewelleryPrice);
				System.out.println("the design style of the jewellery is : "+jewelleryThirteen.jewelleryDesignStyle);
				System.out.println("the warranty period of the jewellery is  : "+jewelleryThirteen.warrantyPeriod);
				
			Jewellery jewelleryFourteen = new Jewellery();
			jewelleryFourteen.jewelleryId=14;
			jewelleryFourteen.jewelleryType="Silver";
			jewelleryFourteen.jewelleryName="Toe Ring";
			jewelleryFourteen.makingCharges=2;
			jewelleryFourteen.jewelleryPrice=7500.00;
			jewelleryFourteen.jewelleryDesignStyle="Traditional";
			jewelleryFourteen.warrantyPeriod=1;
				System.out.println();
				System.out.println("Jewellery Fourteen details : ");
				System.out.println("id of jewellery is : "+jewelleryFourteen.jewelleryId);
				System.out.println("the type of the jewellery is : "+jewelleryFourteen.jewelleryType);
				System.out.println("the jewellery name is : "+jewelleryFourteen.jewelleryName);
				System.out.println("the making charges of the jewellery is : "+jewelleryFourteen.makingCharges+" %");
				System.out.println("the price of the jewellery is : "+jewelleryFourteen.jewelleryPrice);
				System.out.println("the design style of the jewellery is : "+jewelleryFourteen.jewelleryDesignStyle);
				System.out.println("the warranty period of the jewellery is  : "+jewelleryFourteen.warrantyPeriod);
				
			Jewellery jewelleryFifteen = new Jewellery();
			jewelleryFifteen.jewelleryId=15;
			jewelleryFifteen.jewelleryType="Gold";
			jewelleryFifteen.jewelleryName="Wedding Set";
			jewelleryFifteen.makingCharges=12;
			jewelleryFifteen.jewelleryPrice=750599.00;
			jewelleryFifteen.jewelleryDesignStyle="Traditional";
			jewelleryFifteen.warrantyPeriod=5;
				System.out.println();
				System.out.println("Jewellery Fifteen details : ");
				System.out.println("id of jewellery is : "+jewelleryFifteen.jewelleryId);
				System.out.println("the type of the jewellery is : "+jewelleryFifteen.jewelleryType);
				System.out.println("the jewellery name is : "+jewelleryFifteen.jewelleryName);
				System.out.println("the making charges of the jewellery is : "+jewelleryFifteen.makingCharges+" %");
				System.out.println("the price of the jewellery is : "+jewelleryFifteen.jewelleryPrice);
				System.out.println("the design style of the jewellery is : "+jewelleryFifteen.jewelleryDesignStyle);
				System.out.println("the warranty period of the jewellery is  : "+jewelleryFifteen.warrantyPeriod);
				
			Jewellery jewellerySixteen = new Jewellery();
			jewellerySixteen.jewelleryId=16;
			jewellerySixteen.jewelleryType="Diamond";
			jewellerySixteen.jewelleryName="Ring";
			jewellerySixteen.makingCharges=4;
			jewellerySixteen.jewelleryPrice=1000000.00;
			jewellerySixteen.jewelleryDesignStyle="Antique";
			jewellerySixteen.warrantyPeriod=9;
				System.out.println();
				System.out.println("Jewellery Sixteen details : ");
				System.out.println("id of jewellery is : "+jewellerySixteen.jewelleryId);
				System.out.println("the type of the jewellery is : "+jewellerySixteen.jewelleryType);
				System.out.println("the jewellery name is : "+jewellerySixteen.jewelleryName);
				System.out.println("the making charges of the jewellery is : "+jewellerySixteen.makingCharges+" %");
				System.out.println("the price of the jewellery is : "+jewellerySixteen.jewelleryPrice);
				System.out.println("the design style of the jewellery is : "+jewellerySixteen.jewelleryDesignStyle);
				System.out.println("the warranty period of the jewellery is  : "+jewellerySixteen.warrantyPeriod);
				
			Jewellery jewellerySeventeen = new Jewellery();
			jewellerySeventeen.jewelleryId=17;
			jewellerySeventeen.jewelleryType="Gold";
			jewellerySeventeen.jewelleryName="Nose Ring";
			jewellerySeventeen.makingCharges=2;
			jewellerySeventeen.jewelleryPrice=2000.00;
			jewellerySeventeen.jewelleryDesignStyle="Traditional";
			jewellerySeventeen.warrantyPeriod=1;
				System.out.println();
				System.out.println("Jewellery Seventeen details : ");
				System.out.println("id of jewellery is : "+jewellerySeventeen.jewelleryId);
				System.out.println("the type of the jewellery is : "+jewellerySeventeen.jewelleryType);
				System.out.println("the jewellery name is : "+jewellerySeventeen.jewelleryName);
				System.out.println("the making charges of the jewellery is : "+jewellerySeventeen.makingCharges+" %");
				System.out.println("the price of the jewellery is : "+jewellerySeventeen.jewelleryPrice);
				System.out.println("the design style of the jewellery is : "+jewellerySeventeen.jewelleryDesignStyle);
				System.out.println("the warranty period of the jewellery is  : "+jewellerySeventeen.warrantyPeriod);
				
			Jewellery jewelleryEighteen = new Jewellery();
			jewelleryEighteen.jewelleryId=18;
			jewelleryEighteen.jewelleryType="Gold";
			jewelleryEighteen.jewelleryName="Mangalsutra";
			jewelleryEighteen.makingCharges=3;
			jewelleryEighteen.jewelleryPrice=70000.00;
			jewelleryEighteen.jewelleryDesignStyle="Traditional";
			jewelleryEighteen.warrantyPeriod=5;
				System.out.println();
				System.out.println("Jewellery Eighteen details : ");
				System.out.println("id of jewellery is : "+jewelleryEighteen.jewelleryId);
				System.out.println("the type of the jewellery is : "+jewelleryEighteen.jewelleryType);
				System.out.println("the jewellery name is : "+jewelleryEighteen.jewelleryName);
				System.out.println("the making charges of the jewellery is : "+jewelleryEighteen.makingCharges+" %");
				System.out.println("the price of the jewellery is : "+jewelleryEighteen.jewelleryPrice);
				System.out.println("the design style of the jewellery is : "+jewelleryEighteen.jewelleryDesignStyle);
				System.out.println("the warranty period of the jewellery is  : "+jewelleryEighteen.warrantyPeriod);
				
			Jewellery jewelleryNineteen = new Jewellery();
			jewelleryNineteen.jewelleryId=19;
			jewelleryNineteen.jewelleryType="Gold";
			jewelleryNineteen.jewelleryName="Pendant";
			jewelleryNineteen.makingCharges=3.5;
			jewelleryNineteen.jewelleryPrice=90900.00;
			jewelleryNineteen.jewelleryDesignStyle="Modern";
			jewelleryNineteen.warrantyPeriod=1;
				System.out.println();
				System.out.println("Jewellery Nineteen details : ");
				System.out.println("id of jewellery is : "+jewelleryNineteen.jewelleryId);
				System.out.println("the type of the jewellery is : "+jewelleryNineteen.jewelleryType);
				System.out.println("the jewellery name is : "+jewelleryNineteen.jewelleryName);
				System.out.println("the making charges of the jewellery is : "+jewelleryNineteen.makingCharges+" %");
				System.out.println("the price of the jewellery is : "+jewelleryNineteen.jewelleryPrice);
				System.out.println("the design style of the jewellery is : "+jewelleryNineteen.jewelleryDesignStyle);
				System.out.println("the warranty period of the jewellery is  : "+jewelleryNineteen.warrantyPeriod);
				
			Jewellery jewelleryTwenty = new Jewellery();
			jewelleryTwenty.jewelleryId=20;
			jewelleryTwenty.jewelleryType="Gold";
			jewelleryTwenty.jewelleryName="Maang Thika";
			jewelleryTwenty.makingCharges=2.5;
			jewelleryTwenty.jewelleryPrice=10000.00;
			jewelleryTwenty.jewelleryDesignStyle="Antique";
			jewelleryTwenty.warrantyPeriod=1;
				System.out.println();
				System.out.println("Jewellery Twenty details : ");
				System.out.println("id of jewellery is : "+jewelleryTwenty.jewelleryId);
				System.out.println("the type of the jewellery is : "+jewelleryTwenty.jewelleryType);
				System.out.println("the jewellery name is : "+jewelleryTwenty.jewelleryName);
				System.out.println("the making charges of the jewellery is : "+jewelleryTwenty.makingCharges+" %");
				System.out.println("the price of the jewellery is : "+jewelleryTwenty.jewelleryPrice);
				System.out.println("the design style of the jewellery is : "+jewelleryTwenty.jewelleryDesignStyle);
				System.out.println("the warranty period of the jewellery is  : "+jewelleryTwenty.warrantyPeriod);
				System.out.println();
		System.out.println("main ended");
	}
}