class KarateRunner{
	public static void main(String ref[]){
		System.out.println("main started");
			
			Karate karateOne = new Karate();
			karateOne.karateId = 1;
			karateOne.name = "Shotokan";
			karateOne.location = "Tokyo, Japan";
			karateOne.includesMeditation = true;
			karateOne.beltLevel = "Yellow";
			karateOne.trainingSchedule = "Mon-Wed-Fri 6AM-8AM";
				System.out.println();
				System.out.println("Karate one details:");
				System.out.println("ID of the karate is: " + karateOne.karateId);
				System.out.println("Name of the karate style: " + karateOne.name);
				System.out.println("Location of the dojo: " + karateOne.location);
				System.out.println("Includes meditation: " + karateOne.includesMeditation);
				System.out.println("Belt level: " + karateOne.beltLevel);
				System.out.println("Training schedule: " + karateOne.trainingSchedule);

			Karate karateTwo = new Karate();
			karateTwo.karateId = 2;
			karateTwo.name = "Goju-Ryu";
			karateTwo.location = "Okinawa, Japan";
			karateTwo.includesMeditation = false;
			karateTwo.beltLevel = "Green";
			karateTwo.trainingSchedule = "Tue-Thu 7PM-9PM";
				System.out.println();
				System.out.println("Karate two details:");
				System.out.println("ID of the karate is: " + karateTwo.karateId);
				System.out.println("Name of the karate style: " + karateTwo.name);
				System.out.println("Location of the dojo: " + karateTwo.location);
				System.out.println("Includes meditation: " + karateTwo.includesMeditation);
				System.out.println("Belt level: " + karateTwo.beltLevel);
				System.out.println("Training schedule: " + karateTwo.trainingSchedule);

			Karate karateThree = new Karate();
			karateThree.karateId = 3;
			karateThree.name = "Shito-Ryu";
			karateThree.location = "Kyoto, Japan";
			karateThree.includesMeditation = true;
			karateThree.beltLevel = "Orange";
			karateThree.trainingSchedule = "Sat-Sun 8AM-10AM";
				System.out.println();
				System.out.println("Karate three details:");
				System.out.println("ID of the karate is: " + karateThree.karateId);
				System.out.println("Name of the karate style: " + karateThree.name);
				System.out.println("Location of the dojo: " + karateThree.location);
				System.out.println("Includes meditation: " + karateThree.includesMeditation);
				System.out.println("Belt level: " + karateThree.beltLevel);
				System.out.println("Training schedule: " + karateThree.trainingSchedule);

			Karate karateFour = new Karate();
			karateFour.karateId = 4;
			karateFour.name = "Wado-Ryu";
			karateFour.location = "Osaka, Japan";
			karateFour.includesMeditation = false;
			karateFour.beltLevel = "Blue";
			karateFour.trainingSchedule = "Mon-Fri 6PM-8PM";
				System.out.println();
				System.out.println("Karate four details:");
				System.out.println("ID of the karate is: " + karateFour.karateId);
				System.out.println("Name of the karate style: " + karateFour.name);
				System.out.println("Location of the dojo: " + karateFour.location);
				System.out.println("Includes meditation: " + karateFour.includesMeditation);
				System.out.println("Belt level: " + karateFour.beltLevel);
				System.out.println("Training schedule: " + karateFour.trainingSchedule);

			Karate karateFive = new Karate();
			karateFive.karateId = 5;
			karateFive.name = "Kyokushin";
			karateFive.location = "Tokyo, Japan";
			karateFive.includesMeditation = true;
			karateFive.beltLevel = "Purple";
			karateFive.trainingSchedule = "Wed-Fri 7AM-9AM";
				System.out.println();
				System.out.println("Karate five details:");
				System.out.println("ID of the karate is: " + karateFive.karateId);
				System.out.println("Name of the karate style: " + karateFive.name);
				System.out.println("Location of the dojo: " + karateFive.location);
				System.out.println("Includes meditation: " + karateFive.includesMeditation);
				System.out.println("Belt level: " + karateFive.beltLevel);
				System.out.println("Training schedule: " + karateFive.trainingSchedule);

			Karate karateSix = new Karate();
			karateSix.karateId = 6;
			karateSix.name = "Shorin-Ryu";
			karateSix.location = "Naha, Okinawa";
			karateSix.includesMeditation = true;
			karateSix.beltLevel = "Brown";
			karateSix.trainingSchedule = "Tue-Thu 6AM-7AM";
				System.out.println();
				System.out.println("Karate six details:");
				System.out.println("ID of the karate is: " + karateSix.karateId);
				System.out.println("Name of the karate style: " + karateSix.name);
				System.out.println("Location of the dojo: " + karateSix.location);
				System.out.println("Includes meditation: " + karateSix.includesMeditation);
				System.out.println("Belt level: " + karateSix.beltLevel);
				System.out.println("Training schedule: " + karateSix.trainingSchedule);

			Karate karateSeven = new Karate();
			karateSeven.karateId = 7;
			karateSeven.name = "Uechi-Ryu";
			karateSeven.location = "Fukuoka, Japan";
			karateSeven.includesMeditation = false;
			karateSeven.beltLevel = "Red";
			karateSeven.trainingSchedule = "Mon-Wed 5PM-7PM";
				System.out.println();
				System.out.println("Karate seven details:");
				System.out.println("ID of the karate is: " + karateSeven.karateId);
				System.out.println("Name of the karate style: " + karateSeven.name);
				System.out.println("Location of the dojo: " + karateSeven.location);
				System.out.println("Includes meditation: " + karateSeven.includesMeditation);
				System.out.println("Belt level: " + karateSeven.beltLevel);
				System.out.println("Training schedule: " + karateSeven.trainingSchedule);

			Karate karateEight = new Karate();
			karateEight.karateId = 8;
			karateEight.name = "Chito-Ryu";
			karateEight.location = "Sapporo, Japan";
			karateEight.includesMeditation = true;
			karateEight.beltLevel = "White";
			karateEight.trainingSchedule = "Fri-Sat 7PM-9PM";
				System.out.println();
				System.out.println("Karate eight details:");
				System.out.println("ID of the karate is: " + karateEight.karateId);
				System.out.println("Name of the karate style: " + karateEight.name);
				System.out.println("Location of the dojo: " + karateEight.location);
				System.out.println("Includes meditation: " + karateEight.includesMeditation);
				System.out.println("Belt level: " + karateEight.beltLevel);
				System.out.println("Training schedule: " + karateEight.trainingSchedule);

			Karate karateNine = new Karate();
			karateNine.karateId = 9;
			karateNine.name = "Shudokan";
			karateNine.location = "Kobe, Japan";
			karateNine.includesMeditation = false;
			karateNine.beltLevel = "Black";
			karateNine.trainingSchedule = "Sun 8AM-11AM";
				System.out.println();
				System.out.println("Karate nine details:");
				System.out.println("ID of the karate is: " + karateNine.karateId);
				System.out.println("Name of the karate style: " + karateNine.name);
				System.out.println("Location of the dojo: " + karateNine.location);
				System.out.println("Includes meditation: " + karateNine.includesMeditation);
				System.out.println("Belt level: " + karateNine.beltLevel);
				System.out.println("Training schedule: " + karateNine.trainingSchedule);

			Karate karateTen = new Karate();
			karateTen.karateId = 10;
			karateTen.name = "Ashihara";
			karateTen.location = "Nagoya, Japan";
			karateTen.includesMeditation = true;
			karateTen.beltLevel = "Brown";
			karateTen.trainingSchedule = "Tue-Thu 8AM-10AM";
			System.out.println();
			System.out.println("Karate ten details:");
			System.out.println("ID of the karate is: " + karateTen.karateId);
			System.out.println("Name of the karate style: " + karateTen.name);
			System.out.println("Location of the dojo: " + karateTen.location);
			System.out.println("Includes meditation: " + karateTen.includesMeditation);
			System.out.println("Belt level: " + karateTen.beltLevel);
			System.out.println("Training schedule: " + karateTen.trainingSchedule);
					
			Karate karateEleven = new Karate();
			karateEleven.name = "Enshin";
			karateEleven.location = "Osaka, Japan";
			karateEleven.includesMeditation = false;
			karateEleven.beltLevel = "Orange";
			karateEleven.trainingSchedule = "Mon-Wed-Fri 9AM-11AM";
				System.out.println();
				System.out.println("Karate eleven details:");
				System.out.println("ID of the karate is: " + karateEleven.karateId);
				System.out.println("Name of the karate style: " + karateEleven.name);
				System.out.println("Location of the dojo: " + karateEleven.location);
				System.out.println("Includes meditation: " + karateEleven.includesMeditation);
				System.out.println("Belt level: " + karateEleven.beltLevel);
				System.out.println("Training schedule: " + karateEleven.trainingSchedule);

			Karate karateTwelve = new Karate();
			karateTwelve.karateId = 12;
			karateTwelve.name = "Budokan";
			karateTwelve.location = "Hiroshima, Japan";
			karateTwelve.includesMeditation = true;
			karateTwelve.beltLevel = "Green";
			karateTwelve.trainingSchedule = "Tue-Thu 4PM-6PM";
				System.out.println();
				System.out.println("Karate twelve details:");
				System.out.println("ID of the karate is: " + karateTwelve.karateId);
				System.out.println("Name of the karate style: " + karateTwelve.name);
				System.out.println("Location of the dojo: " + karateTwelve.location);
				System.out.println("Includes meditation: " + karateTwelve.includesMeditation);
				System.out.println("Belt level: " + karateTwelve.beltLevel);
				System.out.println("Training schedule: " + karateTwelve.trainingSchedule);

			Karate karateThirteen = new Karate();
			karateThirteen.karateId = 13;
			karateThirteen.name = "Shindo Jinen-Ryu";
			karateThirteen.location = "Yokohama, Japan";
			karateThirteen.includesMeditation = false;
			karateThirteen.beltLevel = "White";
			karateThirteen.trainingSchedule = "Mon-Tue 7PM-8PM";
				System.out.println();
				System.out.println("Karate thirteen details:");
				System.out.println("ID of the karate is: " + karateThirteen.karateId);
				System.out.println("Name of the karate style: " + karateThirteen.name);
				System.out.println("Location of the dojo: " + karateThirteen.location);
				System.out.println("Includes meditation: " + karateThirteen.includesMeditation);
				System.out.println("Belt level: " + karateThirteen.beltLevel);
				System.out.println("Training schedule: " + karateThirteen.trainingSchedule);

			Karate karateFourteen = new Karate();
			karateFourteen.karateId = 14;
			karateFourteen.name = "Seido";
			karateFourteen.location = "Tokyo, Japan";
			karateFourteen.includesMeditation = true;
			karateFourteen.beltLevel = "Blue";
			karateFourteen.trainingSchedule = "Fri-Sun 5AM-7AM";
				System.out.println();
				System.out.println("Karate fourteen details:");
				System.out.println("ID of the karate is: " + karateFourteen.karateId);
				System.out.println("Name of the karate style: " + karateFourteen.name);
				System.out.println("Location of the dojo: " + karateFourteen.location);
				System.out.println("Includes meditation: " + karateFourteen.includesMeditation);
				System.out.println("Belt level: " + karateFourteen.beltLevel);
				System.out.println("Training schedule: " + karateFourteen.trainingSchedule);

			Karate karateFifteen = new Karate();
			karateFifteen.karateId = 15;
			karateFifteen.name = "Kudo";
			karateFifteen.location = "Sendai, Japan";
			karateFifteen.includesMeditation = false;
			karateFifteen.beltLevel = "Purple";
			karateFifteen.trainingSchedule = "Wed-Fri 6PM-8PM";
				System.out.println();
				System.out.println("Karate fifteen details:");
				System.out.println("ID of the karate is: " + karateFifteen.karateId);
				System.out.println("Name of the karate style: " + karateFifteen.name);
				System.out.println("Location of the dojo: " + karateFifteen.location);
				System.out.println("Includes meditation: " + karateFifteen.includesMeditation);
				System.out.println("Belt level: " + karateFifteen.beltLevel);
				System.out.println("Training schedule: " + karateFifteen.trainingSchedule);

			Karate karateSixteen = new Karate();
			karateSixteen.karateId = 16;
			karateSixteen.name = "Ryuei-Ryu";
			karateSixteen.location = "Nagasaki, Japan";
			karateSixteen.includesMeditation = true;
			karateSixteen.beltLevel = "Red";
			karateSixteen.trainingSchedule = "Tue-Thu 9AM-11AM";
				System.out.println();
				System.out.println("Karate sixteen details:");
				System.out.println("ID of the karate is: " + karateSixteen.karateId);
				System.out.println("Name of the karate style: " + karateSixteen.name);
				System.out.println("Location of the dojo: " + karateSixteen.location);
				System.out.println("Includes meditation: " + karateSixteen.includesMeditation);
				System.out.println("Belt level: " + karateSixteen.beltLevel);
				System.out.println("Training schedule: " + karateSixteen.trainingSchedule);

			Karate karateSeventeen = new Karate();
			karateSeventeen.karateId = 17;
			karateSeventeen.name = "Byakuren Kaikan";
			karateSeventeen.location = "Saitama, Japan";
			karateSeventeen.includesMeditation = false;
			karateSeventeen.beltLevel = "Black";
			karateSeventeen.trainingSchedule = "Sat 3PM-6PM";
				System.out.println();
				System.out.println("Karate seventeen details:");
				System.out.println("ID of the karate is: " + karateSeventeen.karateId);
				System.out.println("Name of the karate style: " + karateSeventeen.name);
				System.out.println("Location of the dojo: " + karateSeventeen.location);
				System.out.println("Includes meditation: " + karateSeventeen.includesMeditation);
				System.out.println("Belt level: " + karateSeventeen.beltLevel);
				System.out.println("Training schedule: " + karateSeventeen.trainingSchedule);

			Karate karateEighteen = new Karate();
			karateEighteen.karateId = 18;
			karateEighteen.name = "Okinawa Kenpo";
			karateEighteen.location = "Naha, Okinawa";
			karateEighteen.includesMeditation = true;
			karateEighteen.beltLevel = "Yellow";
			karateEighteen.trainingSchedule = "Mon-Wed 10AM-12PM";
				System.out.println();
				System.out.println("Karate eighteen details:");
				System.out.println("ID of the karate is: " + karateEighteen.karateId);
				System.out.println("Name of the karate style: " + karateEighteen.name);
				System.out.println("Location of the dojo: " + karateEighteen.location);
				System.out.println("Includes meditation: " + karateEighteen.includesMeditation);
				System.out.println("Belt level: " + karateEighteen.beltLevel);
				System.out.println("Training schedule: " + karateEighteen.trainingSchedule);

			Karate karateNineteen = new Karate();
			karateNineteen.karateId = 19;
			karateNineteen.name = "Goshin-Ryu";
			karateNineteen.location = "Chiba, Japan";
			karateNineteen.includesMeditation = false;
			karateNineteen.beltLevel = "Green";
			karateNineteen.trainingSchedule = "Fri-Sat 4PM-6PM";
				System.out.println();
				System.out.println("Karate nineteen details:");
				System.out.println("ID of the karate is: " + karateNineteen.karateId);
				System.out.println("Name of the karate style: " + karateNineteen.name);
				System.out.println("Location of the dojo: " + karateNineteen.location);
				System.out.println("Includes meditation: " + karateNineteen.includesMeditation);
				System.out.println("Belt level: " + karateNineteen.beltLevel);
				System.out.println("Training schedule: " + karateNineteen.trainingSchedule);
			
			Karate karateTwenty = new Karate();
			karateTwenty.karateId = 20;
			karateTwenty.name = "Yamato Karate";
			karateTwenty.location = "Nara, Japan";
			karateTwenty.includesMeditation = true;
			karateTwenty.beltLevel = "Black Belt - 3rd Dan";
			karateTwenty.trainingSchedule = "Monday to Friday, 6:00 PM - 8:00 PM";
				System.out.println();
				System.out.println("Karate Twenty Details:");
				System.out.println("ID of the Karate is : " + karateTwenty.karateId);
				System.out.println("Name of the Karate dojo : " + karateTwenty.name);
				System.out.println("Location of the Karate dojo : " + karateTwenty.location);
				System.out.println("Includes meditation? : " + karateTwenty.includesMeditation);
				System.out.println("Belt level is : " + karateTwenty.beltLevel);
				System.out.println("Training schedule : " + karateTwenty.trainingSchedule);

		System.out.println("main ended");
	}
}