class KingRunner{
	public static void main(String[] king){
		System.out.println("main started");
			
			King kingOne=new King();
			kingOne.kingId=1;
			kingOne.kingName="Krishnaraja Vadeyar";
			kingOne.dynastyName="Tuluva";
			kingOne.kingdomName="The Vijayanagara Empire";
			kingOne.capitalCity="Vijayanagar";
			kingOne.reignStart="26 July 1509";
			kingOne.reignEnd="17 October 1529";
				System.out.println();
				System.out.println("King One details : ");
				System.out.println("id of the king : "+kingOne.kingId);
				System.out.println("name of the king is : "+kingOne.kingName);
				System.out.println("name of the dynasty of the king : "+kingOne.dynastyName);
				System.out.println("name of the kingdom : "+kingOne.kingdomName);
				System.out.println("capitalCity of the kingdom is : "+kingOne.capitalCity);
				System.out.println("reign starte of the kingdom is : "+kingOne.reignStart);
				System.out.println("reign end of the kingdom is : "+kingOne.reignEnd);

			King kingTwo=new King();
			kingTwo.kingId=2;
			kingTwo.kingName="Ashoka the Great";
			kingTwo.dynastyName="Maurya";
			kingTwo.kingdomName="Maurya Empire";
			kingTwo.capitalCity="Pataliputra";
			kingTwo.reignStart="268 BCE";
			kingTwo.reignEnd="232 BCE";
				System.out.println();
				System.out.println("King Two details : ");
				System.out.println("id of the king : "+kingTwo.kingId);
				System.out.println("name of the king is : "+kingTwo.kingName);
				System.out.println("name of the dynasty of the king : "+kingTwo.dynastyName);
				System.out.println("name of the kingdom : "+kingTwo.kingdomName);
				System.out.println("capitalCity of the kingdom is : "+kingTwo.capitalCity);
				System.out.println("reign starte of the kingdom is : "+kingTwo.reignStart);
				System.out.println("reign end of the kingdom is : "+kingTwo.reignEnd);

			King kingThree=new King();
			kingThree.kingId=3;
			kingThree.kingName="Akbar the Great";
			kingThree.dynastyName="Mughal";
			kingThree.kingdomName="Mughal Empire";
			kingThree.capitalCity="Agra";
			kingThree.reignStart="11 February 1556";
			kingThree.reignEnd="27 October 1605";
				System.out.println();
				System.out.println("King Three details : ");
				System.out.println("id of the king : "+kingThree.kingId);
				System.out.println("name of the king is : "+kingThree.kingName);
				System.out.println("name of the dynasty of the king : "+kingThree.dynastyName);
				System.out.println("name of the kingdom : "+kingThree.kingdomName);
				System.out.println("capitalCity of the kingdom is : "+kingThree.capitalCity);
				System.out.println("reign starte of the kingdom is : "+kingThree.reignStart);
				System.out.println("reign end of the kingdom is : "+kingThree.reignEnd);

			King kingFour=new King();
			kingFour.kingId=4;
			kingFour.kingName="Chandragupta Maurya";
			kingFour.dynastyName="Maurya";
			kingFour.kingdomName="Maurya Empire";
			kingFour.capitalCity="Pataliputra";
			kingFour.reignStart="321 BCE";
			kingFour.reignEnd="297 BCE";
				System.out.println();
				System.out.println("King Four details : ");
				System.out.println("id of the king : "+kingFour.kingId);
				System.out.println("name of the king is : "+kingFour.kingName);
				System.out.println("name of the dynasty of the king : "+kingFour.dynastyName);
				System.out.println("name of the kingdom : "+kingFour.kingdomName);
				System.out.println("capitalCity of the kingdom is : "+kingFour.capitalCity);
				System.out.println("reign starte of the kingdom is : "+kingFour.reignStart);
				System.out.println("reign end of the kingdom is : "+kingFour.reignEnd);

			King kingFive=new King();
			kingFive.kingId=5;
			kingFive.kingName="Raja Raja Chola I";
			kingFive.dynastyName="Chola";
			kingFive.kingdomName="Chola Dynasty";
			kingFive.capitalCity="Thanjavur";
			kingFive.reignStart="985 CE";
			kingFive.reignEnd="1014 CE";
				System.out.println();
				System.out.println("King Five details : ");
				System.out.println("id of the king : "+kingFive.kingId);
				System.out.println("name of the king is : "+kingFive.kingName);
				System.out.println("name of the dynasty of the king : "+kingFive.dynastyName);
				System.out.println("name of the kingdom : "+kingFive.kingdomName);
				System.out.println("capitalCity of the kingdom is : "+kingFive.capitalCity);
				System.out.println("reign starte of the kingdom is : "+kingFive.reignStart);
				System.out.println("reign end of the kingdom is : "+kingFive.reignEnd);
			
			King kingSix=new King();
			kingSix.kingId=6;
			kingSix.kingName="Shivaji Maharaj";
			kingSix.dynastyName="Bhonsle";
			kingSix.kingdomName="Maratha Empire";
			kingSix.capitalCity="Raigad";
			kingSix.reignStart="1674";
			kingSix.reignEnd="1680";
				System.out.println();
				System.out.println("King Six details : ");
				System.out.println("id of the king : "+kingSix.kingId);
				System.out.println("name of the king is : "+kingSix.kingName);
				System.out.println("name of the dynasty of the king : "+kingSix.dynastyName);
				System.out.println("name of the kingdom : "+kingSix.kingdomName);
				System.out.println("capitalCity of the kingdom is : "+kingSix.capitalCity);
				System.out.println("reign starte of the kingdom is : "+kingSix.reignStart);
				System.out.println("reign end of the kingdom is : "+kingSix.reignEnd);

			King kingSeven=new King();
			kingSeven.kingId=7;
			kingSeven.kingName="Harsha";
			kingSeven.dynastyName="Vardhana";
			kingSeven.kingdomName="Pushyabhuti Dynasty";
			kingSeven.capitalCity="Kannauj";
			kingSeven.reignStart="606 CE";
			kingSeven.reignEnd="647 CE";
				System.out.println();
				System.out.println("King Seven details : ");
				System.out.println("id of the king : "+kingSeven.kingId);
				System.out.println("name of the king is : "+kingSeven.kingName);
				System.out.println("name of the dynasty of the king : "+kingSeven.dynastyName);
				System.out.println("name of the kingdom : "+kingSeven.kingdomName);
				System.out.println("capitalCity of the kingdom is : "+kingSeven.capitalCity);
				System.out.println("reign starte of the kingdom is : "+kingSeven.reignStart);
				System.out.println("reign end of the kingdom is : "+kingSeven.reignEnd);
			
			King kingEight = new King();
			kingEight.kingId = 8;
			kingEight.kingName = "Rajaraja Chola I";
			kingEight.dynastyName = "Chola";
			kingEight.kingdomName = "Chola Empire";
			kingEight.capitalCity = "Thanjavur";
			kingEight.reignStart = "985 CE";
			kingEight.reignEnd = "1014 CE";
				System.out.println();
				System.out.println("King Eight details : ");
				System.out.println("id of the king : " + kingEight.kingId);
				System.out.println("name of the king is : " + kingEight.kingName);
				System.out.println("name of the dynasty of the king : " + kingEight.dynastyName);
				System.out.println("name of the kingdom : " + kingEight.kingdomName);
				System.out.println("capitalCity of the kingdom is : " + kingEight.capitalCity);
				System.out.println("reign start of the kingdom is : " + kingEight.reignStart);
				System.out.println("reign end of the kingdom is : " + kingEight.reignEnd);

			King kingNine = new King();
			kingNine.kingId = 9;
			kingNine.kingName = "Samudragupta";
			kingNine.dynastyName = "Gupta";
			kingNine.kingdomName = "Gupta Empire";
			kingNine.capitalCity = "Pataliputra";
			kingNine.reignStart = "c. 335 CE";
			kingNine.reignEnd = "c. 375 CE";
				System.out.println();
				System.out.println("King Nine details : ");
				System.out.println("id of the king : " + kingNine.kingId);
				System.out.println("name of the king is : " + kingNine.kingName);
				System.out.println("name of the dynasty of the king : " + kingNine.dynastyName);
				System.out.println("name of the kingdom : " + kingNine.kingdomName);
				System.out.println("capitalCity of the kingdom is : " + kingNine.capitalCity);
				System.out.println("reign start of the kingdom is : " + kingNine.reignStart);
				System.out.println("reign end of the kingdom is : " + kingNine.reignEnd);

			King kingTen = new King();
			kingTen.kingId = 10;
			kingTen.kingName = "Chandragupta Maurya";
			kingTen.dynastyName = "Maurya";
			kingTen.kingdomName = "Maurya Empire";
			kingTen.capitalCity = "Pataliputra";
			kingTen.reignStart = "321 BCE";
			kingTen.reignEnd = "297 BCE";
				System.out.println();
				System.out.println("King Ten details : ");
				System.out.println("id of the king : " + kingTen.kingId);
				System.out.println("name of the king is : " + kingTen.kingName);
				System.out.println("name of the dynasty of the king : " + kingTen.dynastyName);
				System.out.println("name of the kingdom : " + kingTen.kingdomName);
				System.out.println("capitalCity of the kingdom is : " + kingTen.capitalCity);
				System.out.println("reign start of the kingdom is : " + kingTen.reignStart);
				System.out.println("reign end of the kingdom is : " + kingTen.reignEnd);

			King kingEleven = new King();
			kingEleven.kingId = 11;
			kingEleven.kingName = "Harshavardhana";
			kingEleven.dynastyName = "Pushyabhuti";
			kingEleven.kingdomName = "Vardhana Empire";
			kingEleven.capitalCity = "Thanesar";
			kingEleven.reignStart = "606 CE";
			kingEleven.reignEnd = "647 CE";
				System.out.println();
				System.out.println("King Eleven details : ");
				System.out.println("id of the king : " + kingEleven.kingId);
				System.out.println("name of the king is : " + kingEleven.kingName);
				System.out.println("name of the dynasty of the king : " + kingEleven.dynastyName);
				System.out.println("name of the kingdom : " + kingEleven.kingdomName);
				System.out.println("capitalCity of the kingdom is : " + kingEleven.capitalCity);
				System.out.println("reign start of the kingdom is : " + kingEleven.reignStart);
				System.out.println("reign end of the kingdom is : " + kingEleven.reignEnd);

			King kingTwelve = new King();
			kingTwelve.kingId = 12;
			kingTwelve.kingName = "Rana Pratap Singh";
			kingTwelve.dynastyName = "Sisodia";
			kingTwelve.kingdomName = "Mewar";
			kingTwelve.capitalCity = "Chittorgarh";
			kingTwelve.reignStart = "1572";
			kingTwelve.reignEnd = "1597";
				System.out.println();
				System.out.println("King Twelve details : ");
				System.out.println("id of the king : " + kingTwelve.kingId);
				System.out.println("name of the king is : " + kingTwelve.kingName);
				System.out.println("name of the dynasty of the king : " + kingTwelve.dynastyName);
				System.out.println("name of the kingdom : " + kingTwelve.kingdomName);
				System.out.println("capitalCity of the kingdom is : " + kingTwelve.capitalCity);
				System.out.println("reign start of the kingdom is : " + kingTwelve.reignStart);
				System.out.println("reign end of the kingdom is : " + kingTwelve.reignEnd);

			King kingThirteen = new King();
			kingThirteen.kingId = 13;
			kingThirteen.kingName = "Ashoka the Great";
			kingThirteen.dynastyName = "Maurya";
			kingThirteen.kingdomName = "Maurya Empire";
			kingThirteen.capitalCity = "Pataliputra";
			kingThirteen.reignStart = "268 BCE";
			kingThirteen.reignEnd = "232 BCE";
				System.out.println();
				System.out.println("King Thirteen details : ");
				System.out.println("id of the king : " + kingThirteen.kingId);
				System.out.println("name of the king is : " + kingThirteen.kingName);
				System.out.println("name of the dynasty of the king : " + kingThirteen.dynastyName);
				System.out.println("name of the kingdom : " + kingThirteen.kingdomName);
				System.out.println("capitalCity of the kingdom is : " + kingThirteen.capitalCity);
				System.out.println("reign start of the kingdom is : " + kingThirteen.reignStart);
				System.out.println("reign end of the kingdom is : " + kingThirteen.reignEnd);
			
			King kingFourteen = new King();
			kingFourteen.kingId = 14;
			kingFourteen.kingName = "Krishnadevaraya";
			kingFourteen.dynastyName = "Tuluva";
			kingFourteen.kingdomName = "Vijayanagara Empire";
			kingFourteen.capitalCity = "Vijayanagara";
			kingFourteen.reignStart = "1509";
			kingFourteen.reignEnd = "1529";
				System.out.println();
				System.out.println("King Fourteen details : ");
				System.out.println("id of the king : " + kingFourteen.kingId);
				System.out.println("name of the king is : " + kingFourteen.kingName);
				System.out.println("name of the dynasty of the king : " + kingFourteen.dynastyName);
				System.out.println("name of the kingdom : " + kingFourteen.kingdomName);
				System.out.println("capitalCity of the kingdom is : " + kingFourteen.capitalCity);
				System.out.println("reign start of the kingdom is : " + kingFourteen.reignStart);
				System.out.println("reign end of the kingdom is : " + kingFourteen.reignEnd);

			King kingFifteen = new King();
			kingFifteen.kingId = 15;
			kingFifteen.kingName = "Pulakeshin II";
			kingFifteen.dynastyName = "Chalukya";
			kingFifteen.kingdomName = "Chalukya Dynasty";
			kingFifteen.capitalCity = "Vatapi";
			kingFifteen.reignStart = "610 CE";
			kingFifteen.reignEnd = "642 CE";
				System.out.println();
				System.out.println("King Fifteen details : ");
				System.out.println("id of the king : " + kingFifteen.kingId);
				System.out.println("name of the king is : " + kingFifteen.kingName);
				System.out.println("name of the dynasty of the king : " + kingFifteen.dynastyName);
				System.out.println("name of the kingdom : " + kingFifteen.kingdomName);
				System.out.println("capitalCity of the kingdom is : " + kingFifteen.capitalCity);
				System.out.println("reign start of the kingdom is : " + kingFifteen.reignStart);
				System.out.println("reign end of the kingdom is : " + kingFifteen.reignEnd);

			King kingSixteen = new King();
			kingSixteen.kingId = 16;
			kingSixteen.kingName = "Rajendra Chola I";
			kingSixteen.dynastyName = "Chola";
			kingSixteen.kingdomName = "Chola Empire";
			kingSixteen.capitalCity = "Gangaikonda Cholapuram";
			kingSixteen.reignStart = "1014 CE";
			kingSixteen.reignEnd = "1044 CE";
				System.out.println();
				System.out.println("King Sixteen details : ");
				System.out.println("id of the king : " + kingSixteen.kingId);
				System.out.println("name of the king is : " + kingSixteen.kingName);
				System.out.println("name of the dynasty of the king : " + kingSixteen.dynastyName);
				System.out.println("name of the kingdom : " + kingSixteen.kingdomName);
				System.out.println("capitalCity of the kingdom is : " + kingSixteen.capitalCity);
				System.out.println("reign start of the kingdom is : " + kingSixteen.reignStart);
				System.out.println("reign end of the kingdom is : " + kingSixteen.reignEnd);

			King kingSeventeen = new King();
			kingSeventeen.kingId = 17;
			kingSeventeen.kingName = "Bimbisara";
			kingSeventeen.dynastyName = "Haryanka";
			kingSeventeen.kingdomName = "Magadha";
			kingSeventeen.capitalCity = "Rajagriha";
			kingSeventeen.reignStart = "544 BCE";
			kingSeventeen.reignEnd = "492 BCE";
				System.out.println();
				System.out.println("King Seventeen details : ");
				System.out.println("id of the king : " + kingSeventeen.kingId);
				System.out.println("name of the king is : " + kingSeventeen.kingName);
				System.out.println("name of the dynasty of the king : " + kingSeventeen.dynastyName);
				System.out.println("name of the kingdom : " + kingSeventeen.kingdomName);
				System.out.println("capitalCity of the kingdom is : " + kingSeventeen.capitalCity);
				System.out.println("reign start of the kingdom is : " + kingSeventeen.reignStart);
				System.out.println("reign end of the kingdom is : " + kingSeventeen.reignEnd);

			King kingEighteen = new King();
			kingEighteen.kingId = 18;
			kingEighteen.kingName = "Ajatashatru";
			kingEighteen.dynastyName = "Haryanka";
			kingEighteen.kingdomName = "Magadha";
			kingEighteen.capitalCity = "Pataliputra";
			kingEighteen.reignStart = "492 BCE";
			kingEighteen.reignEnd = "460 BCE";
				System.out.println();
				System.out.println("King Eighteen details : ");
				System.out.println("id of the king : " + kingEighteen.kingId);
				System.out.println("name of the king is : " + kingEighteen.kingName);
				System.out.println("name of the dynasty of the king : " + kingEighteen.dynastyName);
				System.out.println("name of the kingdom : " + kingEighteen.kingdomName);
				System.out.println("capitalCity of the kingdom is : " + kingEighteen.capitalCity);
				System.out.println("reign start of the kingdom is : " + kingEighteen.reignStart);
				System.out.println("reign end of the kingdom is : " + kingEighteen.reignEnd);

			King kingNineteen = new King();
			kingNineteen.kingId = 19;
			kingNineteen.kingName = "Mahapadma Nanda";
			kingNineteen.dynastyName = "Nanda";
			kingNineteen.kingdomName = "Nanda Empire";
			kingNineteen.capitalCity = "Pataliputra";
			kingNineteen.reignStart = "c. 345 BCE";
			kingNineteen.reignEnd = "c. 329 BCE";
				System.out.println();
				System.out.println("King Nineteen details : ");
				System.out.println("id of the king : " + kingNineteen.kingId);
				System.out.println("name of the king is : " + kingNineteen.kingName);
				System.out.println("name of the dynasty of the king : " + kingNineteen.dynastyName);
				System.out.println("name of the kingdom : " + kingNineteen.kingdomName);
				System.out.println("capitalCity of the kingdom is : " + kingNineteen.capitalCity);
				System.out.println("reign start of the kingdom is : " + kingNineteen.reignStart);
				System.out.println("reign end of the kingdom is : " + kingNineteen.reignEnd);

			King kingTwenty = new King();
			kingTwenty.kingId = 20;
			kingTwenty.kingName = "Bindusara";
			kingTwenty.dynastyName = "Maurya";
			kingTwenty.kingdomName = "Maurya Empire";
			kingTwenty.capitalCity = "Pataliputra";
			kingTwenty.reignStart = "297 BCE";
			kingTwenty.reignEnd = "273 BCE";
				System.out.println();
				System.out.println("King Twenty details : ");
				System.out.println("id of the king : " + kingTwenty.kingId);
				System.out.println("name of the king is : " + kingTwenty.kingName);
				System.out.println("name of the dynasty of the king : " + kingTwenty.dynastyName);
				System.out.println("name of the kingdom : " + kingTwenty.kingdomName);
				System.out.println("capitalCity of the kingdom is : " + kingTwenty.capitalCity);
				System.out.println("reign start of the kingdom is : " + kingTwenty.reignStart);
				System.out.println("reign end of the kingdom is : " + kingTwenty.reignEnd);


		System.out.println("main ended");
	}
}