class MarbleRunner{

	public static void main(String marble[]){
	
		System.out.println("main started");
			
			Marble marbleOne = new Marble();
			marbleOne.marbleId = 1;
			marbleOne.marbleName = "Calacatta";
			marbleOne.texture = "Smooth";
			marbleOne.porosity = "Low";
			marbleOne.pattern = "Swirls";
			marbleOne.color = "Peach";
				System.out.println();
				System.out.println("Marble one details : ");
				System.out.println("id of marble is : " + marbleOne.marbleId);
				System.out.println("name of the marble is : " + marbleOne.marbleName);
				System.out.println("texture of the marble is : " + marbleOne.texture);
				System.out.println("porosity of the marble is : " + marbleOne.porosity);
				System.out.println("color of the marble is : " + marbleOne.color);
				System.out.println("pattern of the marble is : " + marbleOne.pattern);
			 
			Marble marbleTwo = new Marble();
			marbleTwo.marbleId = 2;
			marbleTwo.marbleName = "Carrara";
			marbleTwo.texture = "Fine";
			marbleTwo.porosity = "Medium";
			marbleTwo.pattern = "Veins";
			marbleTwo.color = "White";
				System.out.println();
				System.out.println("Marble two details : ");
				System.out.println("id of marble is : " + marbleTwo.marbleId);
				System.out.println("name of the marble is : " + marbleTwo.marbleName);
				System.out.println("texture of the marble is : " + marbleTwo.texture);
				System.out.println("porosity of the marble is : " + marbleTwo.porosity);
				System.out.println("color of the marble is : " + marbleTwo.color);
				System.out.println("pattern of the marble is : " + marbleTwo.pattern);

			Marble marbleThree = new Marble();
			marbleThree.marbleId = 3;
			marbleThree.marbleName = "Emperador";
			marbleThree.texture = "Glossy";
			marbleThree.porosity = "Low";
			marbleThree.pattern = "Grains";
			marbleThree.color = "Brown";
				System.out.println();
				System.out.println("Marble three details : ");
				System.out.println("id of marble is : " + marbleThree.marbleId);
				System.out.println("name of the marble is : " + marbleThree.marbleName);
				System.out.println("texture of the marble is : " + marbleThree.texture);
				System.out.println("porosity of the marble is : " + marbleThree.porosity);
				System.out.println("color of the marble is : " + marbleThree.color);
				System.out.println("pattern of the marble is : " + marbleThree.pattern);

			Marble marbleFour = new Marble();
			marbleFour.marbleId = 4;
			marbleFour.marbleName = "Statuario";
			marbleFour.texture = "Smooth";
			marbleFour.porosity = "Medium";
			marbleFour.pattern = "Linear Veins";
			marbleFour.color = "White-Grey";
				System.out.println();
				System.out.println("Marble four details : ");
				System.out.println("id of marble is : " + marbleFour.marbleId);
				System.out.println("name of the marble is : " + marbleFour.marbleName);
				System.out.println("texture of the marble is : " + marbleFour.texture);
				System.out.println("porosity of the marble is : " + marbleFour.porosity);
				System.out.println("color of the marble is : " + marbleFour.color);
				System.out.println("pattern of the marble is : " + marbleFour.pattern);
			
			Marble marbleFive = new Marble();
			marbleFive.marbleId = 5;
			marbleFive.marbleName = "Makrana";
			marbleFive.texture = "Matte";
			marbleFive.porosity = "Low";
			marbleFive.pattern = "Plain";
			marbleFive.color = "White";
				System.out.println();
				System.out.println("Marble five details : ");
				System.out.println("id of marble is : " + marbleFive.marbleId);
				System.out.println("name of the marble is : " + marbleFive.marbleName);
				System.out.println("texture of the marble is : " + marbleFive.texture);
				System.out.println("porosity of the marble is : " + marbleFive.porosity);
				System.out.println("color of the marble is : " + marbleFive.color);
				System.out.println("pattern of the marble is : " + marbleFive.pattern);

			Marble marbleSix = new Marble();
			marbleSix.marbleId = 6;
			marbleSix.marbleName = "Rainforest Brown";
			marbleSix.texture = "Rough";
			marbleSix.porosity = "High";
			marbleSix.pattern = "Tree-like";
			marbleSix.color = "Brown";
				System.out.println();
				System.out.println("Marble six details : ");
				System.out.println("id of marble is : " + marbleSix.marbleId);
				System.out.println("name of the marble is : " + marbleSix.marbleName);
				System.out.println("texture of the marble is : " + marbleSix.texture);
				System.out.println("porosity of the marble is : " + marbleSix.porosity);
				System.out.println("color of the marble is : " + marbleSix.color);
				System.out.println("pattern of the marble is : " + marbleSix.pattern);

			Marble marbleSeven = new Marble();
			marbleSeven.marbleId = 7;
			marbleSeven.marbleName = "Nero Marquina";
			marbleSeven.texture = "Polished";
			marbleSeven.porosity = "Medium";
			marbleSeven.pattern = "White Veins";
			marbleSeven.color = "Black";
				System.out.println();
				System.out.println("Marble seven details : ");
				System.out.println("id of marble is : " + marbleSeven.marbleId);
				System.out.println("name of the marble is : " + marbleSeven.marbleName);
				System.out.println("texture of the marble is : " + marbleSeven.texture);
				System.out.println("porosity of the marble is : " + marbleSeven.porosity);
				System.out.println("color of the marble is : " + marbleSeven.color);
				System.out.println("pattern of the marble is : " + marbleSeven.pattern);

			Marble marbleEight = new Marble();
			marbleEight.marbleId = 8;
			marbleEight.marbleName = "Crema Marfil";
			marbleEight.texture = "Smooth";
			marbleEight.porosity = "Medium";
			marbleEight.pattern = "Light Veins";
			marbleEight.color = "Beige";
				System.out.println();
				System.out.println("Marble eight details : ");
				System.out.println("id of marble is : " + marbleEight.marbleId);
				System.out.println("name of the marble is : " + marbleEight.marbleName);
				System.out.println("texture of the marble is : " + marbleEight.texture);
				System.out.println("porosity of the marble is : " + marbleEight.porosity);
				System.out.println("color of the marble is : " + marbleEight.color);
				System.out.println("pattern of the marble is : " + marbleEight.pattern);

			Marble marbleNine = new Marble();
			marbleNine.marbleId = 9;
			marbleNine.marbleName = "Indian Green";
			marbleNine.texture = "Glossy";
			marbleNine.porosity = "Low";
			marbleNine.pattern = "Random";
			marbleNine.color = "Green";
				System.out.println();
				System.out.println("Marble nine details : ");
				System.out.println("id of marble is : " + marbleNine.marbleId);
				System.out.println("name of the marble is : " + marbleNine.marbleName);
				System.out.println("texture of the marble is : " + marbleNine.texture);
				System.out.println("porosity of the marble is : " + marbleNine.porosity);
				System.out.println("color of the marble is : " + marbleNine.color);
				System.out.println("pattern of the marble is : " + marbleNine.pattern);

			Marble marbleTen = new Marble();
			marbleTen.marbleId = 10;
			marbleTen.marbleName = "Pietra Grey";
			marbleTen.texture = "Polished";
			marbleTen.porosity = "Low";
			marbleTen.pattern = "White Streaks";
			marbleTen.color = "Dark Grey";
				System.out.println();
				System.out.println("Marble ten details : ");
				System.out.println("id of marble is : " + marbleTen.marbleId);
				System.out.println("name of the marble is : " + marbleTen.marbleName);
				System.out.println("texture of the marble is : " + marbleTen.texture);
				System.out.println("porosity of the marble is : " + marbleTen.porosity);
				System.out.println("color of the marble is : " + marbleTen.color);
				System.out.println("pattern of the marble is : " + marbleTen.pattern);

			Marble marbleEleven = new Marble();
			marbleEleven.marbleId = 11;
			marbleEleven.marbleName = "Thassos White";
			marbleEleven.texture = "Crystal-like";
			marbleEleven.porosity = "Very Low";
			marbleEleven.pattern = "Plain";
			marbleEleven.color = "Bright White";
				System.out.println();
				System.out.println("Marble eleven details : ");
				System.out.println("id of marble is : " + marbleEleven.marbleId);
				System.out.println("name of the marble is : " + marbleEleven.marbleName);
				System.out.println("texture of the marble is : " + marbleEleven.texture);
				System.out.println("porosity of the marble is : " + marbleEleven.porosity);
				System.out.println("color of the marble is : " + marbleEleven.color);
				System.out.println("pattern of the marble is : " + marbleEleven.pattern);

			Marble marbleTwelve = new Marble();
			marbleTwelve.marbleId = 12;
			marbleTwelve.marbleName = "Dark Emperador";
			marbleTwelve.texture = "Polished";
			marbleTwelve.porosity = "Medium";
			marbleTwelve.pattern = "Spider Veins";
			marbleTwelve.color = "Dark Brown";
				System.out.println();
				System.out.println("Marble twelve details : ");
				System.out.println("id of marble is : " + marbleTwelve.marbleId);
				System.out.println("name of the marble is : " + marbleTwelve.marbleName);
				System.out.println("texture of the marble is : " + marbleTwelve.texture);
				System.out.println("porosity of the marble is : " + marbleTwelve.porosity);
				System.out.println("color of the marble is : " + marbleTwelve.color);
				System.out.println("pattern of the marble is : " + marbleTwelve.pattern);

			Marble marbleThirteen = new Marble();
			marbleThirteen.marbleId = 13;
			marbleThirteen.marbleName = "Botticino";
			marbleThirteen.texture = "Smooth";
			marbleThirteen.porosity = "Low";
			marbleThirteen.pattern = "Cloudy";
			marbleThirteen.color = "Cream";
				System.out.println();
				System.out.println("Marble thirteen details : ");
				System.out.println("id of marble is : " + marbleThirteen.marbleId);
				System.out.println("name of the marble is : " + marbleThirteen.marbleName);
				System.out.println("texture of the marble is : " + marbleThirteen.texture);
				System.out.println("porosity of the marble is : " + marbleThirteen.porosity);
				System.out.println("color of the marble is : " + marbleThirteen.color);
				System.out.println("pattern of the marble is : " + marbleThirteen.pattern);

			Marble marbleFourteen = new Marble();
			marbleFourteen.marbleId = 14;
			marbleFourteen.marbleName = "Spider Green";
			marbleFourteen.texture = "Rough";
			marbleFourteen.porosity = "High";
			marbleFourteen.pattern = "Web Veins";
			marbleFourteen.color = "Dark Green";
				System.out.println();
				System.out.println("Marble fourteen details : ");
				System.out.println("id of marble is : " + marbleFourteen.marbleId);
				System.out.println("name of the marble is : " + marbleFourteen.marbleName);
				System.out.println("texture of the marble is : " + marbleFourteen.texture);
				System.out.println("porosity of the marble is : " + marbleFourteen.porosity);
				System.out.println("color of the marble is : " + marbleFourteen.color);
				System.out.println("pattern of the marble is : " + marbleFourteen.pattern);

			Marble marbleFifteen = new Marble();
			marbleFifteen.marbleId = 15;
			marbleFifteen.marbleName = "Volakas";
			marbleFifteen.texture = "Polished";
			marbleFifteen.porosity = "Medium";
			marbleFifteen.pattern = "Diagonal Veins";
			marbleFifteen.color = "White-Grey";
				System.out.println();
				System.out.println("Marble fifteen details : ");
				System.out.println("id of marble is : " + marbleFifteen.marbleId);
				System.out.println("name of the marble is : " + marbleFifteen.marbleName);
				System.out.println("texture of the marble is : " + marbleFifteen.texture);
				System.out.println("porosity of the marble is : " + marbleFifteen.porosity);
				System.out.println("color of the marble is : " + marbleFifteen.color);
				System.out.println("pattern of the marble is : " + marbleFifteen.pattern);

			Marble marbleSixteen = new Marble();
			marbleSixteen.marbleId = 16;
			marbleSixteen.marbleName = "Mystery White";
			marbleSixteen.texture = "Soft";
			marbleSixteen.porosity = "Low";
			marbleSixteen.pattern = "Faint Veins";
			marbleSixteen.color = "Off White";
				System.out.println();
				System.out.println("Marble sixteen details : ");
				System.out.println("id of marble is : " + marbleSixteen.marbleId);
				System.out.println("name of the marble is : " + marbleSixteen.marbleName);
				System.out.println("texture of the marble is : " + marbleSixteen.texture);
				System.out.println("porosity of the marble is : " + marbleSixteen.porosity);
				System.out.println("color of the marble is : " + marbleSixteen.color);
				System.out.println("pattern of the marble is : " + marbleSixteen.pattern);

			Marble marbleSeventeen = new Marble();
			marbleSeventeen.marbleId = 17;
			marbleSeventeen.marbleName = "Rosso Levanto";
			marbleSeventeen.texture = "Glossy";
			marbleSeventeen.porosity = "Medium";
			marbleSeventeen.pattern = "White Veins";
			marbleSeventeen.color = "Red-Brown";
				System.out.println();
				System.out.println("Marble seventeen details : ");
				System.out.println("id of marble is : " + marbleSeventeen.marbleId);
				System.out.println("name of the marble is : " + marbleSeventeen.marbleName);
				System.out.println("texture of the marble is : " + marbleSeventeen.texture);
				System.out.println("porosity of the marble is : " + marbleSeventeen.porosity);
				System.out.println("color of the marble is : " + marbleSeventeen.color);
				System.out.println("pattern of the marble is : " + marbleSeventeen.pattern);

			Marble marbleEighteen = new Marble();
			marbleEighteen.marbleId = 18;
			marbleEighteen.marbleName = "Golden Spider";
			marbleEighteen.texture = "Polished";
			marbleEighteen.porosity = "High";
			marbleEighteen.pattern = "Golden Veins";
			marbleEighteen.color = "Ivory";
				System.out.println();
				System.out.println("Marble eighteen details : ");
				System.out.println("id of marble is : " + marbleEighteen.marbleId);
				System.out.println("name of the marble is : " + marbleEighteen.marbleName);
				System.out.println("texture of the marble is : " + marbleEighteen.texture);
				System.out.println("porosity of the marble is : " + marbleEighteen.porosity);
				System.out.println("color of the marble is : " + marbleEighteen.color);
				System.out.println("pattern of the marble is : " + marbleEighteen.pattern);

			Marble marbleNineteen = new Marble();
			marbleNineteen.marbleId = 19;
			marbleNineteen.marbleName = "Pink Marble";
			marbleNineteen.texture = "Smooth";
			marbleNineteen.porosity = "Low";
			marbleNineteen.pattern = "Wavy";
			marbleNineteen.color = "Pink";
				System.out.println();
				System.out.println("Marble nineteen details : ");
				System.out.println("id of marble is : " + marbleNineteen.marbleId);
				System.out.println("name of the marble is : " + marbleNineteen.marbleName);
				System.out.println("texture of the marble is : " + marbleNineteen.texture);
				System.out.println("porosity of the marble is : " + marbleNineteen.porosity);
				System.out.println("color of the marble is : " + marbleNineteen.color);
				System.out.println("pattern of the marble is : " + marbleNineteen.pattern);

			Marble marbleTwenty = new Marble();
			marbleTwenty.marbleId = 20;
			marbleTwenty.marbleName = "Black Marquina";
			marbleTwenty.texture = "High Gloss";
			marbleTwenty.porosity = "Low";
			marbleTwenty.pattern = "Sharp Veins";
			marbleTwenty.color = "Jet Black";
				System.out.println();
				System.out.println("Marble twenty details : ");
				System.out.println("id of marble is : " + marbleTwenty.marbleId);
				System.out.println("name of the marble is : " + marbleTwenty.marbleName);
				System.out.println("texture of the marble is : " + marbleTwenty.texture);
				System.out.println("porosity of the marble is : " + marbleTwenty.porosity);
				System.out.println("color of the marble is : " + marbleTwenty.color);
				System.out.println("pattern of the marble is : " + marbleTwenty.pattern);

		System.out.println("main ended");	
		}

}