class PipeRunner{
	public static void main(String[] pipe){
		System.out.println("main started");
			Pipe pipeOne=new Pipe();
			pipeOne.pipeId=1;
			pipeOne.pipeMaterial="PVC";
			pipeOne.length=3;
			pipeOne.flowRate=30;
			pipeOne.color="Green";
			pipeOne.cost=300.0;
				System.out.println();
				System.out.println("pipe one details : ");
				System.out.println("id of pipe is : "+pipeOne.pipeId);
				System.out.println("material of the type is : "+pipeOne.pipeMaterial);
				System.out.println("length of the pipe is : "+pipeOne.length+" m");
				System.out.println("flowRate of the pipe is : "+pipeOne.flowRate+" L/min");
				System.out.println("color of the pipe is : "+pipeOne.color);
				System.out.println("cost of the pipe is : "+pipeOne.cost);
			
			Pipe pipeTwo = new Pipe();
			pipeTwo.pipeId = 2;
			pipeTwo.pipeMaterial = "Copper";
			pipeTwo.length = 2;
			pipeTwo.flowRate = 50;
			pipeTwo.color = "Brown";
			pipeTwo.cost = 850.0;
				System.out.println();
				System.out.println("pipe two details : ");
				System.out.println("id of pipe is : " + pipeTwo.pipeId);
				System.out.println("material of the type is : " + pipeTwo.pipeMaterial);
				System.out.println("length of the pipe is : " + pipeTwo.length + " m");
				System.out.println("flowRate of the pipe is : " + pipeTwo.flowRate + " L/min");
				System.out.println("color of the pipe is : " + pipeTwo.color);
				System.out.println("cost of the pipe is : " + pipeTwo.cost);

			Pipe pipeThree = new Pipe();
			pipeThree.pipeId = 3;
			pipeThree.pipeMaterial = "Steel";
			pipeThree.length = 5;
			pipeThree.flowRate = 70;
			pipeThree.color = "Silver";
			pipeThree.cost = 1200.0;
				System.out.println();
				System.out.println("pipe three details : ");
				System.out.println("id of pipe is : " + pipeThree.pipeId);
				System.out.println("material of the type is : " + pipeThree.pipeMaterial);
				System.out.println("length of the pipe is : " + pipeThree.length + " m");
				System.out.println("flowRate of the pipe is : " + pipeThree.flowRate + " L/min");
				System.out.println("color of the pipe is : " + pipeThree.color);
				System.out.println("cost of the pipe is : " + pipeThree.cost);

			Pipe pipeFour = new Pipe();
			pipeFour.pipeId = 4;
			pipeFour.pipeMaterial = "Iron";
			pipeFour.length = 4;
			pipeFour.flowRate = 40;
			pipeFour.color = "Black";
			pipeFour.cost = 950.0;
				System.out.println();
				System.out.println("pipe four details : ");
				System.out.println("id of pipe is : " + pipeFour.pipeId);
				System.out.println("material of the type is : " + pipeFour.pipeMaterial);
				System.out.println("length of the pipe is : " + pipeFour.length + " m");
				System.out.println("flowRate of the pipe is : " + pipeFour.flowRate + " L/min");
				System.out.println("color of the pipe is : " + pipeFour.color);
				System.out.println("cost of the pipe is : " + pipeFour.cost);

			Pipe pipeFive = new Pipe();
			pipeFive.pipeId = 5;
			pipeFive.pipeMaterial = "HDPE";
			pipeFive.length = 6;
			pipeFive.flowRate = 60;
			pipeFive.color = "Blue";
			pipeFive.cost = 1100.0;
				System.out.println();
				System.out.println("pipe five details : ");
				System.out.println("id of pipe is : " + pipeFive.pipeId);
				System.out.println("material of the type is : " + pipeFive.pipeMaterial);
				System.out.println("length of the pipe is : " + pipeFive.length + " m");
				System.out.println("flowRate of the pipe is : " + pipeFive.flowRate + " L/min");
				System.out.println("color of the pipe is : " + pipeFive.color);
				System.out.println("cost of the pipe is : " + pipeFive.cost);

			Pipe pipeSix = new Pipe();
			pipeSix.pipeId = 6;
			pipeSix.pipeMaterial = "Concrete";
			pipeSix.length = 8;
			pipeSix.flowRate = 80;
			pipeSix.color = "Grey";
			pipeSix.cost = 1600.0;
				System.out.println();
				System.out.println("pipe six details : ");
				System.out.println("id of pipe is : " + pipeSix.pipeId);
				System.out.println("material of the type is : " + pipeSix.pipeMaterial);
				System.out.println("length of the pipe is : " + pipeSix.length + " m");
				System.out.println("flowRate of the pipe is : " + pipeSix.flowRate + " L/min");
				System.out.println("color of the pipe is : " + pipeSix.color);
				System.out.println("cost of the pipe is : " + pipeSix.cost);

			Pipe pipeSeven = new Pipe();
			pipeSeven.pipeId = 7;
			pipeSeven.pipeMaterial = "Glass";
			pipeSeven.length = 2;
			pipeSeven.flowRate = 25;
			pipeSeven.color = "Transparent";
			pipeSeven.cost = 700.0;
				System.out.println();
				System.out.println("pipe seven details : ");
				System.out.println("id of pipe is : " + pipeSeven.pipeId);
				System.out.println("material of the type is : " + pipeSeven.pipeMaterial);
				System.out.println("length of the pipe is : " + pipeSeven.length + " m");
				System.out.println("flowRate of the pipe is : " + pipeSeven.flowRate + " L/min");
				System.out.println("color of the pipe is : " + pipeSeven.color);
				System.out.println("cost of the pipe is : " + pipeSeven.cost);

			Pipe pipeEight = new Pipe();
			pipeEight.pipeId = 8;
			pipeEight.pipeMaterial = "Rubber";
			pipeEight.length = 3;
			pipeEight.flowRate = 35;
			pipeEight.color = "Black";
			pipeEight.cost = 400.0;
				System.out.println();
				System.out.println("pipe eight details : ");
				System.out.println("id of pipe is : " + pipeEight.pipeId);
				System.out.println("material of the type is : " + pipeEight.pipeMaterial);
				System.out.println("length of the pipe is : " + pipeEight.length + " m");
				System.out.println("flowRate of the pipe is : " + pipeEight.flowRate + " L/min");
				System.out.println("color of the pipe is : " + pipeEight.color);
				System.out.println("cost of the pipe is : " + pipeEight.cost);

			Pipe pipeNine = new Pipe();
			pipeNine.pipeId = 9;
			pipeNine.pipeMaterial = "Aluminum";
			pipeNine.length = 6;
			pipeNine.flowRate = 65;
			pipeNine.color = "Silver";
			pipeNine.cost = 1300.0;
				System.out.println();
				System.out.println("pipe nine details : ");
				System.out.println("id of pipe is : " + pipeNine.pipeId);
				System.out.println("material of the type is : " + pipeNine.pipeMaterial);
				System.out.println("length of the pipe is : " + pipeNine.length + " m");
				System.out.println("flowRate of the pipe is : " + pipeNine.flowRate + " L/min");
				System.out.println("color of the pipe is : " + pipeNine.color);
				System.out.println("cost of the pipe is : " + pipeNine.cost);

			Pipe pipeTen = new Pipe();
			pipeTen.pipeId = 10;
			pipeTen.pipeMaterial = "Brass";
			pipeTen.length = 5;
			pipeTen.flowRate = 55;
			pipeTen.color = "Gold";
			pipeTen.cost = 1400.0;
				System.out.println();
				System.out.println("pipe ten details : ");
				System.out.println("id of pipe is : " + pipeTen.pipeId);
				System.out.println("material of the type is : " + pipeTen.pipeMaterial);
				System.out.println("length of the pipe is : " + pipeTen.length + " m");
				System.out.println("flowRate of the pipe is : " + pipeTen.flowRate + " L/min");
				System.out.println("color of the pipe is : " + pipeTen.color);
				System.out.println("cost of the pipe is : " + pipeTen.cost);

			Pipe pipeEleven = new Pipe();
			pipeEleven.pipeId = 11;
			pipeEleven.pipeMaterial = "Fiber";
			pipeEleven.length = 4;
			pipeEleven.flowRate = 45;
			pipeEleven.color = "White";
			pipeEleven.cost = 1000.0;
				System.out.println();
				System.out.println("pipe eleven details : ");
				System.out.println("id of pipe is : " + pipeEleven.pipeId);
				System.out.println("material of the type is : " + pipeEleven.pipeMaterial);
				System.out.println("length of the pipe is : " + pipeEleven.length + " m");
				System.out.println("flowRate of the pipe is : " + pipeEleven.flowRate + " L/min");
				System.out.println("color of the pipe is : " + pipeEleven.color);
				System.out.println("cost of the pipe is : " + pipeEleven.cost);

			Pipe pipeTwelve = new Pipe();
			pipeTwelve.pipeId = 12;
			pipeTwelve.pipeMaterial = "Plastic";
			pipeTwelve.length = 3;
			pipeTwelve.flowRate = 40;
			pipeTwelve.color = "Blue";
			pipeTwelve.cost = 500.0;
				System.out.println();
				System.out.println("pipe twelve details : ");
				System.out.println("id of pipe is : " + pipeTwelve.pipeId);
				System.out.println("material of the type is : " + pipeTwelve.pipeMaterial);
				System.out.println("length of the pipe is : " + pipeTwelve.length + " m");
				System.out.println("flowRate of the pipe is : " + pipeTwelve.flowRate + " L/min");
				System.out.println("color of the pipe is : " + pipeTwelve.color);
				System.out.println("cost of the pipe is : " + pipeTwelve.cost);

			Pipe pipeThirteen = new Pipe();
			pipeThirteen.pipeId = 13;
			pipeThirteen.pipeMaterial = "Carbon Steel";
			pipeThirteen.length = 6;
			pipeThirteen.flowRate = 75;
			pipeThirteen.color = "Dark Grey";
			pipeThirteen.cost = 1350.0;
				System.out.println();
				System.out.println("pipe thirteen details : ");
				System.out.println("id of pipe is : " + pipeThirteen.pipeId);
				System.out.println("material of the type is : " + pipeThirteen.pipeMaterial);
				System.out.println("length of the pipe is : " + pipeThirteen.length + " m");
				System.out.println("flowRate of the pipe is : " + pipeThirteen.flowRate + " L/min");
				System.out.println("color of the pipe is : " + pipeThirteen.color);
				System.out.println("cost of the pipe is : " + pipeThirteen.cost);

			Pipe pipeFourteen = new Pipe();
			pipeFourteen.pipeId = 14;
			pipeFourteen.pipeMaterial = "Lead";
			pipeFourteen.length = 2;
			pipeFourteen.flowRate = 20;
			pipeFourteen.color = "Dull Grey";
			pipeFourteen.cost = 950.0;
				System.out.println();
				System.out.println("pipe fourteen details : ");
				System.out.println("id of pipe is : " + pipeFourteen.pipeId);
				System.out.println("material of the type is : " + pipeFourteen.pipeMaterial);
				System.out.println("length of the pipe is : " + pipeFourteen.length + " m");
				System.out.println("flowRate of the pipe is : " + pipeFourteen.flowRate + " L/min");
				System.out.println("color of the pipe is : " + pipeFourteen.color);
				System.out.println("cost of the pipe is : " + pipeFourteen.cost);

			Pipe pipeFifteen = new Pipe();
			pipeFifteen.pipeId = 15;
			pipeFifteen.pipeMaterial = "Acrylic";
			pipeFifteen.length = 5;
			pipeFifteen.flowRate = 60;
			pipeFifteen.color = "Red";
			pipeFifteen.cost = 900.0;
				System.out.println();
				System.out.println("pipe fifteen details : ");
				System.out.println("id of pipe is : " + pipeFifteen.pipeId);
				System.out.println("material of the type is : " + pipeFifteen.pipeMaterial);
				System.out.println("length of the pipe is : " + pipeFifteen.length + " m");
				System.out.println("flowRate of the pipe is : " + pipeFifteen.flowRate + " L/min");
				System.out.println("color of the pipe is : " + pipeFifteen.color);
				System.out.println("cost of the pipe is : " + pipeFifteen.cost);

			Pipe pipeSixteen = new Pipe();
			pipeSixteen.pipeId = 16;
			pipeSixteen.pipeMaterial = "Steel Alloy";
			pipeSixteen.length = 7;
			pipeSixteen.flowRate = 85;
			pipeSixteen.color = "Chrome";
			pipeSixteen.cost = 1700.0;
				System.out.println();
				System.out.println("pipe sixteen details : ");
				System.out.println("id of pipe is : " + pipeSixteen.pipeId);
				System.out.println("material of the type is : " + pipeSixteen.pipeMaterial);
				System.out.println("length of the pipe is : " + pipeSixteen.length + " m");
				System.out.println("flowRate of the pipe is : " + pipeSixteen.flowRate + " L/min");
				System.out.println("color of the pipe is : " + pipeSixteen.color);
				System.out.println("cost of the pipe is : " + pipeSixteen.cost);

			Pipe pipeSeventeen = new Pipe();
			pipeSeventeen.pipeId = 17;
			pipeSeventeen.pipeMaterial = "Ceramic";
			pipeSeventeen.length = 4;
			pipeSeventeen.flowRate = 35;
			pipeSeventeen.color = "Beige";
			pipeSeventeen.cost = 800.0;
				System.out.println();
				System.out.println("pipe seventeen details : ");
				System.out.println("id of pipe is : " + pipeSeventeen.pipeId);
				System.out.println("material of the type is : " + pipeSeventeen.pipeMaterial);
				System.out.println("length of the pipe is : " + pipeSeventeen.length + " m");
				System.out.println("flowRate of the pipe is : " + pipeSeventeen.flowRate + " L/min");
				System.out.println("color of the pipe is : " + pipeSeventeen.color);
				System.out.println("cost of the pipe is : " + pipeSeventeen.cost);

			Pipe pipeEighteen = new Pipe();
			pipeEighteen.pipeId = 18;
			pipeEighteen.pipeMaterial = "Teflon";
			pipeEighteen.length = 3;
			pipeEighteen.flowRate = 32;
			pipeEighteen.color = "White";
			pipeEighteen.cost = 950.0;
				System.out.println();
				System.out.println("pipe eighteen details : ");
				System.out.println("id of pipe is : " + pipeEighteen.pipeId);
				System.out.println("material of the type is : " + pipeEighteen.pipeMaterial);
				System.out.println("length of the pipe is : " + pipeEighteen.length + " m");
				System.out.println("flowRate of the pipe is : " + pipeEighteen.flowRate + " L/min");
				System.out.println("color of the pipe is : " + pipeEighteen.color);
				System.out.println("cost of the pipe is : " + pipeEighteen.cost);

			Pipe pipeNineteen = new Pipe();
			pipeNineteen.pipeId = 19;
			pipeNineteen.pipeMaterial = "Polypropylene";
			pipeNineteen.length = 5;
			pipeNineteen.flowRate = 48;
			pipeNineteen.color = "Yellow";
			pipeNineteen.cost = 870.0;
				System.out.println();
				System.out.println("pipe nineteen details : ");
				System.out.println("id of pipe is : " + pipeNineteen.pipeId);
				System.out.println("material of the type is : " + pipeNineteen.pipeMaterial);
				System.out.println("length of the pipe is : " + pipeNineteen.length + " m");
				System.out.println("flowRate of the pipe is : " + pipeNineteen.flowRate + " L/min");
				System.out.println("color of the pipe is : " + pipeNineteen.color);
				System.out.println("cost of the pipe is : " + pipeNineteen.cost);

			Pipe pipeTwenty = new Pipe();
			pipeTwenty.pipeId = 20;
			pipeTwenty.pipeMaterial = "Bronze";
			pipeTwenty.length = 6;
			pipeTwenty.flowRate = 68;
			pipeTwenty.color = "Bronze";
			pipeTwenty.cost = 1450.0;
				System.out.println();
				System.out.println("pipe twenty details : ");
				System.out.println("id of pipe is : " + pipeTwenty.pipeId);
				System.out.println("material of the type is : " + pipeTwenty.pipeMaterial);
				System.out.println("length of the pipe is : " + pipeTwenty.length + " m");
				System.out.println("flowRate of the pipe is : " + pipeTwenty.flowRate + " L/min");
				System.out.println("color of the pipe is : " + pipeTwenty.color);
				System.out.println("cost of the pipe is : " + pipeTwenty.cost);

		System.out.println("main ended");
	}

}