class PoliceStation{
	static String stationId;
	static String stationName;
	static String location;
	static long contactNumber;
	static String email;
	static String stationType;
	static String jurisdictionArea;
	static int 	totalOfficers;
	static int establishedyear;
	static int noOfCasesFiled;
	static int noOfCasesSolved;
	static boolean isOperational;
	static int noOfVehicles;
	static boolean hasCyberCrimeUnit;
	static boolean hasWomenHelpDesk;
	static int noOfCells;
	static String policeCommissionerZone;
	static boolean 	hasCCTVSurveillance;
	static int 	emergencyContactNumber;
	static String 	lastInspectionDate;
	public static void main(String policestation[]){
			System.out.println("The station id is "+stationId);
			System.out.println("The station name is "+stationName);
			System.out.println("The station is located at "+location);
			System.out.println("The contact number of the police station is "+contactNumber);
			System.out.println("The email id of  the police station is "+email);
			System.out.println("The type of the station is "+stationType);
			System.out.println("The jurisdiction area of this police station is "+jurisdictionArea);
			System.out.println("The total officers in this police station is "+totalOfficers);
			System.out.println("This police station was established in the year "+establishedyear);
			System.out.println("The number of cases filed are "+noOfCasesFiled);
			System.out.println("The number of cases solved are "+noOfCasesSolved);
			System.out.println("Is the police station operational? "+isOperational);
			System.out.println("The number of vehicles in this police station are "+noOfVehicles);
			System.out.println("does the police station has cyber crime unit? "+hasCyberCrimeUnit);
			System.out.println("does the police station has women help desk? "+hasWomenHelpDesk);
			System.out.println("The number of cells in this station are "+noOfCells);
			System.out.println("This station comes under the commisioner zone of "+policeCommissionerZone);
			System.out.println("does the police station has CCTV surveillance? "+hasCCTVSurveillance);
			System.out.println("The emergency contact number of this station is "+emergencyContactNumber);
			System.out.println("The last inspection date of this station is "+lastInspectionDate);
			System.out.println();
	 String stationId="PS102";
	 String stationName="MG Road Police Station";
	 String location = "MG Road, Bangalore";
	 long contactNumber=8023456789l;
	 String email="mgps@ksp.gov.in";
	 String stationType="Urban";
	 String jurisdictionArea="5 Km radius";
	 int 	totalOfficers= 45;
	 int establishedyear=1995;
	 int noOfCasesFiled=3540;
	 int noOfCasesSolved=2870;
	 boolean isOperational=true;
	 int noOfVehicles=6;
	 boolean hasCyberCrimeUnit= true;
	 boolean hasWomenHelpDesk=true;
	 int noOfCells=4;
	 String policeCommissionerZone="Zone 2";
	 boolean 	hasCCTVSurveillance=true;
	 int 	emergencyContactNumber=112;
	 String 	lastInspectionDate="2025-03-15";
		System.out.println("After re-initialization");
		System.out.println("The station id is "+stationId);
		System.out.println("The station name is "+stationName);
		System.out.println("The station is located at "+location);
		System.out.println("The contact number of the police station is "+contactNumber);
		System.out.println("The email id of  the police station is "+email);
		System.out.println("The type of the station is "+stationType);
		System.out.println("The jurisdiction area of this police station is "+jurisdictionArea);
		System.out.println("The total officers in this police station is "+totalOfficers);
		System.out.println("This police station was established in the year "+establishedyear);
		System.out.println("The number of cases filed are "+noOfCasesFiled);
		System.out.println("The number of cases solved are "+noOfCasesSolved);
		System.out.println("Is the police station operational? "+isOperational);
		System.out.println("The number of vehicles in this police station are "+noOfVehicles);
		System.out.println("does the police station has cyber crime unit? "+hasCyberCrimeUnit);
		System.out.println("does the police station has women help desk? "+hasWomenHelpDesk);
		System.out.println("The number of cells in this station are "+noOfCells);
		System.out.println("This station comes under the commisioner zone of "+policeCommissionerZone);
		System.out.println("does the police station has CCTV surveillance? "+hasCCTVSurveillance);
		System.out.println("The emergency contact number of this station is "+emergencyContactNumber);
		System.out.println("The last inspection date of this station is "+lastInspectionDate);
	
	}
}