class Projector{
	static String brandName;
	static double price;
	static String modelNumber;
	static String color;
	static double weight;
	static String mountType;
	static String lensType;
	static String resolution;
	static String contrastRatio;
	static int brightnessLumens;
	static String aspectRatio;
	static String displayTechnology;
	static double projectionDistance;
	static int screenSize;
	static int hmdiPorts;
	static int usbPort;
	static boolean isVgaPortAvailable;
	static int powerConsumption;
	static String controlType;
	static boolean isWifiEnabled;
	public static void main(String projector[]){
			System.out.println("The brand name of the projector is "+brandName);
			System.out.println("The price of the projector is "+price);
			System.out.println("The model number of the projector is "+modelNumber);
			System.out.println("The color of the projector is "+color);
			System.out.println("The weight of thr projector is "+weight+"Kg");
			System.out.println("The mount type of the projector is "+mountType);
			System.out.println("The lens type of the projector is "+lensType);
			System.out.println("The resolution of the projector is "+resolution);
			System.out.println("The contrast ratio of the projector is "+contrastRatio);		
			System.out.println("The brightness of the projector is "+brightnessLumens);
			System.out.println("The aspect ratio of the projector is "+aspectRatio);
			System.out.println("The display technology of the projector is "+displayTechnology);
			System.out.println("The projection distance is "+projectionDistance+"metres");
			System.out.println("The screen size of the projector is "+screenSize+"inches");
			System.out.println("The number of hdmi ports are "+hmdiPorts);
			System.out.println("The number of usb ports are "+usbPort);
			System.out.println("Is vga port available for the porjector? "+isVgaPortAvailable);
			System.out.println("The power consumption of the projector is "+powerConsumption+" Watts");
			System.out.println("The control type of the projector is "+controlType);
			System.out.println("Is wifi enabled for the projector "+isWifiEnabled);
			System.out.println();
	 String brandName="Epson";
	 double price=32000;
	 String modelNumber="EH-TW7100";
	 String color="Black";
	 double weight=6.9d;
	 String mountType="ceiling";
	 String lensType="zoom";
	 String resolution="1920x1080";
	 String contrastRatio="1000:1";
	 int brightnessLumens=3000;
	 String aspectRatio="16:9";
	 String displayTechnology="LCD";
	 double projectionDistance=2.5d;
	 int screenSize=120;
	 int hmdiPorts=2;
	 int usbPort=1;
	 boolean isVgaPortAvailable=true;
	 int powerConsumption=290;
	 String controlType="Remote control";
	 boolean isWifiEnabled=true;
		System.out.println("After re-initialization");
		System.out.println("The price of the projector is "+price);
		System.out.println("The model number of the projector is "+modelNumber);
		System.out.println("The color of the projector is "+color);
		System.out.println("The weight of thr projector is "+weight+"Kg");
		System.out.println("The mount type of the projector is "+mountType);
		System.out.println("The lens type of the projector is "+lensType);
		System.out.println("The resolution of the projector is "+resolution);
		System.out.println("The contrast ratio of the projector is "+contrastRatio);		
		System.out.println("The brightness of the projector is "+brightnessLumens);
		System.out.println("The aspect ratio of the projector is "+aspectRatio);
		System.out.println("The display technology of the projector is "+displayTechnology);
		System.out.println("The projection distance is "+projectionDistance+"metres");
		System.out.println("The screen size of the projector is "+screenSize+"inches");
		System.out.println("The number of hdmi ports are "+hmdiPorts);
		System.out.println("The number of usb ports are "+usbPort);
		System.out.println("Is vga port available for the porjector? "+isVgaPortAvailable);
		System.out.println("The power consumption of the projector is "+powerConsumption+" Watts");
		System.out.println("The control type of the projector is "+controlType);
		System.out.println("Is wifi enabled for the projector "+isWifiEnabled);
	
	}
}