class RodRunner{
	public static void main(String[] rod){
		System.out.println("main started");
			Rod rodOne = new Rod();
			rodOne.rodId=1;
			rodOne.rodMaterial="Steel";
			rodOne.rodLength=6;
			rodOne.isMagnetic=false;
			rodOne.weight=15.00;
			rodOne.price=150.00;
				System.out.println();
				System.out.println("Rod one details are : ");
				System.out.println("id of rod is : "+rodOne.rodId);
				System.out.println("material  of rod is : "+rodOne.rodMaterial);
				System.out.println("length of the rod is : "+rodOne.rodLength+" metres");
				System.out.println("is Magnetic? "+rodOne.isMagnetic);
				System.out.println("weight of the rod is : "+rodOne.weight+" Kg");
				System.out.println("price of the rod is : "+rodOne.price);
			
			Rod rodTwo = new Rod();
			rodTwo.rodId = 2;
			rodTwo.rodMaterial = "Aluminum";
			rodTwo.rodLength = 4;
			rodTwo.isMagnetic = false;
			rodTwo.weight = 8.5;
			rodTwo.price = 120.75;
				System.out.println();
				System.out.println("Rod two details are : ");
				System.out.println("id of rod is : " + rodTwo.rodId);
				System.out.println("material of rod is : " + rodTwo.rodMaterial);
				System.out.println("length of the rod is : " + rodTwo.rodLength + " metres");
				System.out.println("is Magnetic? " + rodTwo.isMagnetic);
				System.out.println("weight of the rod is : " + rodTwo.weight + " Kg");
				System.out.println("price of the rod is : " + rodTwo.price);

			Rod rodThree = new Rod();
			rodThree.rodId = 3;
			rodThree.rodMaterial = "Iron";
			rodThree.rodLength = 5;
			rodThree.isMagnetic = true;
			rodThree.weight = 13.2;
			rodThree.price = 135.50;
				System.out.println();
				System.out.println("Rod three details are : ");
				System.out.println("id of rod is : " + rodThree.rodId);
				System.out.println("material of rod is : " + rodThree.rodMaterial);
				System.out.println("length of the rod is : " + rodThree.rodLength + " metres");
				System.out.println("is Magnetic? " + rodThree.isMagnetic);
				System.out.println("weight of the rod is : " + rodThree.weight + " Kg");
				System.out.println("price of the rod is : " + rodThree.price);

			Rod rodFour = new Rod();
			rodFour.rodId = 4;
			rodFour.rodMaterial = "Carbon Fiber";
			rodFour.rodLength = 3;
			rodFour.isMagnetic = false;
			rodFour.weight = 5.0;
			rodFour.price = 200.00;
				System.out.println();
				System.out.println("Rod four details are : ");
				System.out.println("id of rod is : " + rodFour.rodId);
				System.out.println("material of rod is : " + rodFour.rodMaterial);
				System.out.println("length of the rod is : " + rodFour.rodLength + " metres");
				System.out.println("is Magnetic? " + rodFour.isMagnetic);
				System.out.println("weight of the rod is : " + rodFour.weight + " Kg");
				System.out.println("price of the rod is : " + rodFour.price);

			Rod rodFive = new Rod();
			rodFive.rodId = 5;
			rodFive.rodMaterial = "Titanium";
			rodFive.rodLength = 7;
			rodFive.isMagnetic = false;
			rodFive.weight = 10.0;
			rodFive.price = 350.99;
				System.out.println();
				System.out.println("Rod five details are : ");
				System.out.println("id of rod is : " + rodFive.rodId);
				System.out.println("material of rod is : " + rodFive.rodMaterial);
				System.out.println("length of the rod is : " + rodFive.rodLength + " metres");
				System.out.println("is Magnetic? " + rodFive.isMagnetic);
				System.out.println("weight of the rod is : " + rodFive.weight + " Kg");
				System.out.println("price of the rod is :  "+rodFive.price);

			Rod rodSix = new Rod();
			rodSix.rodId = 6;
			rodSix.rodMaterial = "Copper";
			rodSix.rodLength = 4;
			rodSix.isMagnetic = false;
			rodSix.weight = 11.3;
			rodSix.price = 180.25;
				System.out.println();
				System.out.println("Rod six details are : ");
				System.out.println("id of rod is : " + rodSix.rodId);
				System.out.println("material of rod is : " + rodSix.rodMaterial);
				System.out.println("length of the rod is : " + rodSix.rodLength + " metres");
				System.out.println("is Magnetic? " + rodSix.isMagnetic);
				System.out.println("weight of the rod is : " + rodSix.weight + " Kg");
				System.out.println("price of the rod is : " + rodSix.price);

			Rod rodSeven = new Rod();
			rodSeven.rodId = 7;
			rodSeven.rodMaterial = "Brass";
			rodSeven.rodLength = 5;
			rodSeven.isMagnetic = false;
			rodSeven.weight = 9.6;
			rodSeven.price = 165.00;
				System.out.println();
				System.out.println("Rod seven details are : ");
				System.out.println("id of rod is : " + rodSeven.rodId);
				System.out.println("material of rod is : " + rodSeven.rodMaterial);
				System.out.println("length of the rod is : " + rodSeven.rodLength + " metres");
				System.out.println("is Magnetic? " + rodSeven.isMagnetic);
				System.out.println("weight of the rod is : " + rodSeven.weight + " Kg");
				System.out.println("price of the rod is : " + rodSeven.price);

			Rod rodEight = new Rod();
			rodEight.rodId = 8;
			rodEight.rodMaterial = "Graphite";
			rodEight.rodLength = 6;
			rodEight.isMagnetic = false;
			rodEight.weight = 7.4;
			rodEight.price = 140.10;
				System.out.println();
				System.out.println("Rod eight details are : ");
				System.out.println("id of rod is : " + rodEight.rodId);
				System.out.println("material of rod is : " + rodEight.rodMaterial);
				System.out.println("length of the rod is : " + rodEight.rodLength + " metres");
				System.out.println("is Magnetic? " + rodEight.isMagnetic);
				System.out.println("weight of the rod is : " + rodEight.weight + " Kg");
				System.out.println("price of the rod is : " + rodEight.price);

			Rod rodNine = new Rod();
			rodNine.rodId = 9;
			rodNine.rodMaterial = "Plastic";
			rodNine.rodLength = 3;
			rodNine.isMagnetic = false;
			rodNine.weight = 3.2;
			rodNine.price = 75.00;
				System.out.println();
				System.out.println("Rod nine details are : ");
				System.out.println("id of rod is : " + rodNine.rodId);
				System.out.println("material of rod is : " + rodNine.rodMaterial);
				System.out.println("length of the rod is : " + rodNine.rodLength + " metres");
				System.out.println("is Magnetic? " + rodNine.isMagnetic);
				System.out.println("weight of the rod is : " + rodNine.weight + " Kg");
				System.out.println("price of the rod is : " + rodNine.price);

			Rod rodTen = new Rod();
			rodTen.rodId = 10;
			rodTen.rodMaterial = "Nickel";
			rodTen.rodLength = 4;
			rodTen.isMagnetic = true;
			rodTen.weight = 10.8;
			rodTen.price = 210.60;
				System.out.println();
				System.out.println("Rod ten details are : ");
				System.out.println("id of rod is : " + rodTen.rodId);
				System.out.println("material of rod is : " + rodTen.rodMaterial);
				System.out.println("length of the rod is : " + rodTen.rodLength + " metres");
				System.out.println("is Magnetic? " + rodTen.isMagnetic);
				System.out.println("weight of the rod is : " + rodTen.weight + " Kg");
				System.out.println("price of the rod is : " + rodTen.price);


			Rod rodEleven = new Rod();
			rodEleven.rodId = 11;
			rodEleven.rodMaterial = "Titanium";
			rodEleven.rodLength = 5;
			rodEleven.isMagnetic = false;
			rodEleven.weight = 6.5;
			rodEleven.price = 320.75;
				System.out.println();
				System.out.println("Rod eleven details are : ");
				System.out.println("id of rod is : " + rodEleven.rodId);
				System.out.println("material of rod is : " + rodEleven.rodMaterial);
				System.out.println("length of the rod is : " + rodEleven.rodLength + " metres");
				System.out.println("is Magnetic? " + rodEleven.isMagnetic);
				System.out.println("weight of the rod is : " + rodEleven.weight + " Kg");
				System.out.println("price of the rod is : " + rodEleven.price);

			Rod rodTwelve = new Rod();
			rodTwelve.rodId = 12;
			rodTwelve.rodMaterial = "Zinc";
			rodTwelve.rodLength = 4;
			rodTwelve.isMagnetic = false;
			rodTwelve.weight = 8.2;
			rodTwelve.price = 135.50;
				System.out.println();
				System.out.println("Rod twelve details are : ");
				System.out.println("id of rod is : " + rodTwelve.rodId);
				System.out.println("material of rod is : " + rodTwelve.rodMaterial);
				System.out.println("length of the rod is : " + rodTwelve.rodLength + " metres");
				System.out.println("is Magnetic? " + rodTwelve.isMagnetic);
				System.out.println("weight of the rod is : " + rodTwelve.weight + " Kg");
				System.out.println("price of the rod is : " + rodTwelve.price);

			Rod rodThirteen = new Rod();
			rodThirteen.rodId = 13;
			rodThirteen.rodMaterial = "Carbon Fiber";
			rodThirteen.rodLength = 6;
			rodThirteen.isMagnetic = false;
			rodThirteen.weight = 5.7;
			rodThirteen.price = 410.00;
				System.out.println();
				System.out.println("Rod thirteen details are : ");
				System.out.println("id of rod is : " + rodThirteen.rodId);
				System.out.println("material of rod is : " + rodThirteen.rodMaterial);
				System.out.println("length of the rod is : " + rodThirteen.rodLength + " metres");
				System.out.println("is Magnetic? " + rodThirteen.isMagnetic);
				System.out.println("weight of the rod is : " + rodThirteen.weight + " Kg");
				System.out.println("price of the rod is : " + rodThirteen.price);

			Rod rodFourteen = new Rod();
			rodFourteen.rodId = 14;
			rodFourteen.rodMaterial = "Chromium";
			rodFourteen.rodLength = 5;
			rodFourteen.isMagnetic = true;
			rodFourteen.weight = 10.0;
			rodFourteen.price = 250.25;
				System.out.println();
				System.out.println("Rod fourteen details are : ");
				System.out.println("id of rod is : " + rodFourteen.rodId);
				System.out.println("material of rod is : " + rodFourteen.rodMaterial);
				System.out.println("length of the rod is : " + rodFourteen.rodLength + " metres");
				System.out.println("is Magnetic? " + rodFourteen.isMagnetic);
				System.out.println("weight of the rod is : " + rodFourteen.weight + " Kg");
				System.out.println("price of the rod is : " + rodFourteen.price);

			Rod rodFifteen = new Rod();
			rodFifteen.rodId = 15;
			rodFifteen.rodMaterial = "Aluminium";
			rodFifteen.rodLength = 3;
			rodFifteen.isMagnetic = false;
			rodFifteen.weight = 4.6;
			rodFifteen.price = 120.00;
				System.out.println();
				System.out.println("Rod fifteen details are : ");
				System.out.println("id of rod is : " + rodFifteen.rodId);
				System.out.println("material of rod is : " + rodFifteen.rodMaterial);
				System.out.println("length of the rod is : " + rodFifteen.rodLength + " metres");
				System.out.println("is Magnetic? " + rodFifteen.isMagnetic);
				System.out.println("weight of the rod is : " + rodFifteen.weight + " Kg");
				System.out.println("price of the rod is : " + rodFifteen.price);

			Rod rodSixteen = new Rod();
			rodSixteen.rodId = 16;
			rodSixteen.rodMaterial = "Lead";
			rodSixteen.rodLength = 2;
			rodSixteen.isMagnetic = false;
			rodSixteen.weight = 13.2;
			rodSixteen.price = 160.80;
				System.out.println();
				System.out.println("Rod sixteen details are : ");
				System.out.println("id of rod is : " + rodSixteen.rodId);
				System.out.println("material of rod is : " + rodSixteen.rodMaterial);
				System.out.println("length of the rod is : " + rodSixteen.rodLength + " metres");
				System.out.println("is Magnetic? " + rodSixteen.isMagnetic);
				System.out.println("weight of the rod is : " + rodSixteen.weight + " Kg");
				System.out.println("price of the rod is : " + rodSixteen.price);

			Rod rodSeventeen = new Rod();
			rodSeventeen.rodId = 17;
			rodSeventeen.rodMaterial = "Cast Iron";
			rodSeventeen.rodLength = 6;
			rodSeventeen.isMagnetic = true;
			rodSeventeen.weight = 17.9;
			rodSeventeen.price = 190.00;
				System.out.println();
				System.out.println("Rod seventeen details are : ");
				System.out.println("id of rod is : " + rodSeventeen.rodId);
				System.out.println("material of rod is : " + rodSeventeen.rodMaterial);
				System.out.println("length of the rod is : " + rodSeventeen.rodLength + " metres");
				System.out.println("is Magnetic? " + rodSeventeen.isMagnetic);
				System.out.println("weight of the rod is : " + rodSeventeen.weight + " Kg");
				System.out.println("price of the rod is : " + rodSeventeen.price);

			Rod rodEighteen = new Rod();
			rodEighteen.rodId = 18;
			rodEighteen.rodMaterial = "Tin";
			rodEighteen.rodLength = 3;
			rodEighteen.isMagnetic = false;
			rodEighteen.weight = 6.8;
			rodEighteen.price = 85.60;
				System.out.println();
				System.out.println("Rod eighteen details are : ");
				System.out.println("id of rod is : " + rodEighteen.rodId);
				System.out.println("material of rod is : " + rodEighteen.rodMaterial);
				System.out.println("length of the rod is : " + rodEighteen.rodLength + " metres");
				System.out.println("is Magnetic? " + rodEighteen.isMagnetic);
				System.out.println("weight of the rod is : " + rodEighteen.weight + " Kg");
				System.out.println("price of the rod is : " + rodEighteen.price);

			Rod rodNineteen = new Rod();
			rodNineteen.rodId = 19;
			rodNineteen.rodMaterial = "Inconel";
			rodNineteen.rodLength = 5;
			rodNineteen.isMagnetic = false;
			rodNineteen.weight = 12.1;
			rodNineteen.price = 290.90;
				System.out.println();
				System.out.println("Rod nineteen details are : ");
				System.out.println("id of rod is : " + rodNineteen.rodId);
				System.out.println("material of rod is : " + rodNineteen.rodMaterial);
				System.out.println("length of the rod is : " + rodNineteen.rodLength + " metres");
				System.out.println("is Magnetic? " + rodNineteen.isMagnetic);
				System.out.println("weight of the rod is : " + rodNineteen.weight + " Kg");
				System.out.println("price of the rod is : " + rodNineteen.price);

			Rod rodTwenty = new Rod();
			rodTwenty.rodId = 20;
			rodTwenty.rodMaterial = "Silicon Bronze";
			rodTwenty.rodLength = 4;
			rodTwenty.isMagnetic = false;
			rodTwenty.weight = 9.9;
			rodTwenty.price = 230.00;
				System.out.println();
				System.out.println("Rod twenty details are : ");
				System.out.println("id of rod is : " + rodTwenty.rodId);
				System.out.println("material of rod is : " + rodTwenty.rodMaterial);
				System.out.println("length of the rod is : " + rodTwenty.rodLength + " metres");
				System.out.println("is Magnetic? " + rodTwenty.isMagnetic);
				System.out.println("weight of the rod is : " + rodTwenty.weight + " Kg");
				System.out.println("price of the rod is : " + rodTwenty.price);

			System.out.println();
		System.out.println("main ended");
		
	}
}