class Satellite{
	static String name;
	static String launchDate;
	static String orbitType;
	static String launchVehicle;
	static String launchSite;
	static String missionType;
	static String manufacturer;
	static int power;
	static int launchMass;
	static int missionCost;
	static String contractor;
	static int missionDuration;
	static String longitude;
	static String coverageArea;
	static int satcatNo;
	static String cosparId;
	static String launchTime;
	static String band;
	static int noOfKuBandTransponders;
	static int noOfCbandTransponders;
	public static void main(String satellite[]){
		System.out.println("The satellite name is "+name);
		System.out.println("The launch date of the satellite is "+launchDate);
		System.out.println("The orbit type of the satellite is "+orbitType);
		System.out.println("The launch vehicle of the satellite is "+launchVehicle);
		System.out.println("The launch site of the satellite is "+launchSite);
		System.out.println("The mission type is "+missionType);
		System.out.println("The manufacturer of the satellite is "+manufacturer);
		System.out.println("The power supply of the satellite is "+power+" watts");
		System.out.println("The launch mass of the satellite is "+launchMass+" Kg");
		System.out.println("The cost of the mission is "+missionCost);
		System.out.println("The contractor of the mission is "+contractor);
		System.out.println("The duration of the mission is "+missionDuration);
		System.out.println("The longitude of the satellite is "+longitude);
		System.out.println("The coverage area of the satellite is "+coverageArea);
		System.out.println("The SATCAT number of the satellite is "+satcatNo);
		System.out.println("The COSPAR ID of the satellite is "+cosparId);
		System.out.println("The launch time of the satellite is "+launchTime);
		System.out.println("The band of the Satellite is "+band);
		System.out.println("The number of Ku band transponders are "+noOfKuBandTransponders);
		System.out.println("The number of the C-band transponders are "+noOfCbandTransponders);
		System.out.println();
	 String name="GSAT-30";
	 String launchDate="17-01-2020";
	 String orbitType="Geostationary";
	 String launchVehicle="Ariane 5";
	 String launchSite="Kourou";
	 String missionType="Communications";
	 String manufacturer="ISRO Satellite Centre";
	 int power=6000;
	 int launchMass=3357;
	 int missionCost=950;
	 String contractor="Arianespace";
	 int missionDuration=15;
	 String longitude="83.0° East";
	 String coverageArea="Asia, Australia";
	 int satcatNo=45026;
	 String cosparId="2020-005A";
	 String launchTime="02:35 IST";
	 String band="12 x C-band,12 x Ku-band";
	 int noOfKuBandTransponders=12;
	 int noOfCbandTransponders=12;
		System.out.println("After re-initialization");
		System.out.println("The satellite name is "+name);
		System.out.println("The launch date of the satellite is "+launchDate);
		System.out.println("The orbit type of the satellite is "+orbitType);
		System.out.println("The launch vehicle of the satellite is "+launchVehicle);
		System.out.println("The launch site of the satellite is "+launchSite);
		System.out.println("The mission type is "+missionType);
		System.out.println("The manufacturer of the satellite is "+manufacturer);
		System.out.println("The power supply of the satellite is "+power+" watts");
		System.out.println("The launch mass of the satellite is "+launchMass+" Kg");
		System.out.println("The cost of the mission is "+missionCost);
		System.out.println("The contractor of the mission is "+contractor);
		System.out.println("The duration of the mission is "+missionDuration);
		System.out.println("The longitude of the satellite is "+longitude);
		System.out.println("The coverage area of the satellite is "+coverageArea);
		System.out.println("The SATCAT number of the satellite is "+satcatNo);
		System.out.println("The COSPAR ID of the satellite is "+cosparId);
		System.out.println("The launch time of the satellite is "+launchTime);
		System.out.println("The band of the Satellite is "+band);
		System.out.println("The number of Ku band transponders are "+noOfKuBandTransponders);
		System.out.println("The number of the C-band transponders are "+noOfCbandTransponders);
	}
}