class ShoppingMall{
	static String mallName;
	static String location;
	static int builtYear;
	static int noOfFloors;
	static int noOfRetailShops;
	static int noOfWorkers;
	static int noOfFoodOutlets;
	static String movieTheatre;
	static boolean hasGamingZone;
	static String gamingZoneName;
	static String openingTime;
	static String closingTime;
	static boolean hasRestRooms;
	static int noOfRestRooms;
	static String owner;
	static long phoneNumber;
	static int shoppingArea;
	static String architectureDesign;
	static String email;
	static boolean hasescalator;
	public static void main(String mall[]){
		System.out.println("The mall name is "+mallName);
		System.out.println("The mall is located at "+location);
		System.out.println("The mall was built in the year "+builtYear);
		System.out.println("The number of floors in the mall are "+noOfFloors);
		System.out.println("The number of retail shops in the mall are "+noOfRetailShops);
		System.out.println("The number of workers in the mall are "+noOfWorkers);
		System.out.println("The number of food outlets in the mall are "+noOfFoodOutlets);
		System.out.println("The movie theatre in the shopping mall is "+movieTheatre);
		System.out.println("does the shopping mall has gaming zone? "+hasGamingZone);
		System.out.println("The name of the gaming zone in the mall is "+gamingZoneName);
		System.out.println("The opening time of the shopping mall is "+openingTime);
		System.out.println("The closing time of the shopping mall is "+closingTime);
		System.out.println("does the shopping mall has rest rooms? "+hasRestRooms);
		System.out.println("The number of rest rooms are "+noOfRestRooms);
		System.out.println("The owner of the shopping mall is "+owner);
		System.out.println("The contact number of the shopping mall is "+phoneNumber);
		System.out.println("The shopping area of the mall is "+shoppingArea+" Acres");
		System.out.println("The architecture design of the shopping mall is "+architectureDesign);
		System.out.println("The email id of the shopping mall is "+email);
		System.out.println("does the shopping mall has escalator? "+hasescalator);
		System.out.println();
	 String mallName="Orion Mall";
	 String location="Rajajinagar";
	 int builtYear=2012;
	 int noOfFloors=4;
	 int noOfRetailShops=300;
	 int noOfWorkers=400;
	 int noOfFoodOutlets=40;
	 String movieTheatre="PVR Cinemas";
	 boolean hasGamingZone=true;
	 String gamingZoneName="Time Zone";
	 String openingTime="10:00 AM";
	 String closingTime="8:00 PM";
	 boolean hasRestRooms=true;
	 int noOfRestRooms=20;
	 String owner="Brigade Group";
	 long phoneNumber=8067282222l;
	 int shoppingArea=40;
	 String architectureDesign="Sleek Architecture Design";
	 String email="gre@orionmalls.com";
	 boolean hasEscalator=true;
		System.out.println("After re-initialization");
		System.out.println("The mall name is "+mallName);
		System.out.println("The mall is located at "+location);
		System.out.println("The mall was built in the year "+builtYear);
		System.out.println("The number of floors in the mall are "+noOfFloors);
		System.out.println("The number of retail shops in the mall are "+noOfRetailShops);
		System.out.println("The number of workers in the mall are "+noOfWorkers);
		System.out.println("The number of food outlets in the mall are "+noOfFoodOutlets);
		System.out.println("The movie theatre in the shopping mall is "+movieTheatre);
		System.out.println("does the shopping mall has gaming zone? "+hasGamingZone);
		System.out.println("The name of the gaming zone in the mall is "+gamingZoneName);
		System.out.println("The opening time of the shopping mall is "+openingTime);
		System.out.println("The closing time of the shopping mall is "+closingTime);
		System.out.println("does the shopping mall has rest rooms? "+hasRestRooms);
		System.out.println("The number of rest rooms are "+noOfRestRooms);
		System.out.println("The owner of the shopping mall is "+owner);
		System.out.println("The contact number of the shopping mall is "+phoneNumber);
		System.out.println("The shopping area of the mall is "+shoppingArea+" Acres");
		System.out.println("The architecture design of the shopping mall is "+architectureDesign);
		System.out.println("The email id of the shopping mall is "+email);
		System.out.println("does the shopping mall has escalator? "+hasEscalator);
	}
}