class SolarSystem{
	static String galaxyName;
	static int noOfPlanets;
	static String centralStar;
	static String sunType;
	static double sunTemperature;
	static int noOfMoons;
	static int noOfAsteroids;
	static int noOfComets;
	static double age;
	static boolean hasAsteroidBelt;
	static String largestPlanet;
	static String smallestPlanet;
	static String hottestPlanet;
	static String coldestPlanet;
	static String onlyPlanetWithLife;
	static String nearestStar;
	static int orbitralSpeed;
	static int orbitralPeriod;
	static int noOfNaturalSatellites;
	static boolean hasKuiperBelt;
	public static void main(String solarsystem[]){
		System.out.println("The name of the galaxy where the solar system is presnt in "+galaxyName);
		System.out.println("The number of planets in the solar system are "+noOfPlanets);
		System.out.println("The central star of the solar system is "+centralStar);
		System.out.println("The sun type of the solr system is "+sunType);
		System.out.println("The temperature of the sun is "+sunTemperature+" Kelvin");
		System.out.println("The number of moons in the solar system are "+noOfMoons);
		System.out.println("The number of the asteroids in the solar system are "+noOfAsteroids);
		System.out.println("The number of comets in the solar system are "+noOfComets);
		System.out.println("The age of the solar system is "+age+" billion years");
		System.out.println("does the solar sytem has asteroid belt? "+hasAsteroidBelt);
		System.out.println("The largest planet of the solar system is "+largestPlanet);
		System.out.println("The smallest planet of the solar system is "+smallestPlanet);
		System.out.println("The hottest planet of the solar system is "+hottestPlanet);
		System.out.println("The coldest planet in the solar system is "+coldestPlanet);
		System.out.println("The only planet with life in the solar system is "+onlyPlanetWithLife);
		System.out.println("The nearest star to the solar system is "+nearestStar);
		System.out.println("The orbitral speed of the solar system is "+orbitralSpeed+" Km/h");
		System.out.println("The orbitral period of the solar system is "+orbitralPeriod+" million years");
		System.out.println("does the solar system has kuiper belt? "+hasKuiperBelt);
		System.out.println();
	 String galaxyName="Milky Way";
	 int noOfPlanets=8;
	 String centralStar="Sun";
	 String sunType="G-type Main Sequence";
	 double sunTemperature=5778.00d;
	 int noOfMoons=290;
	 int noOfAsteroids=1000000;
	 int noOfComets=3500;
	 double age=4.6d;
	 boolean hasAsteroidBelt=true;
	 String largestPlanet="Jupiter";
	 String smallestPlanet="Mercury";
	 String hottestPlanet="Venus";
	 String coldestPlanet="Neptune";
	 String onlyPlanetWithLife="Earth";
	 String nearestStar="Proxima Centauri";
	 int orbitralSpeed=720000;
	 int orbitralPeriod=230;
	 int noOfNaturalSatellites=758;
	 boolean hasKuiperBelt=true;
		System.out.println("After re-initialization");
	 	System.out.println("The name of the galaxy where the solar system is presnt in "+galaxyName);
		System.out.println("The number of planets in the solar system are "+noOfPlanets);
		System.out.println("The central star of the solar system is "+centralStar);
		System.out.println("The sun type of the solr system is "+sunType);
		System.out.println("The temperature of the sun is "+sunTemperature+" Kelvin");
		System.out.println("The number of moons in the solar system are "+noOfMoons);
		System.out.println("The number of the asteroids in the solar system are "+noOfAsteroids);
		System.out.println("The number of comets in the solar system are "+noOfComets);
		System.out.println("The age of the solar system is "+age+" billion years");
		System.out.println("does the solar sytem has asteroid belt? "+hasAsteroidBelt);
		System.out.println("The largest planet of the solar system is "+largestPlanet);
		System.out.println("The smallest planet of the solar system is "+smallestPlanet);
		System.out.println("The hottest planet of the solar system is "+hottestPlanet);
		System.out.println("The coldest planet in the solar system is "+coldestPlanet);
		System.out.println("The only planet with life in the solar system is "+onlyPlanetWithLife);
		System.out.println("The nearest star to the solar system is "+nearestStar);
		System.out.println("The orbitral speed of the solar system is "+orbitralSpeed+" Km/h");
		System.out.println("The orbitral period of the solar system is "+orbitralPeriod+" million years");
		System.out.println("does the solar system has kuiper belt? "+hasKuiperBelt);
	}
}