class Stadium{
	static String stadiumName;
	static String location;
	static int establishedYear;
	static int stadiumCapacity;
	static String architect;
	static boolean hasCantileverRoof;
	static double shortestBoundary;
	static double longestBoundary;
	static boolean hasVipBoxes;
	static boolean hasFoodCourts;
	static boolean hasRestRooms;
	static int noOfRestRooms;
	static boolean isParkingAvailable;
	static int parkingCapacity;
	static String owner;
	static boolean isIccAproved;
	static String primaryUse;
	static String otherEventsHosted;
	static int noOfPavillions;
	static int noOfPracticeNets;
	public static void main(String stadium[]){
		System.out.println("The name of the stadium is "+stadiumName);
		System.out.println("The stadium is located at "+location);
		System.out.println("The capacity of the stadim is "+stadiumCapacity);
		System.out.println("The architects of the stadim are : "+architect);
		System.out.println("Does the stadium has cantilever roof? "+hasCantileverRoof);
		System.out.println("The shortest boundary if the stadium is "+shortestBoundary+" metres");
		System.out.println("The longest boundary of the stadium is "+longestBoundary+" metres");
		System.out.println("does the stadium has VIP boxes? "+hasVipBoxes);
		System.out.println("does the stadium has food courts? "+hasFoodCourts);
		System.out.println("does the stadium has rest rooms? "+hasRestRooms);
		System.out.println("The number of rest rooms int stadium are "+noOfRestRooms);
		System.out.println("Is parking available at the stadium? "+isParkingAvailable);
		System.out.println("The parking capacity of the stadium is "+parkingCapacity);
		System.out.println("The owner of the stadium is "+owner);
		System.out.println("Is the stadium approved by ICC? "+isIccAproved);
		System.out.println("The primary use of the stadium is "+primaryUse);
		System.out.println("The other events hosted int this stadium are "+otherEventsHosted);
		System.out.println("The number of pavillions in this stadium are "+noOfPavillions);
		System.out.println("The number of practice nets in this stadium are "+noOfPracticeNets);
		System.out.println();
	 String stadiumName="Wankhede Stadium";
	 String location="Church gate, Mumbai";
	 int establishedYear=1974;
	 int stadiumCapacity=33108;
	 String architect="Shashi Prabhu & Associates, P.K. Das & Associates";
	 boolean hasCantileverRoof=true;
	 double shortestBoundary=70.0d;
	 double longestBoundary=70.0d;
	 boolean hasVipBoxes=true;
	 boolean hasFoodCourts=true;
	 boolean hasRestRooms=true;
	 int noOfRestRooms=15;
	 boolean isParkingAvailable=true;
	 int parkingCapacity=250;
	 String owner="Mumbai Cricket Association";
	 boolean isIccAproved=true;
	 String primaryUse="Cricket";
	 String otherEventsHosted="Concerts,Award shows";
	 int noOfPavillions=4;
	 int noOfPracticeNets=6;
		System.out.println("After re-initialization");
		System.out.println("The name of the stadium is "+stadiumName);
		System.out.println("The stadium is located at "+location);
		System.out.println("The capacity of the stadim is "+stadiumCapacity);
		System.out.println("The architects of the stadim are : "+architect);
		System.out.println("Does the stadium has cantilever roof? "+hasCantileverRoof);
		System.out.println("The shortest boundary if the stadium is "+shortestBoundary+" metres");
		System.out.println("The longest boundary of the stadium is "+longestBoundary+" metres");
		System.out.println("does the stadium has VIP boxes? "+hasVipBoxes);
		System.out.println("does the stadium has food courts? "+hasFoodCourts);
		System.out.println("does the stadium has rest rooms? "+hasRestRooms);
		System.out.println("The number of rest rooms int stadium are "+noOfRestRooms);
		System.out.println("Is parking available at the stadium? "+isParkingAvailable);
		System.out.println("The parking capacity of the stadium is "+parkingCapacity);
		System.out.println("The owner of the stadium is "+owner);
		System.out.println("Is the stadium approved by ICC? "+isIccAproved);
		System.out.println("The primary use of the stadium is "+primaryUse);
		System.out.println("The other events hosted int this stadium are "+otherEventsHosted);
		System.out.println("The number of pavillions in this stadium are "+noOfPavillions);
		System.out.println("The number of practice nets in this stadium are "+noOfPracticeNets);
	}
}