class SwitchBoard{
	static int boardId;
	static String brandName;
	static int noOfPlugs;
	static int noOfSwitches;
	static String manufacturer;
	static double price;
	static double customerRatings;
	static int voltageLevel;
	static boolean isOperational;
	static boolean isGrounded;
	static int currentCapacity;
	static String ipRating;
	static String panelMaterial;
	static String fuseType;
	static int powerRating;
	static boolean isTemperatureSensorPresent;
	static int breakerCapacity;
	static String phaseType;
	static int frequency;
	static boolean isOverloaded;
	public static void main(String switchboard[]){
		System.out.println("The switch board Id is "+boardId);
		System.out.println("The brand name of the switch board is "+brandName);
		System.out.println("The number of plugs on the switch board are "+noOfPlugs);
		System.out.println("The number of switches on the switch board are "+noOfSwitches);
		System.out.println("The manufacturer of the switch board is "+manufacturer);
		System.out.println("The price of the switch board is "+price);
		System.out.println("The customer ratings for the swicth board are "+customerRatings);
		System.out.println("The voltage level of the swicth board is "+voltageLevel);
		System.out.println("is the switch board operational?"+isOperational);
		System.out.println("is temperature sensor present? "+isTemperatureSensorPresent);
		System.out.println("is the switch board grounded? "+isGrounded);
		System.out.println("is the switch board overloaded? "+isOverloaded);
		System.out.println("The current capacity of the switch board is "+currentCapacity);
		System.out.println("The Ip Rating of the switch board is "+ipRating);
		System.out.println("The panel material of the switch board is "+panelMaterial);
		System.out.println("The fuse type of the switch board is "+fuseType);
		System.out.println("The power rating of the switch board is "+powerRating);
		System.out.println("The breaker capacity of the swicth board is "+breakerCapacity);
		System.out.println("The phase type of the switch board is "+phaseType);
		System.out.println("The frequency of the switch board is "+frequency);
		System.out.println();
	 int boardId=2;
	 String brandName="Havells";
	 int noOfPlugs=3;
	 int noOfSwitches=12;
	 String manufacturer="Elins Switchboards Private Limited";
	 double price=800.00d;
	 double customerRatings=	4.4d;
	 int voltageLevel=230;
	 boolean isOperational=true;
	 boolean isGrounded=true;
	 int currentCapacity=15;
	 String ipRating="IP65";
	 String panelMaterial="Polycarbonate";
	 String fuseType="MCB";
	 int powerRating=	3500;
	 boolean isTemperatureSensorPresent=true;
	 int breakerCapacity=16;
	 String phaseType="Single Phase";
	 int frequency=50;
	 boolean isOverloaded=false;
		System.out.println("The switch board Id is "+boardId);
		System.out.println("The brand name of the switch board is "+brandName);
		System.out.println("The number of plugs on the switch board are "+noOfPlugs);
		System.out.println("The number of switches on the switch board are "+noOfSwitches);
		System.out.println("The manufacturer of the switch board is "+manufacturer);
		System.out.println("The price of the switch board is "+price);
		System.out.println("The customer ratings for the swicth board are "+customerRatings);
		System.out.println("The voltage level of the swicth board is "+voltageLevel);
		System.out.println("is the switch board operational?"+isOperational);
		System.out.println("is temperature sensor present? "+isTemperatureSensorPresent);
		System.out.println("is the switch board grounded? "+isGrounded);
		System.out.println("is the switch board overloaded? "+isOverloaded);
		System.out.println("The current capacity of the switch board is "+currentCapacity);
		System.out.println("The Ip Rating of the switch board is "+ipRating);
		System.out.println("The panel material of the switch board is "+panelMaterial);
		System.out.println("The fuse type of the switch board is "+fuseType);
		System.out.println("The power rating of the switch board is "+powerRating);
		System.out.println("The breaker capacity of the swicth board is "+breakerCapacity);
		System.out.println("The phase type of the switch board is "+phaseType);
		System.out.println("The frequency of the switch board is "+frequency);
	}
}