class Temple{
	static String templeName;
	static String location;
	static String diety;
	static int noOfSteps;
	static String festivalsOrganized;
	static String managementAuthority;
	static int estabilishedYear;
	static int netWorth;
	static int noOfDevotees;
	static int noOfDevoteesAnnualy;
	static String locatedOn;
	static String prasadamType;
	static String openingTime;
	static String closingTime;
	static boolean hasCctv;
	static int noOfArchakas;
	static double specialEntryFee;
	static String dressCode;
	static boolean isAccomodationAvailable;
	static boolean isPiligrimCentre;
	public static void main(String temple[]){
		System.out.println("The temple name is "+templeName);
		System.out.println("The temple is located at "+location);
		System.out.println("The diety of the temple is "+diety);
		System.out.println("The number of steps to reach the entrance : "+noOfSteps);
		System.out.println("The festivals organized in the temple are : "+festivalsOrganized);
		System.out.println("The management authority of the temple is "+managementAuthority);
		System.out.println("The temple was established in the year "+estabilishedYear+" CE");
		System.out.println("The net worth of the temple is "+netWorth+" billion");
		System.out.println("The number of devotees come for darshanam are "+noOfDevotees+" per day");
		System.out.println("The number of Devotees annualy visit the temple are "+noOfDevoteesAnnualy+" million");
		System.out.println("The temple is located on "+locatedOn);
		System.out.println("The type of prasadam of the temple is "+prasadamType);
		System.out.println("The opening time of the temple is "+openingTime);
		System.out.println("The closing time of the temple is "+closingTime);
		System.out.println("Does the temple has CCTV Surveillance? "+hasCctv);
		System.out.println("The number of archakas of the temple are "+noOfArchakas);
		System.out.println("The special entry fee of the darshanam is "+specialEntryFee+" Rupees");
		System.out.println("The dress code for the temple is "+dressCode);
		System.out.println("Is accomodation available at the temple? "+isAccomodationAvailable);
		System.out.println("Is the temple a piligrim centre? "+isPiligrimCentre);
		System.out.println();
	 String templeName="Shri Ventakeshwara Temple";
	 String location="Tirumala,Andhra Pradesh";
	 String diety="Lord Ventakeshwara(Balaji)";
	 int noOfSteps=3550;
	 String festivalsOrganized="Srivari Brahmotsavam, Vaikunta Ekadashi, Ratha Saptami";
	 String managementAuthority="Tirumala Tirupati Devasthanams";
	 int estabilishedYear=300;
	 int netWorth=35;
	 int noOfDevotees=60000;
	 int noOfDevoteesAnnualy=24;
	 String locatedOn="Seven Hills";
	 String prasadamType="Tirupati Laddu";
	 String openingTime="2:30 AM";
	 String closingTime="1:30 AM (next day)";
	 boolean hasCctv=true;
	 int noOfArchakas=120;
	 double specialEntryFee=300.00d;
	 String dressCode="Tradition only";
	 boolean isAccomodationAvailable=true;
	 boolean isPiligrimCentre=true;
		System.out.println("After re-initialization");
		System.out.println("The temple name is "+templeName);
		System.out.println("The temple is located at "+location);
		System.out.println("The diety of the temple is "+diety);
		System.out.println("The number of steps to reach the entrance : "+noOfSteps);
		System.out.println("The festivals organized in the temple are : "+festivalsOrganized);
		System.out.println("The management authority of the temple is "+managementAuthority);
		System.out.println("The temple was established in the year "+estabilishedYear+" CE");
		System.out.println("The net worth of the temple is "+netWorth+" billion");
		System.out.println("The number of devotees come for darshanam are "+noOfDevotees+" per day");
		System.out.println("The number of Devotees annualy visit the temple are "+noOfDevoteesAnnualy+" million");
		System.out.println("The temple is located on "+locatedOn);
		System.out.println("The type of prasadam of the temple is "+prasadamType);
		System.out.println("The opening time of the temple is "+openingTime);
		System.out.println("The closing time of the temple is "+closingTime);
		System.out.println("Does the temple has CCTV Surveillance? "+hasCctv);
		System.out.println("The number of archakas of the temple are "+noOfArchakas);
		System.out.println("The special entry fee of the darshanam is "+specialEntryFee+" Rupees");
		System.out.println("The dress code for the temple is "+dressCode);
		System.out.println("Is accomodation available at the temple? "+isAccomodationAvailable);
		System.out.println("Is the temple a piligrim centre? "+isPiligrimCentre);
	}
}