class Theatre{
	static String theatreName;
	static String location;
	static int noOfSeats;
	static String typesOfTickets;
	static int noOfTicketCounters;
	static boolean isParkingAreaAvailable;
	static int parkingAreaCapacity;
	static int noOfRestRooms;
	static boolean isMultiplex;
	static int noOfShows;
	static String currentCinemaScreening;
	static int noOfWorkers;
	static boolean isFoodStallAvailable;
	static String morningShowTimings;
	static String matneeShowTimings;
	static String secondShowTimings;
	static int noOfMoviesReleased;
	static String typeOfMovieScreening;
	static int noOfReReleases;
	static int highestRecord;
	public static void main(String theatre[]){
		System.out.println("The theatre name is "+theatreName);
		System.out.println("The location of the theatre is "+location);
		System.out.println("The number of seats available are "+200);
		System.out.println("The types of tickets available are : "+typesOfTickets);
		System.out.println("The number of ticket counters are "+noOfTicketCounters);
		System.out.println("Is Parking available at the theatre? "+isParkingAreaAvailable);
		System.out.println("The capacity of the parking area is "+parkingAreaCapacity+" vehicles");
		System.out.println("The number of rest rooms available are "+noOfRestRooms);
		System.out.println("is the theatre multiplex? "+isMultiplex);
		System.out.println("The number of shows per day "+noOfShows);
		System.out.println("The current cinema screening in the theatre is "+currentCinemaScreening);
		System.out.println("The number of workers in the theatre are "+noOfWorkers);
		System.out.println("Is food stalls available at the theatre? "+isFoodStallAvailable);
		System.out.println("Morning show timings are : "+morningShowTimings);
		System.out.println("Matnee show timings are : "+matneeShowTimings);
		System.out.println("Second show timings are : "+secondShowTimings);
		System.out.println("Number of movies released till now are "+noOfMoviesReleased);
		System.out.println("The type of movie screening is "+typeOfMovieScreening);
		System.out.println("The number of Re-releases are "+noOfReReleases);
		System.out.println("The highest collection record for the theatre is "+highestRecord+" Crores");
		System.out.println();
	 String theatreName="Nataraj Theatre";
	 String location="Rajajinagar";
	 int noOfSeats=100;
	 String typesOfTickets="Golden class, Silver class";
	 int noOfTicketCounters=3;
	 boolean isParkingAreaAvailable=true;
	 int parkingAreaCapacity=200;
	 int noOfRestRooms=10;
	 boolean isMultiplex=false;
	 int noOfShows=4;
	 String currentCinemaScreening="Kubera";
	 int noOfWorkers=15;
	 boolean isFoodStallAvailable=true;
	 String morningShowTimings="9:00 AM to 11:00 AM";
	 String matneeShowTimings="12:00 PM to 2:00PM";
	 String secondShowTimings="10:00 PM to 1:00 AM";
	 int noOfMoviesReleased=50;
	 String typeOfMovieScreening="3D";
	 int noOfReReleases=15;
	 int highestRecord=150;
		System.out.println("After re-initialization");
		System.out.println("The theatre name is "+theatreName);
		System.out.println("The location of the theatre is "+location);
		System.out.println("The number of seats available are "+200);
		System.out.println("The types of tickets available are : "+typesOfTickets);
		System.out.println("The number of ticket counters are "+noOfTicketCounters);
		System.out.println("Is Parking available at the theatre? "+isParkingAreaAvailable);
		System.out.println("The capacity of the parking area is "+parkingAreaCapacity+" vehicles");
		System.out.println("The number of rest rooms available are "+noOfRestRooms);
		System.out.println("is the theatre multiplex? "+isMultiplex);
		System.out.println("The number of shows per day "+noOfShows);
		System.out.println("The current cinema screening in the theatre is "+currentCinemaScreening);
		System.out.println("The number of workers in the theatre are "+noOfWorkers);
		System.out.println("Is food stalls available at the theatre? "+isFoodStallAvailable);
		System.out.println("Morning show timings are : "+morningShowTimings);
		System.out.println("Matnee show timings are : "+matneeShowTimings);
		System.out.println("Second show timings are : "+secondShowTimings);
		System.out.println("Number of movies released till now are "+noOfMoviesReleased);
		System.out.println("The type of movie screening is "+typeOfMovieScreening);
		System.out.println("The number of Re-releases are "+noOfReReleases);
		System.out.println("The highest collection record for the theatre is "+highestRecord+" Crores");
	}

}