class VideoGames{
	static String gameTitle;
	static String genre;
	static String publisher;
	static String developer;
	static String platforms;
	static String creators;
	static String firstReleaseDate;
	static String latestReleaseDate;
	static String latestReleaseName;
	static String noOfDownloads;
	static String popularVersion;
	static boolean isMultiplayerModeAvailable;
	static String mainCharacterNames;
	static double gamesize;
	static int ageRating;
	static boolean isVrSupported;
	static String gameCurrency;
	static String multiplayerMode;
	static String singlePlayerMode;
	static String officialWebsite;
	public static void main(String games[]){
		System.out.println("The title of the game is "+gameTitle);
		System.out.println("The genre of the video game is "+genre);
		System.out.println("The publisher of the video game is "+publisher);
		System.out.println("The developer of the video game is "+developer);
		System.out.println("The platforms where the vidoe games can be played are : "+platforms);
		System.out.println("The creators of the video game are "+creators);
		System.out.println("The first release date of the video game is "+firstReleaseDate);
		System.out.println("The latest release date of the video game is "+latestReleaseDate);
		System.out.println("The name of the latest release version of the video game is "+latestReleaseName);
		System.out.println("The number of downloads of the game are "+noOfDownloads);
		System.out.println("The popular version of the video game is "+popularVersion);
		System.out.println("Is multiplayer mode available? "+isMultiplayerModeAvailable);
		System.out.println("The main characters names of the video game are : "+mainCharacterNames);
		System.out.println("The size of the video game is "+gamesize+" GB");
		System.out.println("The age rating of the video game is "+ageRating);
		System.out.println("Is Vr support available for this video game? "+isVrSupported);
		System.out.println("The game currency is "+gameCurrency);
		System.out.println("The mode of the multiplayer is "+multiplayerMode);
		System.out.println("The mode of the single player is "+singlePlayerMode);
		System.out.println("The official website of the game : "+officialWebsite);
		System.out.println();
	 String gameTitle="Grand Theft Auto v";
	 String genre="Action-adventure";
	 String publisher="Rockstar Games";
	 String developer="Rockstar North";
	 String platforms="Android, Dreamcast, Fire OS, iOS, macOS and others";
	 String creators="David Jones , Mike Dailly";
	 String firstReleaseDate="28 November 1997";
	 String latestReleaseDate="11 November 2021";
	 String latestReleaseName="Grand Theft Auto: The Trilogy - The Definitive Edition";
	 String noOfDownloads="215 million copies";
	 String popularVersion="GTA 5";
	 boolean isMultiplayerModeAvailable=true;
	 String mainCharacterNames="Michael, Trevor, Franklin";
	 double gamesize=90.0;
	 int ageRating=18;
	 boolean isVrSupported=false;
	 String gameCurrency="GTA$";
	 String multiplayerMode="Online";
	 String singlePlayerMode="Offline";
	 String officialWebsite="https://www.rockstargames.com/V";
		System.out.println("After re-initialization");
		System.out.println("The title of the game is "+gameTitle);
		System.out.println("The genre of the video game is "+genre);
		System.out.println("The publisher of the video game is "+publisher);
		System.out.println("The developer of the video game is "+developer);
		System.out.println("The platforms where the vidoe games can be played are : "+platforms);
		System.out.println("The creators of the video game are "+creators);
		System.out.println("The first release date of the video game is "+firstReleaseDate);
		System.out.println("The latest release date of the video game is "+latestReleaseDate);
		System.out.println("The name of the latest release version of the video game is "+latestReleaseName);
		System.out.println("The number of downloads of the game are "+noOfDownloads);
		System.out.println("The popular version of the video game is "+popularVersion);
		System.out.println("Is multiplayer mode available? "+isMultiplayerModeAvailable);
		System.out.println("The main characters names of the video game are : "+mainCharacterNames);
		System.out.println("The size of the video game is "+gamesize+" GB");
		System.out.println("The age rating of the video game is "+ageRating);
		System.out.println("Is Vr support available for this video game? "+isVrSupported);
		System.out.println("The game currency is "+gameCurrency);
		System.out.println("The mode of the multiplayer is "+multiplayerMode);
		System.out.println("The mode of the single player is "+singlePlayerMode);
		System.out.println("The official website of the game : "+officialWebsite);
	}
}