class WeaponRunner{
	public static void main(String[] weapon){
		System.out.println("main started");
			
			Weapon weaponOne = new Weapon();
			weaponOne.weaponId=1;
			weaponOne.weaponName="AK47";
			weaponOne.weaponMaterial="metal";
			weaponOne.price=15000.00;
			weaponOne.manufacturedYear=1847;
			weaponOne.range=200;
				System.out.println();
				System.out.println("first weapon details :");
				System.out.println("id of weapon is : "+weaponOne.weaponId);
				System.out.println("name of the weapon is : "+weaponOne.weaponName);
				System.out.println("material of the weapon is : "+weaponOne.weaponMaterial);
				System.out.println("price of the weapon is  : "+weaponOne.price);
				System.out.println("manufactured year of the weapon is : "+weaponOne.manufacturedYear);
				System.out.println("range of the weapon is : "+weaponOne.range+" m");
				
			Weapon weaponTwo = new Weapon();
			weaponTwo.weaponId = 2;
			weaponTwo.weaponName = "M16";
			weaponTwo.weaponMaterial = "Alloy Steel";
			weaponTwo.price = 18000.00;
			weaponTwo.manufacturedYear = 1964;
			weaponTwo.range = 550;
				System.out.println();
				System.out.println("Second weapon details :");
				System.out.println("id of weapon is : " + weaponTwo.weaponId);
				System.out.println("name of the weapon is : " + weaponTwo.weaponName);
				System.out.println("material of the weapon is : " + weaponTwo.weaponMaterial);
				System.out.println("price of the weapon is  : " + weaponTwo.price);
				System.out.println("manufactured year of the weapon is : " + weaponTwo.manufacturedYear);
				System.out.println("range of the weapon is : " + weaponTwo.range + " m");

			Weapon weaponThree = new Weapon();
			weaponThree.weaponId = 3;
			weaponThree.weaponName = "Glock 17";
			weaponThree.weaponMaterial = "Polymer and Steel";
			weaponThree.price = 7000.00;
			weaponThree.manufacturedYear = 1982;
			weaponThree.range = 50;
				System.out.println();
				System.out.println("Third weapon details :");
				System.out.println("id of weapon is : " + weaponThree.weaponId);
				System.out.println("name of the weapon is : " + weaponThree.weaponName);
				System.out.println("material of the weapon is : " + weaponThree.weaponMaterial);
				System.out.println("price of the weapon is  : " + weaponThree.price);
				System.out.println("manufactured year of the weapon is : " + weaponThree.manufacturedYear);
				System.out.println("range of the weapon is : " + weaponThree.range + " m");

			Weapon weaponFour = new Weapon();
			weaponFour.weaponId = 4;
			weaponFour.weaponName = "Sniper Rifle";
			weaponFour.weaponMaterial = "Carbon Fiber and Steel";
			weaponFour.price = 25000.00;
			weaponFour.manufacturedYear = 2001;
			weaponFour.range = 1200;
				System.out.println();
				System.out.println("Fourth weapon details :");
				System.out.println("id of weapon is : " + weaponFour.weaponId);
				System.out.println("name of the weapon is : " + weaponFour.weaponName);
				System.out.println("material of the weapon is : " + weaponFour.weaponMaterial);
				System.out.println("price of the weapon is  : " + weaponFour.price);
				System.out.println("manufactured year of the weapon is : " + weaponFour.manufacturedYear);
				System.out.println("range of the weapon is : " + weaponFour.range + " m");

			Weapon weaponFive = new Weapon();
			weaponFive.weaponId = 5;
			weaponFive.weaponName = "Desert Eagle";
			weaponFive.weaponMaterial = "Stainless Steel";
			weaponFive.price = 12000.00;
			weaponFive.manufacturedYear = 1983;
			weaponFive.range = 200;
				System.out.println();
				System.out.println("Fifth weapon details :");
				System.out.println("id of weapon is : " + weaponFive.weaponId);
				System.out.println("name of the weapon is : " + weaponFive.weaponName);
				System.out.println("material of the weapon is : " + weaponFive.weaponMaterial);
				System.out.println("price of the weapon is  : " + weaponFive.price);
				System.out.println("manufactured year of the weapon is : " + weaponFive.manufacturedYear);
				System.out.println("range of the weapon is : " + weaponFive.range + " m");

			Weapon weaponSix = new Weapon();
			weaponSix.weaponId = 6;
			weaponSix.weaponName = "M16";
			weaponSix.weaponMaterial = "Steel and Aluminum";
			weaponSix.price = 18000.00;
			weaponSix.manufacturedYear = 1963;
			weaponSix.range = 550;
				System.out.println();
				System.out.println("Sixth weapon details :");
				System.out.println("id of weapon is : " + weaponSix.weaponId);
				System.out.println("name of the weapon is : " + weaponSix.weaponName);
				System.out.println("material of the weapon is : " + weaponSix.weaponMaterial);
				System.out.println("price of the weapon is  : " + weaponSix.price);
				System.out.println("manufactured year of the weapon is : " + weaponSix.manufacturedYear);
				System.out.println("range of the weapon is : " + weaponSix.range + " m");

			Weapon weaponSeven = new Weapon();
			weaponSeven.weaponId = 7;
			weaponSeven.weaponName = "M4 Carbine";
			weaponSeven.weaponMaterial = "Aluminum Alloy";
			weaponSeven.price = 20000.00;
			weaponSeven.manufacturedYear = 1994;
			weaponSeven.range = 600;
				System.out.println();
				System.out.println("Seventh weapon details :");
				System.out.println("id of weapon is : " + weaponSeven.weaponId);
				System.out.println("name of the weapon is : " + weaponSeven.weaponName);
				System.out.println("material of the weapon is : " + weaponSeven.weaponMaterial);
				System.out.println("price of the weapon is  : " + weaponSeven.price);
				System.out.println("manufactured year of the weapon is : " + weaponSeven.manufacturedYear);
				System.out.println("range of the weapon is : " + weaponSeven.range + " m");

			Weapon weaponEight = new Weapon();
			weaponEight.weaponId = 8;
			weaponEight.weaponName = "Glock 17";
			weaponEight.weaponMaterial = "Polymer and Steel";
			weaponEight.price = 5000.00;
			weaponEight.manufacturedYear = 1982;
			weaponEight.range = 50;
				System.out.println();
				System.out.println("Eighth weapon details :");
				System.out.println("id of weapon is : " + weaponEight.weaponId);
				System.out.println("name of the weapon is : " + weaponEight.weaponName);
				System.out.println("material of the weapon is : " + weaponEight.weaponMaterial);
				System.out.println("price of the weapon is  : " + weaponEight.price);
				System.out.println("manufactured year of the weapon is : " + weaponEight.manufacturedYear);
				System.out.println("range of the weapon is : " + weaponEight.range + " m");

			Weapon weaponNine = new Weapon();
			weaponNine.weaponId = 9;
			weaponNine.weaponName = "Desert Eagle";
			weaponNine.weaponMaterial = "Steel";
			weaponNine.price = 12000.00;
			weaponNine.manufacturedYear = 1983;
			weaponNine.range = 200;
				System.out.println();
				System.out.println("Ninth weapon details :");
				System.out.println("id of weapon is : " + weaponNine.weaponId);
				System.out.println("name of the weapon is : " + weaponNine.weaponName);
				System.out.println("material of the weapon is : " + weaponNine.weaponMaterial);
				System.out.println("price of the weapon is  : " + weaponNine.price);
				System.out.println("manufactured year of the weapon is : " + weaponNine.manufacturedYear);
				System.out.println("range of the weapon is : " + weaponNine.range + " m");

			Weapon weaponTen = new Weapon();
			weaponTen.weaponId = 10;
			weaponTen.weaponName = "Sniper Rifle";
			weaponTen.weaponMaterial = "Carbon Fiber";
			weaponTen.price = 30000.00;
			weaponTen.manufacturedYear = 2001;
			weaponTen.range = 1500;
				System.out.println();
				System.out.println("Tenth weapon details :");
				System.out.println("id of weapon is : " + weaponTen.weaponId);
				System.out.println("name of the weapon is : " + weaponTen.weaponName);
				System.out.println("material of the weapon is : " + weaponTen.weaponMaterial);
				System.out.println("price of the weapon is  : " + weaponTen.price);
				System.out.println("manufactured year of the weapon is : " + weaponTen.manufacturedYear);
				System.out.println("range of the weapon is : " + weaponTen.range + " m");

			Weapon weaponEleven = new Weapon();
			weaponEleven.weaponId = 11;
			weaponEleven.weaponName = "MP5";
			weaponEleven.weaponMaterial = "Steel and Polymer";
			weaponEleven.price = 9000.00;
			weaponEleven.manufacturedYear = 1966;
			weaponEleven.range = 200;
				System.out.println();
				System.out.println("Eleventh weapon details :");
				System.out.println("id of weapon is : " + weaponEleven.weaponId);
				System.out.println("name of the weapon is : " + weaponEleven.weaponName);
				System.out.println("material of the weapon is : " + weaponEleven.weaponMaterial);
				System.out.println("price of the weapon is  : " + weaponEleven.price);
				System.out.println("manufactured year of the weapon is : " + weaponEleven.manufacturedYear);
				System.out.println("range of the weapon is : " + weaponEleven.range + " m");

			Weapon weaponTwelve = new Weapon();
			weaponTwelve.weaponId = 12;
			weaponTwelve.weaponName = "Uzi";
			weaponTwelve.weaponMaterial = "Steel";
			weaponTwelve.price = 6000.00;
			weaponTwelve.manufacturedYear = 1950;
			weaponTwelve.range = 150;
				System.out.println();
				System.out.println("Twelfth weapon details :");
				System.out.println("id of weapon is : " + weaponTwelve.weaponId);
				System.out.println("name of the weapon is : " + weaponTwelve.weaponName);
				System.out.println("material of the weapon is : " + weaponTwelve.weaponMaterial);
				System.out.println("price of the weapon is  : " + weaponTwelve.price);
				System.out.println("manufactured year of the weapon is : " + weaponTwelve.manufacturedYear);
				System.out.println("range of the weapon is : " + weaponTwelve.range + " m");

			Weapon weaponThirteen = new Weapon();
			weaponThirteen.weaponId = 13;
			weaponThirteen.weaponName = "Makarov";
			weaponThirteen.weaponMaterial = "Steel";
			weaponThirteen.price = 4500.00;
			weaponThirteen.manufacturedYear = 1951;
			weaponThirteen.range = 50;
				System.out.println();
				System.out.println("Thirteenth weapon details :");
				System.out.println("id of weapon is : " + weaponThirteen.weaponId);
				System.out.println("name of the weapon is : " + weaponThirteen.weaponName);
				System.out.println("material of the weapon is : " + weaponThirteen.weaponMaterial);
				System.out.println("price of the weapon is  : " + weaponThirteen.price);
				System.out.println("manufactured year of the weapon is : " + weaponThirteen.manufacturedYear);
				System.out.println("range of the weapon is : " + weaponThirteen.range + " m");

			Weapon weaponFourteen = new Weapon();
			weaponFourteen.weaponId = 14;
			weaponFourteen.weaponName = "Beretta M9";
			weaponFourteen.weaponMaterial = "Aluminum Alloy";
			weaponFourteen.price = 7500.00;
			weaponFourteen.manufacturedYear = 1985;
			weaponFourteen.range = 100;
				System.out.println();
				System.out.println("Fourteenth weapon details :");
				System.out.println("id of weapon is : " + weaponFourteen.weaponId);
				System.out.println("name of the weapon is : " + weaponFourteen.weaponName);
				System.out.println("material of the weapon is : " + weaponFourteen.weaponMaterial);
				System.out.println("price of the weapon is  : " + weaponFourteen.price);
				System.out.println("manufactured year of the weapon is : " + weaponFourteen.manufacturedYear);
				System.out.println("range of the weapon is : " + weaponFourteen.range + " m");

			Weapon weaponFifteen = new Weapon();
			weaponFifteen.weaponId = 15;
			weaponFifteen.weaponName = "FN SCAR";
			weaponFifteen.weaponMaterial = "Polymer and Aluminum";
			weaponFifteen.price = 22000.00;
			weaponFifteen.manufacturedYear = 2004;
			weaponFifteen.range = 800;
				System.out.println();
				System.out.println("Fifteenth weapon details :");
				System.out.println("id of weapon is : " + weaponFifteen.weaponId);
				System.out.println("name of the weapon is : " + weaponFifteen.weaponName);
				System.out.println("material of the weapon is : " + weaponFifteen.weaponMaterial);
				System.out.println("price of the weapon is  : " + weaponFifteen.price);
				System.out.println("manufactured year of the weapon is : " + weaponFifteen.manufacturedYear);
				System.out.println("range of the weapon is : " + weaponFifteen.range + " m");

			Weapon weaponSixteen = new Weapon();
			weaponSixteen.weaponId = 16;
			weaponSixteen.weaponName = "P90";
			weaponSixteen.weaponMaterial = "Polymer";
			weaponSixteen.price = 14000.00;
			weaponSixteen.manufacturedYear = 1990;
			weaponSixteen.range = 200;
				System.out.println();
				System.out.println("Sixteenth weapon details :");
				System.out.println("id of weapon is : " + weaponSixteen.weaponId);
				System.out.println("name of the weapon is : " + weaponSixteen.weaponName);
				System.out.println("material of the weapon is : " + weaponSixteen.weaponMaterial);
				System.out.println("price of the weapon is  : " + weaponSixteen.price);
				System.out.println("manufactured year of the weapon is : " + weaponSixteen.manufacturedYear);
				System.out.println("range of the weapon is : " + weaponSixteen.range + " m");

			Weapon weaponSeventeen = new Weapon();
			weaponSeventeen.weaponId = 17;
			weaponSeventeen.weaponName = "MG42";
			weaponSeventeen.weaponMaterial = "Steel";
			weaponSeventeen.price = 26000.00;
			weaponSeventeen.manufacturedYear = 1942;
			weaponSeventeen.range = 1000;
				System.out.println();
				System.out.println("Seventeenth weapon details :");
				System.out.println("id of weapon is : " + weaponSeventeen.weaponId);
				System.out.println("name of the weapon is : " + weaponSeventeen.weaponName);
				System.out.println("material of the weapon is : " + weaponSeventeen.weaponMaterial);
				System.out.println("price of the weapon is  : " + weaponSeventeen.price);
				System.out.println("manufactured year of the weapon is : " + weaponSeventeen.manufacturedYear);
				System.out.println("range of the weapon is : " + weaponSeventeen.range + " m");

			Weapon weaponEighteen = new Weapon();
			weaponEighteen.weaponId = 18;
			weaponEighteen.weaponName = "Thompson SMG";
			weaponEighteen.weaponMaterial = "Wood and Steel";
			weaponEighteen.price = 12000.00;
			weaponEighteen.manufacturedYear = 1920;
			weaponEighteen.range = 150;
				System.out.println();
				System.out.println("Eighteenth weapon details :");
				System.out.println("id of weapon is : " + weaponEighteen.weaponId);
				System.out.println("name of the weapon is : " + weaponEighteen.weaponName);
				System.out.println("material of the weapon is : " + weaponEighteen.weaponMaterial);
				System.out.println("price of the weapon is  : " + weaponEighteen.price);
				System.out.println("manufactured year of the weapon is : " + weaponEighteen.manufacturedYear);
				System.out.println("range of the weapon is : " + weaponEighteen.range + " m");

			Weapon weaponNineteen = new Weapon();
			weaponNineteen.weaponId = 19;
			weaponNineteen.weaponName = "RPG-7";
			weaponNineteen.weaponMaterial = "Steel and Wood";
			weaponNineteen.price = 30000.00;
			weaponNineteen.manufacturedYear = 1961;
			weaponNineteen.range = 500;
				System.out.println();
				System.out.println("Nineteenth weapon details :");
				System.out.println("id of weapon is : " + weaponNineteen.weaponId);
				System.out.println("name of the weapon is : " + weaponNineteen.weaponName);
				System.out.println("material of the weapon is : " + weaponNineteen.weaponMaterial);
				System.out.println("price of the weapon is  : " + weaponNineteen.price);
				System.out.println("manufactured year of the weapon is : " + weaponNineteen.manufacturedYear);
				System.out.println("range of the weapon is : " + weaponNineteen.range + " m");

			Weapon weaponTwenty = new Weapon();
			weaponTwenty.weaponId = 20;
			weaponTwenty.weaponName = "Mossberg 500";
			weaponTwenty.weaponMaterial = "Steel and Synthetic";
			weaponTwenty.price = 8000.00;
			weaponTwenty.manufacturedYear = 1960;
			weaponTwenty.range = 45;
				System.out.println();
				System.out.println("Twentieth weapon details :");
				System.out.println("id of weapon is : " + weaponTwenty.weaponId);
				System.out.println("name of the weapon is : " + weaponTwenty.weaponName);
				System.out.println("material of the weapon is : " + weaponTwenty.weaponMaterial);
				System.out.println("price of the weapon is  : " + weaponTwenty.price);
				System.out.println("manufactured year of the weapon is : " + weaponTwenty.manufacturedYear);
				System.out.println("range of the weapon is : " + weaponTwenty.range + " m");
				
		System.out.println("main ended");
	}
}